//! Project templates + scaffolding.
//!
//! `inf new` (and the editor's New Project dialog) scaffold a project directory
//! from a template: a real user cargo crate (where hand-written gameplay + the
//! P6-generated Rust will live), the `inf.toml` manifest, the content root, and
//! **a boot scene under `Content/Levels/`**.
//!
//! # The IB-7 ruling
//!
//! All four templates scaffold a boot level, and it lands where `inf cook`
//! looks. Before the island phase, two of the four scaffolded no level at all
//! and the other two scaffolded one into `<root>/Levels/` — a directory the cook
//! never opens — so **four of four produced a project `inf cook` refused**. See
//! [`Project::levels_root`](crate::Project::levels_root) for why levels are
//! content rather than a parallel root, and `inf-player`'s `first_run_path` for
//! the arm that runs `new` → `cook` → the shipped player on every template.

use std::path::{Path, PathBuf};

use crate::error::{ProjectError, Result};
use crate::manifest::ProjectManifest;

/// A first-run project template.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ProjectTemplate {
    /// Empty 3D scene.
    Blank3d,
    /// 2D side-scroller starter.
    Platformer2d,
    /// First-person starter.
    FirstPerson,
    /// Hybrid 2.5D starter: a 3D ground plane with billboarded sprites (P8.4b).
    Hybrid25d,
}

impl ProjectTemplate {
    pub fn slug(self) -> &'static str {
        match self {
            ProjectTemplate::Blank3d => "blank-3d",
            ProjectTemplate::Platformer2d => "2d-platformer",
            ProjectTemplate::FirstPerson => "first-person",
            ProjectTemplate::Hybrid25d => "hybrid-2.5d",
        }
    }

    pub fn label(self) -> &'static str {
        match self {
            ProjectTemplate::Blank3d => "Blank 3D",
            ProjectTemplate::Platformer2d => "2D Platformer",
            ProjectTemplate::FirstPerson => "First Person",
            ProjectTemplate::Hybrid25d => "Hybrid 2.5D",
        }
    }

    pub fn description(self) -> &'static str {
        match self {
            ProjectTemplate::Blank3d => "An empty 3D scene — a clean slate.",
            ProjectTemplate::Platformer2d => "A 2D side-scroller starter.",
            ProjectTemplate::FirstPerson => "A first-person starter.",
            ProjectTemplate::Hybrid25d => {
                "A 2.5D scene: a 3D ground plane with billboarded sprites."
            }
        }
    }

    pub fn from_slug(slug: &str) -> Option<Self> {
        Self::all().iter().copied().find(|t| t.slug() == slug)
    }

    pub fn all() -> &'static [ProjectTemplate] {
        &[
            ProjectTemplate::Blank3d,
            ProjectTemplate::Platformer2d,
            ProjectTemplate::FirstPerson,
            ProjectTemplate::Hybrid25d,
        ]
    }

    /// The committed starter `.inf_lvl` this template scaffolds into
    /// [`Project::levels_root`](crate::Project::levels_root) — its **boot
    /// scene**.
    ///
    /// # Every template ships one, and that is the IB-7 ruling's other half
    ///
    /// Two of the four used to return `None`, and a project with no level is a
    /// project `inf cook` refuses: *"no levels in cook — the build has no boot
    /// scene"*. Moving levels under `Content/` fixes where a level is found; it
    /// does not conjure one for a template that scaffolds none. So Blank 3D and
    /// 2D Platformer got starter scenes (`samples::blank3d_scene`,
    /// `samples::platformer_scene`), and `inf new` → `inf cook` → run is now a
    /// property of **all four**, asserted by `inf-player`'s `first_run_path`.
    ///
    /// All four payloads are generated by `inf_editor_core::samples` and blessed
    /// by `committed_sample_matches_generators`, so there is one definition of
    /// each scene in this repository and these bytes are locked to it.
    pub fn starter_level(self) -> StarterLevel {
        match self {
            ProjectTemplate::Blank3d => StarterLevel {
                file_name: "Main.inf_lvl",
                payload: include_bytes!("../../../templates/blank-3d/Blank.inf_lvl"),
                sidecar: include_bytes!("../../../templates/blank-3d/Blank.inf_lvl.toml"),
            },
            ProjectTemplate::Platformer2d => StarterLevel {
                file_name: "Main.inf_lvl",
                payload: include_bytes!("../../../templates/2d-platformer/Platformer.inf_lvl"),
                sidecar: include_bytes!("../../../templates/2d-platformer/Platformer.inf_lvl.toml"),
            },
            ProjectTemplate::FirstPerson => StarterLevel {
                file_name: "Main.inf_lvl",
                payload: include_bytes!("../../../templates/first-person/FirstPerson.inf_lvl"),
                sidecar: include_bytes!("../../../templates/first-person/FirstPerson.inf_lvl.toml"),
            },
            ProjectTemplate::Hybrid25d => StarterLevel {
                file_name: "Main.inf_lvl",
                payload: include_bytes!("../../../templates/hybrid-2.5d/Hybrid.inf_lvl"),
                sidecar: include_bytes!("../../../templates/hybrid-2.5d/Hybrid.inf_lvl.toml"),
            },
        }
    }

    /// Extra content files scaffolded **beside** the boot level, relative to the
    /// project's content root: `(relative path, bytes)`.
    ///
    /// The 2D platformer's level carries an `ActorClass` binding, and an asset
    /// GUID with no asset behind it is a player that does not move. A template's
    /// promise is a project that runs, so what the boot scene binds ships with
    /// it.
    pub fn starter_content(self) -> &'static [(&'static str, &'static [u8])] {
        match self {
            ProjectTemplate::Platformer2d => &[
                (
                    "Coyote.inf_act",
                    include_bytes!("../../../templates/2d-platformer/Coyote.inf_act"),
                ),
                (
                    "Coyote.inf_act.toml",
                    include_bytes!("../../../templates/2d-platformer/Coyote.inf_act.toml"),
                ),
            ],
            _ => &[],
        }
    }

    fn starter_lib(self, crate_name: &str) -> String {
        let doc = match self {
            ProjectTemplate::Blank3d => "an empty 3D scene",
            ProjectTemplate::Platformer2d => "a 2D platformer",
            ProjectTemplate::FirstPerson => "a first-person game",
            ProjectTemplate::Hybrid25d => "a hybrid 2.5D scene",
        };
        format!(
            "//! `{crate_name}` — gameplay for {doc}.\n\
             //!\n\
             //! Hand-written systems live here; Infinity Blueprints (Phase 6) generate\n\
             //! additional Rust into this crate and stay in sync.\n\
             //!\n\
             //! Generated blueprint code lives in `src/blueprints/` and is COMMITTED,\n\
             //! not ignored — it is what cargo compiles and what ships. The editor's\n\
             //! Code tab writes it; each file carries the graph hash it came from and\n\
             //! is rewritten when that goes stale.\n\
             \n\
             pub mod blueprints;\n\
             \n\
             /// Called once when play begins.\n\
             pub fn begin_play() {{\n    \
                 // Your setup here.\n\
             }}\n\
             \n\
             /// Called every frame with the delta time in seconds.\n\
             pub fn tick(_dt: f32) {{\n    \
                 // Your per-frame logic here.\n\
             }}\n"
        )
    }
}

/// A template's committed boot scene: the payload **and its sidecar**.
///
/// The sidecar is not decoration. `AssetDb` synthesizes a **content-derived**
/// GUID for a loose payload that has none, so a level scaffolded without one
/// gets a different identity in every project it is scaffolded into — and the
/// `ActorClass` bindings inside it name asset GUIDs that must resolve. The
/// scaffold wrote the payload alone until IB-7; this type is why it cannot
/// again.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct StarterLevel {
    /// The file name written under the project's levels root.
    pub file_name: &'static str,
    /// The `.inf_lvl` bincode payload.
    pub payload: &'static [u8],
    /// The `.inf_lvl.toml` asset sidecar (GUID, kind, content hash, deps).
    pub sidecar: &'static [u8],
}

/// The result of scaffolding: where the project was created.
#[derive(Debug, Clone)]
pub struct Scaffolded {
    pub root: PathBuf,
    pub crate_name: String,
    pub manifest: ProjectManifest,
}

/// Scaffold a new project named `name` from `template` inside `parent`. The
/// project directory is `parent/<sanitized-name>`; it must not already exist
/// (or must be empty). Returns the created root.
pub fn scaffold(parent: &Path, name: &str, template: ProjectTemplate) -> Result<Scaffolded> {
    let dir_name = sanitize_dir(name);
    let crate_name = sanitize_crate(name);
    let root = parent.join(&dir_name);

    if root.exists() && std::fs::read_dir(&root)?.next().is_some() {
        return Err(ProjectError::Other(format!(
            "{} already exists and is not empty",
            root.display()
        )));
    }

    let manifest = ProjectManifest::new(name, template.slug());
    manifest.save(&root)?;

    // User cargo crate.
    write(&root.join("Cargo.toml"), &cargo_toml(&crate_name))?;
    write(&root.join("src/lib.rs"), &template.starter_lib(&crate_name))?;
    // **`src/blueprints/` exists from day one** (Wave D), with an index that
    // compiles. `lib.rs` declares `pub mod blueprints;` above, so a project
    // scaffolded and immediately built has to find something there — an empty
    // directory would make every new project fail `cargo build` until its first
    // blueprint, which is the worst possible first impression.
    //
    // Only NEW projects get this. An existing project's hand-written `lib.rs` is
    // not edited behind its author's back; the editor's Code tab creates the
    // directory and the index on first use and the author adds the one line.
    write(
        &root.join("src/blueprints/mod.rs"),
        "// @generated by Infinity Engine — edits may be overwritten.\n\
         //\n\
         // One `pub mod` per generated blueprint class. Rebuilt from the directory\n\
         // whenever the editor writes a class, so a deleted one's line goes with it.\n",
    )?;

    // Content root + the levels root INSIDE it (IB-7). Kept in git with a
    // placeholder so an empty project still round-trips through a clone.
    let content_root = root.join(&manifest.content_dir);
    let levels_root = content_root.join(&manifest.levels_dir);
    write(&content_root.join(".gitkeep"), "")?;
    write(&levels_root.join(".gitkeep"), "")?;

    // The boot scene — payload AND sidecar, so the level keeps its identity and
    // its bindings resolve. Every template ships one (IB-7).
    let level = template.starter_level();
    let level_path = levels_root.join(level.file_name);
    std::fs::create_dir_all(&levels_root)?;
    inf_asset::write_atomically(&level_path, level.payload)?;
    inf_asset::write_atomically(
        &levels_root.join(format!("{}.toml", level.file_name)),
        level.sidecar,
    )?;

    // …and whatever the boot scene binds, beside it under the content root.
    for (rel, bytes) in template.starter_content() {
        let path = content_root.join(rel);
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        inf_asset::write_atomically(&path, *bytes)?;
    }

    write(&root.join(".gitignore"), GITIGNORE)?;
    write(
        &root.join("README.md"),
        &format!(
            "# {name}\n\nAn Infinity Engine project ({}).\n\nOpen it in Infinity Engine, or build the gameplay crate with `cargo build`.\n",
            template.label()
        ),
    )?;

    Ok(Scaffolded {
        root,
        crate_name,
        manifest,
    })
}

fn write(path: &Path, contents: &str) -> Result<()> {
    inf_asset::write_atomically(path, contents)?;
    Ok(())
}

fn cargo_toml(crate_name: &str) -> String {
    format!(
        "[package]\n\
         name = \"{crate_name}\"\n\
         version = \"0.1.0\"\n\
         edition = \"2021\"\n\
         \n\
         [lib]\n\
         crate-type = [\"lib\"]\n\
         \n\
         [dependencies]\n"
    )
}

const GITIGNORE: &str = "/target\n/Content/.inf/\n*.inf_lvl.autosave\ncrash-recovery.inf_lvl\n";

/// A filesystem-safe directory name (spaces → hyphens, alnum/-/_ kept).
pub fn sanitize_dir(name: &str) -> String {
    let s: String = name
        .trim()
        .chars()
        .map(|c| {
            if c.is_alphanumeric() || c == '-' || c == '_' {
                c
            } else {
                '-'
            }
        })
        .collect();
    let trimmed = s.trim_matches('-').to_string();
    if trimmed.is_empty() {
        "InfinityProject".to_string()
    } else {
        trimmed
    }
}

/// A valid `snake_case` crate name.
pub fn sanitize_crate(name: &str) -> String {
    let mut out = String::new();
    for c in name.chars() {
        if c.is_alphanumeric() {
            out.extend(c.to_lowercase());
        } else if !out.ends_with('_') {
            out.push('_');
        }
    }
    let trimmed = out.trim_matches('_').to_string();
    if trimmed.is_empty() || trimmed.chars().next().unwrap().is_numeric() {
        format!("game_{trimmed}")
    } else {
        trimmed
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn scaffold_writes_a_valid_project() {
        let parent = tempfile::tempdir().unwrap();
        let s = scaffold(parent.path(), "My Cool Game!", ProjectTemplate::Blank3d).unwrap();
        assert!(s.root.join("inf.toml").exists());
        assert!(s.root.join("Cargo.toml").exists());
        assert!(s.root.join("src/lib.rs").exists());
        // **Wave D: `lib.rs` declares the blueprints module, so the module has
        // to exist.** A scaffolded project that does not compile until its first
        // blueprint is the worst possible first impression, and the two halves
        // of that claim are one line apart on purpose.
        let lib = std::fs::read_to_string(s.root.join("src/lib.rs")).unwrap();
        assert!(lib.contains("pub mod blueprints;"), "{lib}");
        assert!(s.root.join("src/blueprints/mod.rs").exists());
        assert!(s.root.join("Content/.gitkeep").exists());
        // IB-7: the levels root is under Content/, and the pre-ruling location
        // is not created at all.
        assert!(s.root.join("Content/Levels/.gitkeep").exists());
        assert!(
            !s.root.join("Levels").exists(),
            "the pre-ruling <root>/Levels/ must not be scaffolded any more"
        );
        assert_eq!(s.crate_name, "my_cool_game");
        // The manifest reloads.
        let m = ProjectManifest::load(&s.root).unwrap();
        assert_eq!(m.name, "My Cool Game!");
        assert_eq!(m.template, "blank-3d");
        // The Cargo.toml names the sanitized crate.
        let cargo = std::fs::read_to_string(s.root.join("Cargo.toml")).unwrap();
        assert!(cargo.contains("name = \"my_cool_game\""));
    }

    #[test]
    fn refuses_a_non_empty_target() {
        let parent = tempfile::tempdir().unwrap();
        scaffold(parent.path(), "Dup", ProjectTemplate::Blank3d).unwrap();
        assert!(scaffold(parent.path(), "Dup", ProjectTemplate::Blank3d).is_err());
    }

    #[test]
    fn slug_round_trips() {
        for &t in ProjectTemplate::all() {
            assert_eq!(ProjectTemplate::from_slug(t.slug()), Some(t));
        }
    }

    /// **Every template scaffolds a boot scene, under `Content/Levels/`** — the
    /// IB-7 ruling at the scaffold door.
    ///
    /// The old version of this test asserted the opposite half by name
    /// (`assert!(ProjectTemplate::Blank3d.starter_level().is_none())`) and was
    /// green while `inf new --template blank-3d` produced a project the cook
    /// refused. A gate that pins the defect it was written beside is only useful
    /// while someone remembers it is doing that.
    #[test]
    fn every_template_scaffolds_a_boot_scene_under_content() {
        let parent = tempfile::tempdir().unwrap();
        let mut payloads: Vec<Vec<u8>> = Vec::new();
        for (i, &t) in ProjectTemplate::all().iter().enumerate() {
            let s = scaffold(parent.path(), &format!("Proj{i}"), t).unwrap();
            let levels = s
                .root
                .join(&s.manifest.content_dir)
                .join(&s.manifest.levels_dir);
            let starter = t.starter_level();
            let level = levels.join(starter.file_name);
            let side = levels.join(format!("{}.toml", starter.file_name));
            assert!(level.exists(), "{} scaffolds no boot scene", t.slug());
            assert!(
                side.exists(),
                "{} scaffolds a boot scene with no sidecar, so its GUID would be \
                 content-derived and its bindings would not resolve",
                t.slug()
            );
            let bytes = std::fs::read(&level).unwrap();
            assert!(!bytes.is_empty());
            assert_eq!(bytes, starter.payload);
            assert_eq!(std::fs::read(&side).unwrap(), starter.sidecar);
            // Whatever the boot scene binds ships beside it.
            for (rel, want) in t.starter_content() {
                let p = s.root.join(&s.manifest.content_dir).join(rel);
                assert!(p.exists(), "{}: {rel} was not scaffolded", t.slug());
                assert_eq!(&std::fs::read(&p).unwrap()[..], *want);
            }
            payloads.push(bytes);
        }
        // ANTI-VACUITY: four *different* scenes, not one file copied four times
        // — which would satisfy every assertion above.
        let mut uniq = payloads.clone();
        uniq.sort();
        uniq.dedup();
        assert_eq!(
            uniq.len(),
            ProjectTemplate::all().len(),
            "the templates do not ship distinct boot scenes"
        );
    }

    /// The 2D platformer's boot scene binds a blueprint, and the sidecar beside
    /// that blueprint carries the GUID the binding names.
    #[test]
    fn the_platformer_template_ships_the_actor_its_level_binds() {
        let extra = ProjectTemplate::Platformer2d.starter_content();
        assert_eq!(extra.len(), 2, "the actor payload and its sidecar");
        let side = std::str::from_utf8(extra[1].1).unwrap();
        assert!(
            side.contains("guid = "),
            "the actor sidecar must name a stable GUID, else the level's \
             ActorClass binding resolves to nothing: {side}"
        );
    }

    #[test]
    fn crate_names_are_valid() {
        assert_eq!(sanitize_crate("My Game"), "my_game");
        assert_eq!(sanitize_crate("123"), "game_123");
        assert_eq!(sanitize_crate("!!!"), "game_");
    }
}
