// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * **One entry of a mesh session's history** (Wave D — the history panel).
 */
export type DccHistoryEntryDto = { 
/**
 * Its index in the journal — what `dcc_amend` takes.
 */
index: number, 
/**
 * A one-word name for the op ("extrude", "bevel", "sculpt stroke").
 */
kind: string, 
/**
 * Whether it is still applied, or sits in the redo tail past the cursor.
 */
applied: boolean, 
/**
 * **The single number an author may drag**, when the op has one — an
 * extrude's distance, an inset's or bevel's amount, a mirror's coordinate,
 * a split's parameter. `None` for an op with nothing scalar to change,
 * which is most of them.
 *
 * One number and not a form, deliberately: the ops an author reaches back
 * for are the ones with a magnitude, and a general parameter editor over a
 * wire enum is a second reflection system this codebase has already refused
 * once (the memo's no-DNA/RNA ruling).
 */
value: number | null, 
/**
 * A unit for it, for the row's label: `"m"`, `"°"`, `""`.
 */
unit: string, 
/**
 * Whether [`inf_dcc::op_amendable`] permits re-parameterizing it at all.
 */
amendable: boolean, 
/**
 * Why not, when it does not. Never empty when `amendable` is false — the
 * Wave-E invariant "a route or a reason, never neither", applied to a row.
 */
reason: string | null, };
