/**
 * Typed IPC layer — the ONLY place `invoke` is called.
 *
 * Convention (engine-wide): every backend `#[tauri::command]` gets a typed
 * wrapper here, grouped by domain. Components import these wrappers, never
 * `invoke` directly. Payload types come from `src/bindings/` — generated by
 * ts-rs from `inf_editor_core::ipc` (CI drift-checked), never hand-written.
 * Events use namespaced channels (`log://line`, `viewport://rect`,
 * `assets://changed/{id}`, …) via lib/events.ts.
 */
import { invoke } from "@tauri-apps/api/core";

import type {
  BpDoc,
  BpEdit,
  GraphApplyResult,
  GraphRunResult,
  NodeDef,
} from "./blueprintTypes";
import type { MaterialCompileResult } from "./materialTypes";
import type { PcgCompileResult, PcgEvaluateResult } from "./pcgTypes";
import type { AssetRefDto } from "../bindings/AssetRefDto";
import type { AssetSnapshot } from "../bindings/AssetSnapshot";
import type { DataAssetDto } from "../bindings/DataAssetDto";
import type { DataFieldDto } from "../bindings/DataFieldDto";
import type { DeleteResult } from "../bindings/DeleteResult";
import type { DetailsDto } from "../bindings/DetailsDto";
import type { ErosionParamsDto } from "../bindings/ErosionParamsDto";
import type { ErosionReportDto } from "../bindings/ErosionReportDto";
import type { FileEntryDto } from "../bindings/FileEntryDto";
import type { GitStatusDto } from "../bindings/GitStatusDto";
import type { LayoutSummary } from "../bindings/LayoutSummary";
import type { PackageErrorDto } from "../bindings/PackageErrorDto";
import type { PackageResultDto } from "../bindings/PackageResultDto";
import type { ProjectInfoDto } from "../bindings/ProjectInfoDto";
import type { ProjectSettingsDto } from "../bindings/ProjectSettingsDto";
import type { ProjectTemplateDto } from "../bindings/ProjectTemplateDto";
import type { PropValueDto } from "../bindings/PropValueDto";
import type { RecentProjectDto } from "../bindings/RecentProjectDto";
import type { SearchHitDto } from "../bindings/SearchHitDto";
import type { SculptSettingsDto } from "../bindings/SculptSettingsDto";
import type { SearchOptsDto } from "../bindings/SearchOptsDto";
import type { SceneSnapshot } from "../bindings/SceneSnapshot";
import type { Snap2DDto } from "../bindings/Snap2DDto";
import type { SortingLayerDto } from "../bindings/SortingLayerDto";
import type { SpawnKind } from "../bindings/SpawnKind";
import type { SpriteSheetDto } from "../bindings/SpriteSheetDto";
import type { TilemapCellDto } from "../bindings/TilemapCellDto";
import type { TilemapDto } from "../bindings/TilemapDto";
import type { ToolModeDto } from "../bindings/ToolModeDto";
import type { ViewportDrop } from "../bindings/ViewportDrop";
import type { ViewportModeDto } from "../bindings/ViewportModeDto";
import type { ViewportRect } from "../bindings/ViewportRect";

export type {
  AssetRefDto,
  AssetSnapshot,
  DataAssetDto,
  DataFieldDto,
  DeleteResult,
  DetailsDto,
  FileEntryDto,
  GitStatusDto,
  LayoutSummary,
  PackageErrorDto,
  PackageResultDto,
  ProjectInfoDto,
  ProjectTemplateDto,
  ProjectSettingsDto,
  PropValueDto,
  RecentProjectDto,
  SearchHitDto,
  SearchOptsDto,
  SceneSnapshot,
  Snap2DDto,
  SortingLayerDto,
  SpawnKind,
  SpriteSheetDto,
  TilemapCellDto,
  TilemapDto,
  ViewportDrop,
  ViewportModeDto,
  ViewportRect,
};

export const app = {
  /** Editor backend version, shown in the status bar. */
  version: (): Promise<string> => invoke<string>("app_version"),
};

/**
 * Embedded terminal (P5.3). A session is a real PTY in the backend; output
 * streams on `pty://output/{id}` (see lib/events.ts). Arg names are camelCase.
 */
export const pty = {
  /** Open a session in `cwd` sized `cols`×`rows`; returns the session id. */
  create: (cwd: string | null, cols: number, rows: number): Promise<string> =>
    invoke<string>("pty_create", { cwd, cols, rows }),
  write: (id: string, data: string): Promise<void> => invoke("pty_write", { id, data }),
  resize: (id: string, cols: number, rows: number): Promise<void> =>
    invoke("pty_resize", { id, cols, rows }),
  close: (id: string): Promise<void> => invoke("pty_close", { id }),
};

/** Named dock-layout presets, persisted in the app config dir (P1.2.5). */
export const layouts = {
  save: (name: string, json: string): Promise<void> => invoke("layout_save", { name, json }),
  load: (name: string): Promise<string | null> => invoke("layout_load", { name }),
  list: (): Promise<LayoutSummary[]> => invoke("layout_list"),
  delete: (name: string): Promise<boolean> => invoke("layout_delete", { name }),
};

export const viewport = {
  /** Create (once) the native engine viewport inside this window. */
  attach: (): Promise<void> => invoke("viewport_attach"),
  /**
   * Report the viewport hole's rectangle in PHYSICAL pixels relative to the
   * window client area (see `toPhysicalRect` in lib/viewportRect.ts).
   */
  setRect: (rect: ViewportRect): Promise<void> => invoke("viewport_set_rect", { rect }),
  /**
   * Show/hide the native viewport (the shell hides it while an HTML overlay
   * — menu, palette, dialog, drag ghost — is open; airspace rule).
   */
  setVisible: (visible: boolean): Promise<void> => invoke("viewport_set_visible", { visible }),
  /**
   * Hand off a drag that ended over the viewport hole. Coordinates are
   * PHYSICAL pixels relative to the hole's top-left corner (HTML drag ghosts
   * die over the native window — the drop point crosses via IPC instead).
   */
  drop: (drop: ViewportDrop): Promise<void> => invoke("viewport_drop", { drop }),
  /** Switch the active projection (Perspective ↔ 2D ortho) (P8.2c). */
  setMode: (mode: ViewportModeDto): Promise<void> => invoke("viewport_set_mode", { mode }),
  /** Push the 2D-mode grid/pixel snapping configuration to the viewport. */
  setSnap2d: (snap: Snap2DDto): Promise<void> => invoke("viewport_set_snap2d", { snap }),
  /** Switch the active tool (Select ↔ Sculpt terrain) (P10.2b). */
  setToolMode: (mode: ToolModeDto): Promise<void> =>
    invoke("viewport_set_tool_mode", { mode }),
  /** Push the sculpt brush configuration (op / radius / strength / falloff). */
  setSculpt: (sculpt: SculptSettingsDto): Promise<void> =>
    invoke("viewport_set_sculpt", { sculpt }),
};

/**
 * Terrain erosion bake (P10.3b). Runs the GPU hydraulic + thermal erosion
 * compute pipeline (CPU reference fallback with no adapter) over the entity's
 * terrain and commits ONE undoable height delta. `region` is an optional
 * terrain-local `[minX, minZ, maxX, maxZ]`; omit to erode the whole terrain.
 */
export const terrain = {
  erode: (
    entity: string,
    params: ErosionParamsDto,
    steps: number,
    region?: [number, number, number, number],
  ): Promise<ErosionReportDto> =>
    invoke<ErosionReportDto>("terrain_erode", { entity, params, steps, region: region ?? null }),
};

/**
 * Per-project editor settings (P8.2c): pixels-per-unit for 2D pixel snapping,
 * persisted under `<content-root>/.infinity/settings.toml`. `set` returns the
 * normalized values.
 */
export const projectSettings = {
  get: (): Promise<ProjectSettingsDto> => invoke<ProjectSettingsDto>("project_settings_get"),
  set: (settings: ProjectSettingsDto): Promise<ProjectSettingsDto> =>
    invoke<ProjectSettingsDto>("project_settings_set", { settings }),
};

/**
 * Scene / world binding (Phase 3). The authoritative ECS world lives in the
 * backend; these mutate it and the frontend re-syncs from the returned value or
 * the `world://delta` event. Arg names are camelCase (Tauri maps to snake_case).
 */
export const scene = {
  snapshot: (): Promise<SceneSnapshot> => invoke<SceneSnapshot>("scene_snapshot"),
  details: (): Promise<DetailsDto> => invoke<DetailsDto>("scene_details"),
  create: (kind: SpawnKind, parent: string | null): Promise<string> =>
    invoke<string>("scene_create", { kind, parent }),
  delete: (guids: string[]): Promise<void> => invoke("scene_delete", { guids }),
  rename: (guid: string, name: string): Promise<void> => invoke("scene_rename", { guid, name }),
  reparent: (guid: string, parent: string | null): Promise<boolean> =>
    invoke<boolean>("scene_reparent", { guid, parent }),
  setVisible: (guid: string, visible: boolean): Promise<void> =>
    invoke("scene_set_visible", { guid, visible }),
  select: (guids: string[], additive: boolean): Promise<void> =>
    invoke("scene_select", { guids, additive }),
  setProperty: (
    guids: string[],
    typePath: string,
    field: string,
    value: PropValueDto,
  ): Promise<DetailsDto> =>
    invoke<DetailsDto>("scene_set_property", { guids, typePath, field, value }),
  resetProperty: (guids: string[], typePath: string, field: string): Promise<DetailsDto> =>
    invoke<DetailsDto>("scene_reset_property", { guids, typePath, field }),
  undo: (): Promise<void> => invoke("scene_undo"),
  redo: (): Promise<void> => invoke("scene_redo"),
  /** Save to `path`, or a default quicksave when omitted. */
  save: (path: string | null = null): Promise<void> => invoke("scene_save", { path }),
  open: (path: string | null = null): Promise<SceneSnapshot> =>
    invoke<SceneSnapshot>("scene_open", { path }),
  newScene: (): Promise<SceneSnapshot> => invoke<SceneSnapshot>("scene_new"),
  /** Write the crash-recovery file if there are unsaved changes. */
  autosave: (): Promise<void> => invoke("scene_autosave"),
  /** Spawn a Content-Drawer asset dropped over the viewport (P4.4). */
  spawnAsset: (assetId: string): Promise<string> =>
    invoke<string>("scene_spawn_asset", { assetId }),
  /**
   * Apply a material asset's PBR parameters to entities (P7.1). `targets`
   * defaults to the current selection. Resolves to how many were updated.
   */
  applyMaterial: (assetId: string, targets: string[] | null = null): Promise<number> =>
    invoke<number>("scene_apply_material", { assetId, targets }),
  /**
   * Bind a `.inf_act` blueprint-class asset to entities (P9.5). Sets each
   * target's `ActorClass` link to the asset GUID; `targets` defaults to the
   * current selection. Resolves to how many entities were (re)bound.
   */
  applyActor: (assetId: string, targets: string[] | null = null): Promise<number> =>
    invoke<number>("scene_apply_actor", { assetId, targets }),
  /**
   * Apply a texture's sprite-sheet slice to entities (P8.2a). `slice` is a
   * resolved slice name (grid cells are index-named "0","1",…; manual rects use
   * their names). `resizeToSlice` sets the quad size from the slice's pixel
   * aspect. `targets` defaults to the current selection; resolves to how many
   * entities were updated.
   */
  applySpriteSlice: (
    assetId: string,
    slice: string,
    resizeToSlice: boolean,
    targets: string[] | null = null,
  ): Promise<number> =>
    invoke<number>("scene_apply_sprite_slice", { assetId, slice, targets, resizeToSlice }),
};

/**
 * Tilemap painting (P8.2b). `get` projects the selected entity's tilemap for
 * the Tilemap paint panel; `paint` applies one stroke (mouse-down→up batch or a
 * bounded flood-fill) as a single undo step. Tile indices are 1-based atlas
 * cells (`0` erases). Arg names are camelCase (Tauri maps to snake_case).
 */
export const tilemap = {
  get: (entity: string): Promise<TilemapDto | null> =>
    invoke<TilemapDto | null>("tilemap_get", { entity }),
  paint: (entity: string, cells: TilemapCellDto[]): Promise<number> =>
    invoke<number>("tilemap_paint", { entity, cells }),
};

/**
 * Sprite-sheet slicing (P8.2a). A texture asset's slice model is persisted into
 * its sidecar; the Sprite Sheet panel reads it, edits it live, and saves.
 */
export const texture = {
  getSlices: (id: string): Promise<SpriteSheetDto> =>
    invoke<SpriteSheetDto>("texture_get_slices", { id }),
  setSlices: (slices: SpriteSheetDto): Promise<void> =>
    invoke("texture_set_slices", { slices }),
};

/**
 * Sorting-layer registry (P8.2a): a per-project map of `i32` layer ids → names,
 * managed from the "Sorting Layers" dialog. `set` returns the normalized list.
 */
export const layers = {
  get: (): Promise<SortingLayerDto[]> => invoke<SortingLayerDto[]>("layers_get"),
  set: (rows: SortingLayerDto[]): Promise<SortingLayerDto[]> =>
    invoke<SortingLayerDto[]>("layers_set", { layers: rows }),
};

/**
 * Asset system / Content Drawer (Phase 4). The asset database lives in the
 * backend under the project content root; the store loads `assets_snapshot`
 * and re-fetches on the `assets://changed` event. Thumbnails are lazy PNG
 * data-URLs. Arg names are camelCase (Tauri maps to snake_case).
 */
export const assets = {
  snapshot: (): Promise<AssetSnapshot> => invoke<AssetSnapshot>("assets_snapshot"),
  /** Assets that reference `id` (Show References / delete warning). */
  references: (id: string): Promise<AssetRefDto[]> =>
    invoke<AssetRefDto[]>("asset_references", { id }),
  /** A PNG data-URL thumbnail, or null for icon-only kinds / no GPU. */
  thumbnail: (id: string): Promise<string | null> =>
    invoke<string | null>("asset_thumbnail", { id }),
  /** Queue external files for import; progress arrives on `assets://import`. */
  import: (sources: string[], destFolder: string | null = null): Promise<number[]> =>
    invoke<number[]>("asset_import", { sources, destFolder }),
  /** Create a new authored asset (Phase 4.4: "material"). Returns the GUID. */
  create: (kind: string, folder: string | null = null, name: string | null = null): Promise<string> =>
    invoke<string>("asset_create", { kind, folder, name }),
  /** Create a material instance overriding a parent material (P7.4). */
  createMaterialInstance: (parentId: string, name: string | null = null): Promise<string> =>
    invoke<string>("asset_create_material_instance", { parentId, name }),
  /** Delete; when still referenced (and not forced) returns the blockers. */
  delete: (id: string, force = false): Promise<DeleteResult> =>
    invoke<DeleteResult>("asset_delete", { id, force }),
  rename: (id: string, name: string): Promise<void> => invoke("asset_rename", { id, name }),
  duplicate: (id: string): Promise<string> => invoke<string>("asset_duplicate", { id }),
  setTags: (id: string, tags: string[]): Promise<void> => invoke("asset_set_tags", { id, tags }),
  /** Load a data asset (struct/enum/table) for editing; null if not a data kind. */
  data: (id: string): Promise<DataAssetDto | null> =>
    invoke<DataAssetDto | null>("asset_data", { id }),
  dataSave: (dataAsset: DataAssetDto): Promise<void> =>
    invoke("asset_data_save", { dataAsset }),
  tableImport: (id: string, source: string): Promise<void> =>
    invoke("asset_table_import", { id, source }),
  rustSource: (id: string): Promise<string> => invoke<string>("asset_rust_source", { id }),
};

/**
 * Project system (Phase 5.5). Opening/creating a project re-roots the asset
 * database and emits `project://changed`. Arg names are camelCase.
 */
export const project = {
  templates: (): Promise<ProjectTemplateDto[]> =>
    invoke<ProjectTemplateDto[]>("project_templates"),
  recent: (): Promise<RecentProjectDto[]> => invoke<RecentProjectDto[]>("project_recent"),
  current: (): Promise<ProjectInfoDto | null> =>
    invoke<ProjectInfoDto | null>("project_current"),
  newProject: (parent: string, name: string, template: string): Promise<ProjectInfoDto> =>
    invoke<ProjectInfoDto>("project_new", { parent, name, template }),
  open: (root: string): Promise<ProjectInfoDto> => invoke<ProjectInfoDto>("project_open", { root }),
  close: (): Promise<void> => invoke("project_close"),
};

/** Project file surface (P5.4): read/write + a gitignore-aware listing. */
export const files = {
  read: (path: string): Promise<string> => invoke<string>("file_read", { path }),
  write: (path: string, content: string): Promise<void> =>
    invoke("file_write", { path, content }),
  list: (root: string): Promise<FileEntryDto[]> =>
    invoke<FileEntryDto[]>("list_project_files", { root }),
};

/** Git panel (P5.4): shells out to the `git` CLI. `repo` is the project root. */
export const git = {
  status: (repo: string): Promise<GitStatusDto> => invoke<GitStatusDto>("git_status", { repo }),
  stage: (repo: string, paths: string[]): Promise<void> => invoke("git_stage", { repo, paths }),
  unstage: (repo: string, paths: string[]): Promise<void> => invoke("git_unstage", { repo, paths }),
  discard: (repo: string, paths: string[]): Promise<void> => invoke("git_discard", { repo, paths }),
  commit: (repo: string, message: string): Promise<string> =>
    invoke<string>("git_commit", { repo, message }),
  fileDiff: (repo: string, path: string, staged: boolean): Promise<string> =>
    invoke<string>("git_file_diff", { repo, path, staged }),
  branches: (repo: string): Promise<string[]> => invoke<string[]>("git_branches", { repo }),
  init: (repo: string): Promise<void> => invoke("git_init", { repo }),
};

/** Global workspace search (P5.4). */
export const search = {
  workspace: (root: string, query: string, opts: SearchOptsDto): Promise<SearchHitDto[]> =>
    invoke<SearchHitDto[]>("search_workspace", { root, query, opts }),
};

/**
 * Language intelligence (P5.2): a rust-analyzer LSP client. `didOpen/didChange/
 * didClose` are fire-and-forget notifications; `request` pulls completion/hover/
 * definition; diagnostics arrive on the `lsp://diagnostics` event.
 */
export const lsp = {
  start: (language: string, workspace: string): Promise<void> =>
    invoke("lsp_start", { language, workspace }),
  stop: (language: string): Promise<void> => invoke("lsp_stop", { language }),
  didOpen: (language: string, path: string, text: string): Promise<void> =>
    invoke("lsp_did_open", { language, path, text }),
  didChange: (language: string, path: string, text: string): Promise<void> =>
    invoke("lsp_did_change", { language, path, text }),
  didClose: (language: string, path: string): Promise<void> =>
    invoke("lsp_did_close", { language, path }),
  // `params`/result are raw LSP JSON (opaque to the typed layer).
  request: (language: string, method: string, params: unknown): Promise<unknown> =>
    invoke<unknown>("lsp_request", { language, method, params }),
};

/**
 * Blueprint graphs (Phase 6). The visual node editor drives everything here:
 * fetch the palette, CRUD documents, apply edit batches (invariant-checked +
 * re-validated on the backend), run a graph through the interpreter, and read
 * the generated Rust. Types come from `./blueprintTypes` (mirrors of the
 * Ring-0 graph crate, not ts-rs). Edits are the kebab-case tagged union the
 * backend deserializes as `inf_graph::GraphEdit`.
 */
export const graph = {
  registry: (): Promise<NodeDef[]> => invoke<NodeDef[]>("graph_registry"),
  list: (): Promise<BpDoc[]> => invoke<BpDoc[]>("graph_list"),
  create: (name: string): Promise<BpDoc> => invoke<BpDoc>("graph_create", { name }),
  get: (id: string): Promise<BpDoc> => invoke<BpDoc>("graph_get", { id }),
  apply: (id: string, edits: BpEdit[], label: string): Promise<GraphApplyResult> =>
    invoke<GraphApplyResult>("graph_apply", { id, edits, label }),
  undo: (id: string): Promise<BpDoc | null> => invoke<BpDoc | null>("graph_undo", { id }),
  redo: (id: string): Promise<BpDoc | null> => invoke<BpDoc | null>("graph_redo", { id }),
  run: (id: string): Promise<GraphRunResult> => invoke<GraphRunResult>("graph_run", { id }),
  generate: (id: string): Promise<string> => invoke<string>("graph_generate", { id }),
};

/**
 * Material graphs (Phase 7.2). Mirrors the blueprint surface (CRUD + apply +
 * undo/redo over the shared `inf-graph` shapes), plus `compile`: the material
 * node graph → naga-validated WGSL, node-anchored diagnostics, and an offscreen
 * preview-sphere render (PNG data-URL). Documents share the `BpDoc`/`BpEdit`
 * shapes; only the compile result is material-specific.
 */
export const material = {
  registry: (): Promise<NodeDef[]> => invoke<NodeDef[]>("material_registry"),
  list: (): Promise<BpDoc[]> => invoke<BpDoc[]>("material_list"),
  create: (name: string): Promise<BpDoc> => invoke<BpDoc>("material_create", { name }),
  get: (id: string): Promise<BpDoc> => invoke<BpDoc>("material_get", { id }),
  apply: (id: string, edits: BpEdit[], label: string): Promise<GraphApplyResult> =>
    invoke<GraphApplyResult>("material_apply", { id, edits, label }),
  undo: (id: string): Promise<BpDoc | null> => invoke<BpDoc | null>("material_undo", { id }),
  redo: (id: string): Promise<BpDoc | null> => invoke<BpDoc | null>("material_redo", { id }),
  compile: (id: string): Promise<MaterialCompileResult> =>
    invoke<MaterialCompileResult>("material_compile", { id }),
  /** Bake the graph to a new `.inf_tex` asset via a compute pass; returns the id. */
  bake: (id: string, size: number, name: string): Promise<string> =>
    invoke<string>("material_bake", { id, size, name }),
};

/**
 * PCG graphs (Phase 10.5b). Mirrors the material surface (CRUD + apply +
 * undo/redo over the shared `inf-graph` shapes), plus `compile` (lower the graph
 * to the runtime `PcgDocument` + node-anchored diagnostics), `save` (persist the
 * graph into a `.inf_pcg` asset), and `evaluate` (scatter over the scene terrain
 * into the selected `PcgVolume`, refreshing the viewport). Documents share the
 * `BpDoc`/`BpEdit` shapes; only the compile/evaluate results are PCG-specific.
 */
export const pcg = {
  registry: (): Promise<NodeDef[]> => invoke<NodeDef[]>("pcg_registry"),
  list: (): Promise<BpDoc[]> => invoke<BpDoc[]>("pcg_list"),
  create: (name: string): Promise<BpDoc> => invoke<BpDoc>("pcg_create", { name }),
  get: (id: string): Promise<BpDoc> => invoke<BpDoc>("pcg_get", { id }),
  apply: (id: string, edits: BpEdit[], label: string): Promise<GraphApplyResult> =>
    invoke<GraphApplyResult>("pcg_apply", { id, edits, label }),
  undo: (id: string): Promise<BpDoc | null> => invoke<BpDoc | null>("pcg_undo", { id }),
  redo: (id: string): Promise<BpDoc | null> => invoke<BpDoc | null>("pcg_redo", { id }),
  compile: (id: string): Promise<PcgCompileResult> =>
    invoke<PcgCompileResult>("pcg_compile", { id }),
  /** Persist the graph to a `.inf_pcg` asset; returns the written file name. */
  save: (id: string, name: string): Promise<string> => invoke<string>("pcg_save", { id, name }),
  /** Scatter over the scene terrain into the target volume (null → selection). */
  evaluate: (id: string, entity: string | null): Promise<PcgEvaluateResult> =>
    invoke<PcgEvaluateResult>("pcg_evaluate", { id, entity }),
};

/**
 * Cook / Package (P9.2 item 3). Runs `inf_packager::cook` against the open
 * project on a blocking task and resolves to a `PackageResultDto`, or **rejects
 * with a structured `PackageErrorDto`** (blueprint failures carry the class +
 * handler anchor). Start/finish also broadcasts on `package://state`. Arg names
 * are camelCase (Tauri maps to snake_case); `outDir` defaults to `<project>/Build`
 * and `roots` (asset GUIDs) to the default root set.
 */
export const packaging = {
  cook: (outDir: string | null = null, roots: string[] | null = null): Promise<PackageResultDto> =>
    invoke<PackageResultDto>("project_package", { outDir, roots }),
};

/**
 * In-editor Simulate / Play (P8.4). Drives the `SimSession` over the live
 * `SceneDoc`: `start` snapshots the world + fires BeginPlay, `tick` advances one
 * frame with the currently-held actions (the backend owns fixed-step
 * accumulation), `stop` restores the pre-play world exactly. Running state also
 * broadcasts on the `sim://state` event (see lib/events.ts).
 */
export const sim = {
  /** Enter Simulate over the current scene. Rejects (e.g. no scene) with a message. */
  start: (): Promise<void> => invoke("sim_start"),
  /**
   * Advance one frame with the held actions (`["left","jump"]`). Resolves to
   * whether a session was running (false = no-op). Arg name is camelCase.
   */
  tick: (keys: string[]): Promise<boolean> => invoke<boolean>("sim_tick", { keys }),
  /** Exit Simulate, restoring the pre-play world. */
  stop: (): Promise<void> => invoke("sim_stop"),
  /** Whether a Simulate session is currently running (mount-time sync). */
  isRunning: (): Promise<boolean> => invoke<boolean>("sim_is_running"),
};

/**
 * Play-In-Editor (P9.4). Spawns `inf-player` as a crash-isolated subprocess and
 * streams the **live** scene (unsaved edits included) to it — the same content
 * path a shipped game uses. `start` mode is `"embedded"` (reparent the player
 * window into the viewport, Windows) or `"window"` ("Play in New Window",
 * always works). Session state broadcasts on `pie://state`.
 */
export const pie = {
  /** Start PIE in the given mode; resumes if already paused. */
  start: (mode: "embedded" | "window"): Promise<void> => invoke("pie_start", { mode }),
  /** Pause the running player. */
  pause: (): Promise<void> => invoke("pie_pause"),
  /** Resume a paused player. */
  resume: (): Promise<void> => invoke("pie_resume"),
  /** Advance exactly one fixed step (while paused). */
  step: (): Promise<void> => invoke("pie_step"),
  /** Release input possession back to the editor (v1 Eject). */
  eject: (): Promise<void> => invoke("pie_eject"),
  /** Stop PIE: kill the player, restore the viewport. */
  stop: (): Promise<void> => invoke("pie_stop"),
  /** Whether a PIE session is running (mount-time sync). */
  isRunning: (): Promise<boolean> => invoke<boolean>("pie_is_running"),
};
