/**
 * Typed IPC layer — the ONLY place `invoke` is called.
 *
 * Convention (engine-wide): every backend `#[tauri::command]` gets a typed
 * wrapper here, grouped by domain. Components import these wrappers, never
 * `invoke` directly. Payload types come from `src/bindings/` — generated by
 * ts-rs from `inf_editor_core::ipc` (CI drift-checked), never hand-written.
 * Events use namespaced channels (`log://line`, `viewport://rect`,
 * `assets://changed/{id}`, …) via lib/events.ts.
 */
import { invoke } from "@tauri-apps/api/core";

import type { AssetRefDto } from "../bindings/AssetRefDto";
import type { AssetSnapshot } from "../bindings/AssetSnapshot";
import type { DataAssetDto } from "../bindings/DataAssetDto";
import type { DataFieldDto } from "../bindings/DataFieldDto";
import type { DeleteResult } from "../bindings/DeleteResult";
import type { DetailsDto } from "../bindings/DetailsDto";
import type { LayoutSummary } from "../bindings/LayoutSummary";
import type { PropValueDto } from "../bindings/PropValueDto";
import type { SceneSnapshot } from "../bindings/SceneSnapshot";
import type { SpawnKind } from "../bindings/SpawnKind";
import type { ViewportDrop } from "../bindings/ViewportDrop";
import type { ViewportRect } from "../bindings/ViewportRect";

export type {
  AssetRefDto,
  AssetSnapshot,
  DataAssetDto,
  DataFieldDto,
  DeleteResult,
  DetailsDto,
  LayoutSummary,
  PropValueDto,
  SceneSnapshot,
  SpawnKind,
  ViewportDrop,
  ViewportRect,
};

export const app = {
  /** Editor backend version, shown in the status bar. */
  version: (): Promise<string> => invoke<string>("app_version"),
};

/** Named dock-layout presets, persisted in the app config dir (P1.2.5). */
export const layouts = {
  save: (name: string, json: string): Promise<void> => invoke("layout_save", { name, json }),
  load: (name: string): Promise<string | null> => invoke("layout_load", { name }),
  list: (): Promise<LayoutSummary[]> => invoke("layout_list"),
  delete: (name: string): Promise<boolean> => invoke("layout_delete", { name }),
};

export const viewport = {
  /** Create (once) the native engine viewport inside this window. */
  attach: (): Promise<void> => invoke("viewport_attach"),
  /**
   * Report the viewport hole's rectangle in PHYSICAL pixels relative to the
   * window client area (see `toPhysicalRect` in lib/viewportRect.ts).
   */
  setRect: (rect: ViewportRect): Promise<void> => invoke("viewport_set_rect", { rect }),
  /**
   * Show/hide the native viewport (the shell hides it while an HTML overlay
   * — menu, palette, dialog, drag ghost — is open; airspace rule).
   */
  setVisible: (visible: boolean): Promise<void> => invoke("viewport_set_visible", { visible }),
  /**
   * Hand off a drag that ended over the viewport hole. Coordinates are
   * PHYSICAL pixels relative to the hole's top-left corner (HTML drag ghosts
   * die over the native window — the drop point crosses via IPC instead).
   */
  drop: (drop: ViewportDrop): Promise<void> => invoke("viewport_drop", { drop }),
};

/**
 * Scene / world binding (Phase 3). The authoritative ECS world lives in the
 * backend; these mutate it and the frontend re-syncs from the returned value or
 * the `world://delta` event. Arg names are camelCase (Tauri maps to snake_case).
 */
export const scene = {
  snapshot: (): Promise<SceneSnapshot> => invoke<SceneSnapshot>("scene_snapshot"),
  details: (): Promise<DetailsDto> => invoke<DetailsDto>("scene_details"),
  create: (kind: SpawnKind, parent: string | null): Promise<string> =>
    invoke<string>("scene_create", { kind, parent }),
  delete: (guids: string[]): Promise<void> => invoke("scene_delete", { guids }),
  rename: (guid: string, name: string): Promise<void> => invoke("scene_rename", { guid, name }),
  reparent: (guid: string, parent: string | null): Promise<boolean> =>
    invoke<boolean>("scene_reparent", { guid, parent }),
  setVisible: (guid: string, visible: boolean): Promise<void> =>
    invoke("scene_set_visible", { guid, visible }),
  select: (guids: string[], additive: boolean): Promise<void> =>
    invoke("scene_select", { guids, additive }),
  setProperty: (
    guids: string[],
    typePath: string,
    field: string,
    value: PropValueDto,
  ): Promise<DetailsDto> =>
    invoke<DetailsDto>("scene_set_property", { guids, typePath, field, value }),
  resetProperty: (guids: string[], typePath: string, field: string): Promise<DetailsDto> =>
    invoke<DetailsDto>("scene_reset_property", { guids, typePath, field }),
  undo: (): Promise<void> => invoke("scene_undo"),
  redo: (): Promise<void> => invoke("scene_redo"),
  /** Save to `path`, or a default quicksave when omitted. */
  save: (path: string | null = null): Promise<void> => invoke("scene_save", { path }),
  open: (path: string | null = null): Promise<SceneSnapshot> =>
    invoke<SceneSnapshot>("scene_open", { path }),
  newScene: (): Promise<SceneSnapshot> => invoke<SceneSnapshot>("scene_new"),
  /** Write the crash-recovery file if there are unsaved changes. */
  autosave: (): Promise<void> => invoke("scene_autosave"),
  /** Spawn a Content-Drawer asset dropped over the viewport (P4.4). */
  spawnAsset: (assetId: string): Promise<string> =>
    invoke<string>("scene_spawn_asset", { assetId }),
};

/**
 * Asset system / Content Drawer (Phase 4). The asset database lives in the
 * backend under the project content root; the store loads `assets_snapshot`
 * and re-fetches on the `assets://changed` event. Thumbnails are lazy PNG
 * data-URLs. Arg names are camelCase (Tauri maps to snake_case).
 */
export const assets = {
  snapshot: (): Promise<AssetSnapshot> => invoke<AssetSnapshot>("assets_snapshot"),
  /** Assets that reference `id` (Show References / delete warning). */
  references: (id: string): Promise<AssetRefDto[]> =>
    invoke<AssetRefDto[]>("asset_references", { id }),
  /** A PNG data-URL thumbnail, or null for icon-only kinds / no GPU. */
  thumbnail: (id: string): Promise<string | null> =>
    invoke<string | null>("asset_thumbnail", { id }),
  /** Queue external files for import; progress arrives on `assets://import`. */
  import: (sources: string[], destFolder: string | null = null): Promise<number[]> =>
    invoke<number[]>("asset_import", { sources, destFolder }),
  /** Create a new authored asset (Phase 4.4: "material"). Returns the GUID. */
  create: (kind: string, folder: string | null = null, name: string | null = null): Promise<string> =>
    invoke<string>("asset_create", { kind, folder, name }),
  /** Delete; when still referenced (and not forced) returns the blockers. */
  delete: (id: string, force = false): Promise<DeleteResult> =>
    invoke<DeleteResult>("asset_delete", { id, force }),
  rename: (id: string, name: string): Promise<void> => invoke("asset_rename", { id, name }),
  duplicate: (id: string): Promise<string> => invoke<string>("asset_duplicate", { id }),
  setTags: (id: string, tags: string[]): Promise<void> => invoke("asset_set_tags", { id, tags }),
  /** Load a data asset (struct/enum/table) for editing; null if not a data kind. */
  data: (id: string): Promise<DataAssetDto | null> =>
    invoke<DataAssetDto | null>("asset_data", { id }),
  dataSave: (dataAsset: DataAssetDto): Promise<void> =>
    invoke("asset_data_save", { dataAsset }),
  tableImport: (id: string, source: string): Promise<void> =>
    invoke("asset_table_import", { id, source }),
  rustSource: (id: string): Promise<string> => invoke<string>("asset_rust_source", { id }),
};
