/**
 * `file://` URIs from absolute paths — the ONE encoder on this side of the
 * wire.
 *
 * Extracted from `lspBridge.ts` in wave SCRIPT2b, unchanged, because the
 * InfiniScript layer keys the same diagnostics store and importing the LSP
 * bridge to reach one pure function would have made `setup.ts` depend on it —
 * and `lspBridge.ts` already depends on `setup.ts`. A leaf module is cheaper
 * than a cycle. `lspBridge` re-exports it, so the committed fixture test that
 * pins this encoder against the backend's keeps importing it from where it
 * has always been.
 */

/**
 * `file://` URI from an absolute path — the twin of the backend's
 * `path_to_uri`, character for character (round-2 findings R2.F3 / B4).
 *
 * This escaped **only the space**, under a comment claiming it matched the
 * backend, while Wave F gave the Rust side full RFC-3986 percent-encoding. The
 * two then disagreed on `#`, `%`, `?`, `(`, `)`, `'`, `&`, `,`, `+` and every
 * non-ASCII byte. That matters because the URI *is* the document's identity on
 * this wire: `:127` keys the diagnostics store on the URI the backend sends,
 * `:84` and `:130` look it up with this one, and `lspExtension` sends this one
 * to a server that was told the other. On any project under `C:\Users\Müller\`
 * or in a folder called `Game (v2)`, squiggles were never painted, Problems
 * entries never matched a file, and completion got "unknown document" — with
 * nothing anywhere saying why.
 *
 * The agreement is now pinned: `lspUriFixtures.json` is generated by the Rust
 * encoder's own test and asserted here, so neither side can move alone.
 * (Wave C's law — two copies of one expression across a language boundary are a
 * contract nobody is measuring.)
 *
 * Deliberately hand-rolled rather than `encodeURI`: that leaves `#`, `?`, `&`,
 * `+`, `,`, `=`, `;`, `@`, `!`, `$`, `*`, `'`, `(`, `)` unescaped — most of the
 * defect — and `encodeURIComponent` escapes the `/` separators and the Windows
 * drive `:`. The set here is exactly RFC 3986's unreserved plus the two
 * structural characters a file URI needs verbatim.
 */
export function pathToUri(path: string): string {
  const normalized = path.replace(/\\/g, "/");
  let p = "";
  // `TextEncoder` gives the UTF-8 bytes; the RFC escapes non-ASCII byte by
  // byte, which is what the backend's `String::bytes()` loop does.
  for (const b of new TextEncoder().encode(normalized)) {
    const unreserved =
      (b >= 0x30 && b <= 0x39) || // 0-9
      (b >= 0x41 && b <= 0x5a) || // A-Z
      (b >= 0x61 && b <= 0x7a) || // a-z
      b === 0x2d || // -
      b === 0x2e || // .
      b === 0x5f || // _
      b === 0x7e || // ~
      b === 0x2f || // / — the separator
      b === 0x3a; // : — the Windows drive letter's, which file:///C:/… requires
    p += unreserved
      ? String.fromCharCode(b)
      : `%${b.toString(16).toUpperCase().padStart(2, "0")}`;
  }
  return p.startsWith("/") ? `file://${p}` : `file:///${p}`;
}
