/**
 * **The cross-language pin for the LSP URI encoder** (round-2 findings
 * R2.F3 / B4).
 *
 * `lspBridge.pathToUri` is a hand-written mirror of the backend's
 * `path_to_uri`, and the two are *compared for equality* at run time: the
 * diagnostics store is keyed on the URI rust-analyzer publishes and looked up
 * with the URI this side builds. When Wave F gave the Rust side full RFC-3986
 * escaping and left this one at spaces-only, every diagnostic for a path
 * containing `#`, `%`, `(`, `'`, `&` or any non-ASCII character was silently
 * dropped — the exact symptom L7.L3 named, re-opened at the other end.
 *
 * Nothing measured the agreement, so this is the measurement. The fixture is
 * **generated by the Rust test**
 * (`inf-studio`'s `the_typescript_mirror_is_pinned_to_this_encoder`) and
 * committed; that test fails if the Rust encoder moves without re-blessing it,
 * and this one fails if the TypeScript encoder disagrees with what was blessed.
 * Neither side can move alone, which is the whole point.
 */
import { describe, expect, it } from "vitest";

import { uriToPath } from "../fileUri";
import { pathToUri } from "../lspBridge";
import fixtures from "./lspUriFixtures.json";

interface UriCase {
  path: string;
  uri: string;
}

const cases: UriCase[] = fixtures.cases;

describe("pathToUri agrees with the backend, case by case", () => {
  it("has a corpus worth calling one", () => {
    // A fixture that emptied itself would make every assertion below vacuous —
    // the shape this campaign has caught eight times.
    expect(cases.length).toBeGreaterThanOrEqual(15);
    expect(cases.some((c) => /[^\x20-\x7e]/.test(c.path))).toBe(true);
    expect(cases.some((c) => c.path.includes("#"))).toBe(true);
    expect(cases.some((c) => c.path.includes("%"))).toBe(true);
    expect(cases.some((c) => c.path.includes(" "))).toBe(true);
  });

  for (const c of cases) {
    it(`${c.path} → ${c.uri}`, () => {
      expect(pathToUri(c.path)).toBe(c.uri);
    });
  }

  it("emits nothing that is not legal in a URI", () => {
    // The property under the table: whatever the pairs say, the output has to
    // be ASCII with no space and no fragment marker, or the server reads a
    // different document than the one that was opened.
    for (const c of cases) {
      const uri = pathToUri(c.path);
      expect(/^[\x21-\x7e]+$/.test(uri)).toBe(true);
      expect(uri.slice("file://".length)).not.toContain("#");
    }
  });

  /**
   * **The decoder, over the same corpus** (SCRIPT2b audit).
   *
   * `uriToPath` is what turns a Problems row back into a file to open, and it
   * decoded `%20` and nothing else — Wave F's defect, fixed on the encoder and
   * left standing on the decoder one module away. Every row for a path
   * containing `#`, `(`, `&`, `+` or a non-ASCII character pointed at a file
   * that does not exist, so clicking it did nothing, silently. Since SCRIPT2b
   * both producers land in that panel.
   *
   * The pin is the round trip over the fixture the *backend* generated, so the
   * decoder is measured against the same corpus as the encoder rather than
   * against a table someone wrote for it.
   */
  it("decodes back to the path the backend's own fixture names", () => {
    for (const c of cases) {
      // Forward-slashed: that is the form `pathToUri` encodes and the form the
      // file IPC takes on Windows.
      expect(uriToPath(c.uri)).toBe(c.path.replace(/\\/g, "/"));
    }
  });

  it("would have failed against the %20-only decoder it replaced", () => {
    // The falsifier for the half above.
    const old = (uri: string) => {
      let p = uri.replace(/^file:\/\//, "").replace(/%20/g, " ");
      if (/^\/[A-Za-z]:/.test(p)) p = p.slice(1);
      return p;
    };
    const wrong = cases.filter((c) => old(c.uri) !== c.path.replace(/\\/g, "/"));
    expect(wrong.length).toBeGreaterThanOrEqual(cases.length / 2);
  });

  it("shows a URI it cannot decode rather than throwing while rendering", () => {
    // A row is a React render; an exception here takes the panel down.
    expect(() => uriToPath("file:///C:/a%ZZb/c.rs")).not.toThrow();
    expect(uriToPath("file:///C:/a%ZZb/c.rs")).toBe("C:/a%ZZb/c.rs");
  });

  it("would have failed against the spaces-only encoder it replaced", () => {
    // The falsifier. A pin whose fixture the OLD implementation also satisfies
    // is a pin about nothing, so the retired encoder is kept here and shown to
    // disagree — on more than half the corpus.
    const old = (path: string) => {
      const p = path.replace(/\\/g, "/").replace(/ /g, "%20");
      return p.startsWith("/") ? `file://${p}` : `file:///${p}`;
    };
    const disagreements = cases.filter((c) => old(c.path) !== c.uri);
    expect(disagreements.length).toBeGreaterThanOrEqual(cases.length / 2);
  });
});
