/**
 * **The cross-language pin for the LSP URI encoder** (round-2 findings
 * R2.F3 / B4).
 *
 * `lspBridge.pathToUri` is a hand-written mirror of the backend's
 * `path_to_uri`, and the two are *compared for equality* at run time: the
 * diagnostics store is keyed on the URI rust-analyzer publishes and looked up
 * with the URI this side builds. When Wave F gave the Rust side full RFC-3986
 * escaping and left this one at spaces-only, every diagnostic for a path
 * containing `#`, `%`, `(`, `'`, `&` or any non-ASCII character was silently
 * dropped — the exact symptom L7.L3 named, re-opened at the other end.
 *
 * Nothing measured the agreement, so this is the measurement. The fixture is
 * **generated by the Rust test**
 * (`inf-studio`'s `the_typescript_mirror_is_pinned_to_this_encoder`) and
 * committed; that test fails if the Rust encoder moves without re-blessing it,
 * and this one fails if the TypeScript encoder disagrees with what was blessed.
 * Neither side can move alone, which is the whole point.
 */
import { describe, expect, it } from "vitest";

import { pathToUri } from "../lspBridge";
import fixtures from "./lspUriFixtures.json";

interface UriCase {
  path: string;
  uri: string;
}

const cases: UriCase[] = fixtures.cases;

describe("pathToUri agrees with the backend, case by case", () => {
  it("has a corpus worth calling one", () => {
    // A fixture that emptied itself would make every assertion below vacuous —
    // the shape this campaign has caught eight times.
    expect(cases.length).toBeGreaterThanOrEqual(15);
    expect(cases.some((c) => /[^\x20-\x7e]/.test(c.path))).toBe(true);
    expect(cases.some((c) => c.path.includes("#"))).toBe(true);
    expect(cases.some((c) => c.path.includes("%"))).toBe(true);
    expect(cases.some((c) => c.path.includes(" "))).toBe(true);
  });

  for (const c of cases) {
    it(`${c.path} → ${c.uri}`, () => {
      expect(pathToUri(c.path)).toBe(c.uri);
    });
  }

  it("emits nothing that is not legal in a URI", () => {
    // The property under the table: whatever the pairs say, the output has to
    // be ASCII with no space and no fragment marker, or the server reads a
    // different document than the one that was opened.
    for (const c of cases) {
      const uri = pathToUri(c.path);
      expect(/^[\x21-\x7e]+$/.test(uri)).toBe(true);
      expect(uri.slice("file://".length)).not.toContain("#");
    }
  });

  it("would have failed against the spaces-only encoder it replaced", () => {
    // The falsifier. A pin whose fixture the OLD implementation also satisfies
    // is a pin about nothing, so the retired encoder is kept here and shown to
    // disagree — on more than half the corpus.
    const old = (path: string) => {
      const p = path.replace(/\\/g, "/").replace(/ /g, "%20");
      return p.startsWith("/") ? `file://${p}` : `file:///${p}`;
    };
    const disagreements = cases.filter((c) => old(c.path) !== c.uri);
    expect(disagreements.length).toBeGreaterThanOrEqual(cases.length / 2);
  });
});
