// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry in the "+ Add Component" menu (E-P1).
 */
export type AddableComponentDto = { 
/**
 * Stable reflect type path — the key passed to `scene_add_component`.
 */
type_path: string, 
/**
 * Human-readable menu label.
 */
display: string, };
