// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A folder in the content tree (`assets_snapshot`).
 */
export type AssetFolderDto = { 
/**
 * Path relative to the content root ("" = root).
 */
path: string, 
/**
 * Leaf folder name ("" for the root).
 */
name: string, 
/**
 * Child folder paths.
 */
children: Array<string>, 
/**
 * Assets directly in this folder.
 */
asset_count: number, };
