// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A lightweight reference to another asset (delete-warning referrer list).
 */
export type AssetRefDto = { id: string, name: string, kind: string, };
