// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The `assets://changed` event payload — a version bump prompting a re-fetch.
 */
export type AssetChanged = { version: number, };
