// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetDto } from "./AssetDto";
import type { AssetFolderDto } from "./AssetFolderDto";

/**
 * The full content snapshot (`assets_snapshot` command).
 */
export type AssetSnapshot = { 
/**
 * Monotonic version (bumped on every content change).
 */
version: number, 
/**
 * Absolute content-root path, for display.
 */
root: string, assets: Array<AssetDto>, folders: Array<AssetFolderDto>, };
