// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One asset row in the Content Drawer grid.
 */
export type AssetDto = { 
/**
 * Stable GUID string.
 */
id: string, name: string, 
/**
 * Kind slug ("mesh", "texture", …) for filtering/icons.
 */
kind: string, 
/**
 * Kind display label ("Static Mesh", …).
 */
kind_label: string, 
/**
 * Folder path relative to the content root ("", "meshes", "props/env").
 */
folder: string, 
/**
 * Payload path relative to the content root (forward slashes).
 */
path: string, 
/**
 * xxh3 content hash hex (the thumbnail + change key).
 */
content_hash: string, 
/**
 * User tags.
 */
tags: Array<string>, 
/**
 * Import source (relative), if imported.
 */
source: string | null, 
/**
 * Number of assets this one references (outgoing deps).
 */
dep_count: number, 
/**
 * Number of assets that reference this one (for the delete warning badge).
 */
ref_count: number, 
/**
 * Whether this kind has a rendered thumbnail (else the UI shows an icon).
 */
previewable: boolean, };
