// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BiomeDefDto } from "./BiomeDefDto";

/**
 * A `.inf_biomes` asset as the inline editor sees it (`asset_get_biome_set` /
 * `asset_save_biome_set`).
 */
export type BiomeSetDto = { 
/**
 * The asset GUID.
 */
id: string, 
/**
 * Display name of the set.
 */
name: string, biomes: Array<BiomeDefDto>, };
