// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One biome definition inside a [`BiomeSetDto`].
 *
 * `color` is **linear** RGBA (it is uploaded straight into the overlay palette).
 * `pcg_graph` is a GUID string (the P19.3 hook); `water_hint` is a still-water
 * level in **metres** of absolute world height; `structure_hint` names a
 * building palette (P19.5). Both hints are plain advisory data in P19.2.
 */
export type BiomeDefDto = { 
/**
 * Stable id `1..=255`. `0` is reserved for *unassigned* and cannot be
 * defined — the backend rejects a set that tries.
 */
id: number, name: string, color: [number, number, number, number], 
/**
 * Which of the terrain's four splat layers this biome shades as, if any.
 */
splat_layer: number | null, pcg_graph: string | null, water_hint: number | null, structure_hint: string | null, };
