// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * [`inf_anim::BodyParams`] on the wire. Every length is **metres** and every
 * ratio is a fraction of `height_m` (SI, units doctrine); nothing here is
 * degrees.
 */
export type BodyParamsDto = { heightM: number, hipHeightRatio: number, shoulderHeightRatio: number, headHeightRatio: number, spineSegments: number, neckSegments: number, shoulderWidthM: number, hipWidthM: number, upperLimbRatio: number, armLengthRatio: number, 
/**
 * Multi-girdle plans only; a biped's torso is vertical.
 */
bodyLengthM: number, 
/**
 * Multi-girdle plans only.
 */
headForwardM: number, };
