// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CaptureCameraDto } from "./CaptureCameraDto";

/**
 * The knobs the capture wizard exposes.
 *
 * A **subset** of `CaptureConfig`, deliberately: the sparse and dense solvers'
 * constants are committed numbers whose defaults every measurement in Phase 25
 * was taken at, and a dialog that let them be typed would make every one of
 * those numbers a claim about somebody's session.
 */
export type CaptureSettingsDto = { camera: CaptureCameraDto, 
/**
 * **The scale step.** Metres per reconstruction unit; `1.0` leaves the
 * result in the reconstruction's own baseline units.
 */
metresPerUnit: number, 
/**
 * Triangle budget for the retopologized mesh.
 */
targetTriangles: number, 
/**
 * Atlas side, in texels.
 */
atlasSize: number, 
/**
 * Ambient-occlusion rays per texel.
 */
aoRays: number, 
/**
 * Drop geometry no camera photographed.
 */
trimUnseen: boolean, 
/**
 * Attempt de-lighting (it refuses on its own when the fit is not
 * believable).
 */
delight: boolean, 
/**
 * Roughness written into the material and the ORM map.
 */
roughness: number, 
/**
 * Metallic, likewise.
 */
metallic: number, };
