// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One `photogrammetry://progress` event.
 */
export type CaptureProgressDto = { run: number, 
/**
 * `"load" | "sfm" | "dense" | "finish" | "write"`.
 */
stage: string, 
/**
 * Its position in the pipeline, so a bar can show overall progress without
 * a second copy of the stage order.
 */
stageIndex: number, 
/**
 * How many stages there are.
 */
stages: number, 
/**
 * `"started" | "progress" | "finished" | "failed" | "cancelled"`.
 */
phase: string, done: number, total: number, detail: string, error: string | null, };
