// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One finding, with the severity and stage that decide where it is shown.
 */
export type CaptureIssueDto = { 
/**
 * `"blocking" | "warning" | "note"`.
 */
severity: string, 
/**
 * `"load" | "sfm" | "dense" | "finish" | "write"`.
 */
stage: string, 
/**
 * The sentence, carrying its own remedy.
 */
message: string, };
