// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What an import wrote.
 */
export type CaptureImportDto = { mesh: string, albedo: string, normal: string, orm: string, material: string, 
/**
 * The content sub-folder they landed in.
 */
folder: string, 
/**
 * The asset name they were written under.
 */
name: string, 
/**
 * Things a caller needs to know now that the scan is on disk — the
 * placeholder-cube note among them.
 */
notes: Array<string>, };
