// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoverageDto } from "./CoverageDto";

/**
 * The numbers a finished run produced.
 */
export type CaptureResultDto = { registered: number, views: number, points: number, reprojectionRmsPx: number, denseTriangles: number, voxelSize: number, triangles: number, vertices: number, charts: number, atlasCoverage: number, 
/**
 * The longest side in **baseline units** — what a known real-world length
 * is divided by to get [`CaptureSettingsDto::metres_per_unit`]. It does
 * **not** move when the scale does, so a second correction is computed
 * against the same number as the first.
 */
extentUnits: number, 
/**
 * The same side at the scale the run used, in metres.
 */
extentMetres: number, coverage: CoverageDto, 
/**
 * Wall clock per stage, in `load, sfm, dense, finish, write` order.
 */
elapsedMs: number[], };
