// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The preview, as data-URL PNGs.
 *
 * Two images because the offscreen path draws **geometry**: binding a real
 * base-colour texture in the preview session is the standing P7 follow-up, so
 * the atlas is shown beside the render through the CPU texture door the Content
 * Drawer already uses. Either may be absent — the geometry needs a GPU adapter
 * and the atlas does not.
 */
export type CapturePreviewDto = { 
/**
 * The shaded mesh, rendered offscreen.
 */
geometry: string | null, 
/**
 * The baked base-colour atlas, decoded on the CPU.
 */
albedo: string | null, 
/**
 * Why the geometry preview is absent.
 */
error: string | null, size: number, };
