// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CaptureIssueDto } from "./CaptureIssueDto";
import type { CaptureResultDto } from "./CaptureResultDto";
import type { CaptureSettingsDto } from "./CaptureSettingsDto";
import type { PhotoEntryDto } from "./PhotoEntryDto";

/**
 * Everything the capture panel renders.
 */
export type CaptureStatusDto = { 
/**
 * `"idle" | "running" | "ready" | "imported" | "failed" | "cancelled"`.
 */
state: string, 
/**
 * The stage in flight, when one is.
 */
stage: string | null, 
/**
 * The run these events belong to.
 */
run: number, photos: Array<PhotoEntryDto>, settings: CaptureSettingsDto, 
/**
 * The pre-flight before a run, the product's findings after one.
 */
issues: Array<CaptureIssueDto>, result: CaptureResultDto | null, 
/**
 * The refusal that ended a run.
 */
error: string | null, 
/**
 * Where an import will write, relative to the content root.
 */
folder: string, };
