// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CharacterJointDto } from "./CharacterJointDto";
import type { CharacterLegDto } from "./CharacterLegDto";

/**
 * What a spec *would* produce — recomputed on every slider drag, with nothing
 * written.
 */
export type CharacterRigDto = { joints: Array<CharacterJointDto>, sockets: Array<string>, 
/**
 * Joints carrying a rotation limit — the IK input the template emits.
 */
limits: number, 
/**
 * The span between the rig's lowest and highest **joint** in the bind pose
 * (metres). **Not** the requested height and not the creature's: a template
 * rig's topmost joint is `head`, at `head_height_ratio × height_m`, so a
 * 1.75 m biped reads 1.6275. A fitted rig takes the mesh's, which is what
 * makes this the fit's readout. The panel labels it "Joint span" for that
 * reason.
 */
heightM: number, legs: Array<CharacterLegDto>, 
/**
 * idle / walk / run cycle lengths, seconds.
 */
durationsS: [number, number, number], walkSpeedMS: number, runSpeedMS: number, walkThresholdMS: number, runThresholdMS: number, 
/**
 * Mannequin vertex + triangle count, absent when the spec brings its own
 * mesh.
 */
bodyVertices: number | null, bodyTriangles: number | null, };
