// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CharacterJointDto } from "./CharacterJointDto";
import type { CharacterLegDto } from "./CharacterLegDto";

/**
 * What a spec *would* produce — recomputed on every slider drag, with nothing
 * written.
 */
export type CharacterRigDto = { joints: Array<CharacterJointDto>, sockets: Array<string>, 
/**
 * Joints carrying a rotation limit — the IK input the template emits.
 */
limits: number, 
/**
 * The rig's real bind-pose extent along Y (metres). **Not** the requested
 * height: a fitted rig takes the mesh's, and reading it back is how an
 * author sees the fit worked.
 */
heightM: number, legs: Array<CharacterLegDto>, 
/**
 * idle / walk / run cycle lengths, seconds.
 */
durationsS: [number, number, number], walkSpeedMS: number, runSpeedMS: number, walkThresholdMS: number, runThresholdMS: number, 
/**
 * Mannequin vertex + triangle count, absent when the spec brings its own
 * mesh.
 */
bodyVertices: number | null, bodyTriangles: number | null, };
