// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BodyParamsDto } from "./BodyParamsDto";
import type { GaitParamsDto } from "./GaitParamsDto";

/**
 * Everything the wizard collects, in one message — so a preview and a create
 * are the *same* input and a preview cannot describe a character the create
 * would not make.
 */
export type CharacterSpecDto = { name: string, 
/**
 * `"biped"` | `"biped-canonical"` | `"quadruped"` | `"hexapod"` |
 * `"npedal"`. A **string** for `skel_create_template`'s stated reason: the
 * plan set is the part of this API most likely to grow, and a name that
 * fails loudly with the list of what it does know is kinder to a stale
 * frontend than a generated union that silently loses a variant. (SK1a
 * widened the set and this list did not follow, which is the doc making
 * exactly the mistake it argues against.)
 */
plan: string, 
/**
 * Leg count for `"npedal"`; ignored by the named plans.
 */
legs: number | null, params: BodyParamsDto, gait: GaitParamsDto, 
/**
 * An existing `.inf_mesh` GUID to fit the rig to and skin. Absent → the
 * wizard generates a blocky mannequin from the rig.
 */
meshAsset: string | null, };
