// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One driven leg and where it falls in the gait cycle.
 */
export type CharacterLegDto = { name: string, lengthM: number, 
/**
 * Position in the cycle, `[0, 1)`.
 */
phase: number, };
