// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One joint of the previewed rig — the three numbers the Skeleton Editor's SVG
 * diagram projects from, so the wizard and the editor draw the same picture.
 */
export type CharacterJointDto = { name: string, parent: number | null, 
/**
 * Local rest translation, metres.
 */
translation: [number, number, number], };
