// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One named collection (`collections_list`).
 */
export type CollectionDto = { name: string, 
/**
 * Member asset GUID strings, in insertion order (dangling ids pruned).
 */
ids: Array<string>, };
