// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One named collision layer (`collision_layers_get` / `collision_layers_set`).
 * `bit` is the layer index in `0..32`; the `Collider*` masks store `1 << bit`.
 */
export type CollisionLayerDto = { bit: number, name: string, };
