// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PropFieldDto } from "./PropFieldDto";

/**
 * One component section in the Details grid.
 */
export type ComponentDto = { type_path: string, display: string, fields: Array<PropFieldDto>, };
