// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What one camera saw of the finished mesh — a row of the coverage overlay.
 */
export type CoverageViewDto = { view: number, photo: string, 
/**
 * Whether it got a pose at all.
 */
registered: boolean, trianglesSeen: number, 
/**
 * That, over the finished triangle count.
 */
fraction: number, };
