// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of a data-map export (`terrain_export_data_map`, P19.1).
 *
 * The written file is a **16-bit grayscale PNG** normalized over `[min, max]` —
 * the range the terrain's raw accumulators actually span, reported here so the
 * mapping is stated rather than implied. The stored data is never normalized;
 * only this view is.
 */
export type DataMapExportDto = { 
/**
 * Which map was exported (`"flow"` / `"deposition"` / `"wear"`).
 */
map: string, 
/**
 * Absolute path of the PNG written.
 */
path: string, width: number, height: number, 
/**
 * Bytes written.
 */
bytes: number, 
/**
 * Low end of the exported range (black), in the map's own SI unit.
 */
min: number, 
/**
 * High end of the exported range (white), in the map's own SI unit.
 */
max: number, 
/**
 * SI unit of the accumulator (`"m^3"` for flow, `"m"` for the others).
 */
unit: string, };
