// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One struct field / table column, flattened for the editor. `ty` is a slug
 * ("bool"/"int"/"float"/"text"/"vec3"/"color"/"asset_ref"/"enum"); an enum
 * field also carries the referenced `.inf_enum` GUID + name.
 */
export type DataFieldDto = { name: string, type: string, enum_id: string | null, enum_name: string | null, };
