// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DccDocDto } from "./DccDocDto";

/**
 * The result of a tool press: what it did, or why it refused.
 */
export type DccApplyDto = { ok: boolean, 
/**
 * The kernel's typed refusal, rendered for a human. Empty when `ok`.
 */
refusal: string | null, doc: DccDocDto, };
