// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How much of a surface the lossy non-manifold repair detached, banded.
 *
 * A wire mirror of `inf_dcc::DetachSeverity`. The **bands** cross the wire, not
 * the ratio, so the thresholds stay in the kernel where the repair is — a
 * duplicated threshold in TypeScript is the GpuLight triplication law waiting to
 * happen. `detach_severity_is_the_kernels_bands` in the DCC command module pins
 * the two enums against each other.
 */
export type DccDetachSeverityDto = "none" | "isolated" | "substantial" | "pervasive";
