// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DccGizmoModeDto } from "./DccGizmoModeDto";
import type { DccImportDto } from "./DccImportDto";
import type { DccModeDto } from "./DccModeDto";
import type { DccOrientDto } from "./DccOrientDto";
import type { DccPivotDto } from "./DccPivotDto";

/**
 * One open Model Editor document.
 */
export type DccDocDto = { 
/**
 * `"dcc:<assetId>"` — one document per mesh asset.
 */
id: string, assetId: string, name: string, mode: DccModeDto, verts: number, edges: number, faces: number, 
/**
 * How many components are selected **in the current mode**.
 */
selected: number, canUndo: boolean, canRedo: boolean, 
/**
 * Unsaved edits since the last `dcc_save` (or since open).
 */
dirty: boolean, 
/**
 * The journal generation. The frontend does not interpret it; it is the
 * preview's cache key and the reason a stale image is impossible.
 */
generation: number, import: DccImportDto, 
/**
 * How many waypoints the knife has collected (see `dcc_pick`).
 */
knifePoints: number, 
/**
 * A pointer drag is in flight (P23.5). The panel reads it to keep sending
 * moves and to know that a `dcc_drag_end` is owed — but the **backend** is
 * what settles an orphaned one, because a panel that has already unmounted
 * cannot.
 */
dragging: boolean, 
/**
 * How many raw path points the stroke in flight has collected. `0` for a
 * gizmo drag or no drag. Surfaced so "is this doing anything" is answerable
 * from the status bar.
 */
dragPoints: number, 
/**
 * Which transform gizmo is armed, if any. Backend state, like the camera
 * and the selection, because the handles are drawn and picked backend-side
 * and a panel-held copy would be a second opinion about the active tool.
 */
gizmo: DccGizmoModeDto | null, 
/**
 * **A content revision of the selection** — what a view keys on to know its
 * picture is stale.
 *
 * Not the journal `generation` (a selection change does not move it) and not
 * `selected` (a count: face A and face B both read `1`). Neither of those can
 * tell two different one-face selections apart, and the UV pane keyed on the
 * first of them and therefore never refreshed on a pick.
 */
selectionRev: number, 
/**
 * Undirected edges marked as UV seams (P23.5).
 */
seams: number, 
/**
 * How many charts the seams cut the mesh into — the number an author checks
 * **before** unwrapping, because it is the thing their seam marks control.
 */
charts: number, 
/**
 * How many joints this mesh's skin channel is bound to, or `None` when it
 * carries no skin (P24.2).
 *
 * The weight brush's **bound**, and the reason the influence picker is a
 * number box rather than a list: a `.inf_mesh` records no skeleton (the
 * pairing lives in the scene's `SkeletalMesh`), so the kernel knows how many
 * joints its indices address and not what any of them is called. Names
 * arrive with P24.3's skeleton binding UI.
 */
skinJoints: number | null, 
/**
 * The mesh's material slot table, in slot order.
 *
 * `Op::AddMaterialSlots` and `Op::SetFaceSlot` have existed since P24.3 with
 * **no UI caller at all** — the only consumer was `merge_into` — so a
 * multi-material prop could not be authored in this editor. This is the
 * field that makes the table visible; `DccToolDto::AssignSlot` is what
 * writes to it.
 */
materialSlots: Array<string>, 
/**
 * Where the transform gizmo sits. Hard-wired to the centroid until Wave D.
 */
pivot: DccPivotDto, 
/**
 * Which way its axes point. `Quat::IDENTITY` at two sites until Wave D.
 */
orient: DccOrientDto, 
/**
 * Whether a marquee catches what it cannot see.
 */
xray: boolean, 
/**
 * **The live readout of the drag in flight** — "0.42 m along X",
 * "37.5°", "×1.25" — or `None` when nothing is being dragged.
 *
 * The P23 carried remainder was "no rotate-gizmo angle readout"; all three
 * modes had the same nothing, so all three have this.
 */
readout: string | null, };
