// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DccImportDto } from "./DccImportDto";
import type { DccModeDto } from "./DccModeDto";

/**
 * One open Model Editor document.
 */
export type DccDocDto = { 
/**
 * `"dcc:<assetId>"` — one document per mesh asset.
 */
id: string, assetId: string, name: string, mode: DccModeDto, verts: number, edges: number, faces: number, 
/**
 * How many components are selected **in the current mode**.
 */
selected: number, canUndo: boolean, canRedo: boolean, 
/**
 * Unsaved edits since the last `dcc_save` (or since open).
 */
dirty: boolean, 
/**
 * The journal generation. The frontend does not interpret it; it is the
 * preview's cache key and the reason a stale image is impossible.
 */
generation: number, import: DccImportDto, 
/**
 * How many waypoints the knife has collected (see `dcc_pick`).
 */
knifePoints: number, };
