// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DccDocDto } from "./DccDocDto";

/**
 * The result of starting a drag: whether the pointer actually grabbed anything.
 *
 * Distinguished from [`DccApplyDto`] because "the pointer missed the model" is
 * not a refusal to report in the status bar — it is the panel's cue to orbit the
 * camera instead, which is the behaviour that makes a sculpt tool usable without
 * a modifier key.
 */
export type DccDragBeginDto = { 
/**
 * `true` when a drag is now in flight. `false` means the pointer hit
 * nothing, nothing is pending, and the panel should treat the gesture as a
 * camera orbit.
 */
grabbed: boolean, 
/**
 * Which gizmo handle was grabbed, for the panel's cursor. `None` for a
 * sculpt stroke or a miss.
 */
handle: string | null, 
/**
 * Why the drag was **refused**, as opposed to having missed. A miss is silent
 * — it becomes a camera orbit — but a refusal is a sentence, because an
 * author whose brush did nothing needs to know it was the radius.
 */
refusal: string | null, doc: DccDocDto, };
