// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the writer had to do on the way out — the two unroundtrippable counters
 * plus the shape of what was written.
 */
export type DccExportDto = { submeshes: number, vertices: number, triangles: number, fanFallbacks: number, fallbackTangents: number, 
/**
 * Kernel vertices that share a position with another. **Non-zero means the
 * next open will not be this mesh**: the reader's exact weld fuses them.
 */
coincidentVertices: number, 
/**
 * Triangulation diagonals that had to repeat an existing edge. The other way
 * a written asset comes back unreadable.
 */
reusedDiagonals: number, nonFiniteWritten: number, nonUnitNormalsWritten: number, };
