// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * **The Cloth section's knobs** (P24.4) — what the panel sends to
 * `dcc_make_garment`.
 *
 * Compliance is m/N and not a 0..1 "stiffness", because XPBD compliance is
 * timestep-independent and this engine compares traces across hosts that may
 * tick at different rates (see `inf_anim::ClothMaterial`). Everything else is
 * metres, `1/s` or a count. The *operand* — which vertices are pinned — is the
 * document's own selection, resolved backend-side, exactly like a tool press.
 */
export type DccGarmentDto = { 
/**
 * Stretch compliance, m/N. `0` is inextensible.
 */
stretchCompliance: number, 
/**
 * Bend compliance, m/N. Two orders above the stretch one is a skirt.
 */
bendCompliance: number, 
/**
 * Velocity damping, 1/s.
 */
damping: number, 
/**
 * Collision thickness, metres.
 */
thicknessM: number, 
/**
 * Substeps per fixed step (`0` reads as `1`).
 */
substeps: number, 
/**
 * Constraint sweeps per substep (`0` reads as `1`).
 */
iterations: number, 
/**
 * Uniform body-capsule radius, metres. `0` derives none.
 */
bodyRadiusM: number, 
/**
 * The `.inf_skel` whose bones become the collision capsules, or `None` for a
 * garment that collides against nothing.
 */
skeleton: string | null, 
/**
 * Asset name for the new `.inf_cloth`.
 */
name: string | null, };
