// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which transform the component gizmo is showing.
 */
export type DccGizmoModeDto = "translate" | "rotate" | "scale";
