// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DccDetachSeverityDto } from "./DccDetachSeverityDto";

/**
 * What the kernel's reader had to do to open this asset — surfaced, not hidden.
 *
 * `boundaryEdges` is the one the panel puts a verdict on: a solid the author
 * believes is closed arriving with boundary edges is *fragmented*, and the exact
 * weld (tolerance zero, and it stays zero) is why. Telling them beats picking an
 * epsilon on their behalf.
 */
export type DccImportDto = { sourceVertices: number, weldedPositions: number, fanSplits: number, 
/**
 * **Faces dropped as exact duplicates** of an earlier one (Wave D).
 */
duplicateFacesDropped: number, 
/**
 * **Faces whose winding was flipped** to agree with their neighbours
 * (Wave D). The LOSSLESS half of the non-manifold repair: the surface is
 * identical, only its orientation is now consistent.
 */
facesReoriented: number, 
/**
 * **Faces detached because they still shared a directed edge** (Wave D).
 * The LOSSY half, counted apart from the lossless one on purpose: non-zero
 * means the source described something that is not a manifold surface — an
 * interior partition, a double-sided sheet — and this is how much of it
 * came in as a separate shell.
 */
nonManifoldSplits: number, 
/**
 * **How bad that detach was, as a share of the surface** — the severity the
 * count above cannot express (the Wave-D audit's re-carry). Two faces out of
 * 200 000 and two out of six are the same number and different meshes; the
 * panel's verdict reads this, not `nonManifoldSplits === 0`. Banded in the
 * kernel (`inf_dcc::DetachSeverity`) so the thresholds live in one place.
 */
detachSeverity: DccDetachSeverityDto, degenerateTrianglesSkipped: number, sharpEdges: number, boundaryEdges: number, nonFiniteValues: number, 
/**
 * **Welded positions where two source vertices disagreed about their
 * skinning influences** (P24.2). Normally zero — a well-formed exporter
 * gives every split copy of a vertex the same weights — and a non-zero
 * reading is also the exact number that makes the export round trip
 * inexact, because first-occurrence wins.
 */
skinConflicts: number, };
