// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which component kind the Model Editor is selecting in.
 *
 * A mirror of `inf_dcc::SelectMode` rather than a re-export, for the reason
 * every DTO in this file is: the wire shape is the editor's contract and the
 * kernel's enum is the kernel's, and tying them together means a kernel rename
 * silently changes an IPC payload.
 */
export type DccModeDto = "vert" | "edge" | "face";
