// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * **Which way the gizmo's axes point** — the second hard-wired constant
 * (`Quat::IDENTITY`, at two sites).
 */
export type DccOrientDto = "global" | "normal" | "view";
