// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The pivot a gizmo sits on: the **centroid of the selected vertices**.
 *
 * Not the bounding-box centre: a centroid is what the transform ops are
 * pivot-relative to, and a box centre would put the visible handle somewhere the
 * rotation is not actually about on any asymmetric selection.
 * **Where the gizmo sits** — the first of the two constants P23.5 hard-wired.
 *
 * Blender offers five; four of them are a statement about the selection and one
 * (*individual origins*) is a statement about the **op**, because it means "run
 * this transform once per element about its own centre". `transform_ops`
 * produces one op for one transform, so individual origins is a different shape
 * and is a named remainder rather than a fifth variant nobody can honour.
 */
export type DccPivotDto = "median" | "boundingBox" | "worldOrigin" | "activeElement";
