// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a **weight** dab does to the influence under it (P24.2). A mirror of
 * `inf_dcc::PaintMode`, for the reason [`DccSculptModeDto`] is a mirror of
 * `SculptMode`.
 */
export type DccPaintModeDto = "add" | "subtract" | "replace" | "smooth";
