// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which primitive a new mesh starts as.
 *
 * The four the kernel has had since P23.3 and Ring 2 has never had a door for.
 * **Wave E's own remainder was blunter than that**: *"there is no way to start
 * a new model at all"* — the Model Editor could open an imported mesh and
 * nothing else, which made an engine with a modelling kernel a tool for editing
 * other people's geometry.
 */
export type DccPrimitiveDto = "cube" | "plane" | "cylinder" | "torus";
