// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a brush dab does. A mirror of `inf_dcc::SculptMode`, for the reason
 * [`DccModeDto`] is a mirror of `SelectMode`.
 */
export type DccSculptModeDto = "draw" | "smooth" | "flatten" | "grab";
