// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DccModeDto } from "./DccModeDto";

/**
 * A selection command.
 */
export type DccSelectDto = { "action": "mode", mode: DccModeDto, } | { "action": "all" } | { "action": "none" } | { "action": "invert" } | { "action": "grow" } | { "action": "shrink" } | { "action": "linked" } | { "action": "loop" } | { "action": "ring" };
