// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SculptFalloffDto } from "./SculptFalloffDto";

/**
 * A modelling tool press. Parameters arrive from the toolbar popovers; the
 * *operands* are the document's current selection, resolved backend-side.
 */
export type DccToolDto = { "tool": "extrude", distance: number, } | { "tool": "extrudeEdges", delta: [number, number, number], } | { "tool": "inset", amount: number, individual: boolean, } | { "tool": "bevel", amount: number, } | { "tool": "loopCut", cuts: number, } | { "tool": "knife" } | { "tool": "merge", center: boolean, } | { "tool": "subdivide" } | { "tool": "mirror", axis: string, coord: number, } | { "tool": "translate", delta: [number, number, number], } | { "tool": "softTranslate", delta: [number, number, number], radius: number, falloff: SculptFalloffDto, } | { "tool": "delete" };
