// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DccDocDto } from "./DccDocDto";

/**
 * The verdict on an unwrap — the P20.4 readout pattern, and the place the
 * solver's **residual** is reported rather than hidden.
 *
 * `worstResidual` is `‖Ax − b‖ / ‖b‖` for the worst chart after the fixed
 * iteration count. A fixed-count solver either converged or it did not, and the
 * only honest interface is to say which: a big number means a distorted chart,
 * not a failure, and the author can act on it (add a seam) in a way that "unwrap
 * complete" would never have prompted.
 */
export type DccUnwrapDto = { ok: boolean, 
/**
 * The kernel's typed refusal, rendered for a human. Empty when `ok`.
 */
refusal: string | null, charts: number, corners: number, seams: number, 
/**
 * **How much the worst chart has to stretch** — a property of the geometry.
 * Non-zero for a shape that is not developable, however well the solve went.
 */
worstResidual: number, 
/**
 * **Whether the solver finished** — a property of the solve, zero iff CG
 * converged. Split from `worstResidual` because one number gave the same
 * reading, and therefore the same advice, to opposite causes: a *failed* flat
 * plane read 5.7e-2 and a *converged* saddle read 4.1e-2.
 */
worstConvergence: number, 
/**
 * Triangles whose UV winding opposes their chart's majority — **folds**. A
 * converged, low-distortion unwrap can still overlap itself when a chart is
 * not a disk, and this is the only number that sees it.
 */
flipped: number, 
/**
 * Triangles across all charts, so `flipped` has a denominator.
 */
triangles: number, doc: DccDocDto, };
