// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DccDocDto } from "./DccDocDto";

/**
 * The verdict on an unwrap — the P20.4 readout pattern, and the place the
 * solver's **residual** is reported rather than hidden.
 *
 * `worstResidual` is `‖Ax − b‖ / ‖b‖` for the worst chart after the fixed
 * iteration count. A fixed-count solver either converged or it did not, and the
 * only honest interface is to say which: a big number means a distorted chart,
 * not a failure, and the author can act on it (add a seam) in a way that "unwrap
 * complete" would never have prompted.
 */
export type DccUnwrapDto = { ok: boolean, 
/**
 * The kernel's typed refusal, rendered for a human. Empty when `ok`.
 */
refusal: string | null, charts: number, corners: number, seams: number, 
/**
 * The worst per-chart relative residual after the fixed CG iteration count.
 */
worstResidual: number, doc: DccDocDto, };
