// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetRefDto } from "./AssetRefDto";

/**
 * The result of a delete request (`asset_delete`): either it happened, or it
 * was blocked by the assets still referencing the target.
 */
export type DeleteResult = { deleted: boolean, 
/**
 * Non-empty only when `deleted` is false — the referrers to warn about.
 */
blockers: Array<AssetRefDto>, };
