// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentDto } from "./ComponentDto";

/**
 * The Details panel view of the current selection.
 */
export type DetailsDto = { selection: Array<string>, 
/**
 * Header label (the object name, or "N selected").
 */
name: string, 
/**
 * Header type (single selection only).
 */
kind: string, 
/**
 * Component sections shared by every selected object.
 */
components: Array<ComponentDto>, multi: boolean, };
