// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FoliageSettingsDto } from "./FoliageSettingsDto";
import type { Snap3DDto } from "./Snap3DDto";

/**
 * Application-level (per-user) editor settings.
 *
 * This type is **also the wire type**: `ipc.rs` re-exports it and the ts-rs
 * harness roots it, so there is exactly one definition and a Dto mirror cannot
 * drift out of step with the file format.
 *
 * Field order is load-bearing for TOML: every scalar comes before every table,
 * because `toml` refuses to emit a value after a table.
 */
export type EditorSettings = { 
/**
 * On-disk schema version. Stamped by [`Self::normalize`]; a file written by
 * a NEWER editor is refused rather than downgraded.
 */
schema_version: number, 
/**
 * Selected theme id (`lib/theme.ts`). Unknown ids fall back in the shell.
 */
theme_id: string, 
/**
 * Whether the first-run tour has been seen/dismissed.
 */
tour_seen: boolean, 
/**
 * Crash-recovery autosave period, seconds.
 */
autosave_interval_s: number, 
/**
 * Editor flycam speed at session start, m/s (the wheel still scales it).
 */
camera_fly_speed_mps: number, 
/**
 * Mouse-look sensitivity multiplier (1.0 = the shipped feel).
 */
camera_look_sensitivity: number, 
/**
 * A right-button gesture that travels less than this (physical px) **and**
 * lasts less than [`Self::rmb_click_ms`] is a click (context menu); longer
 * or further is a flycam drag.
 */
rmb_click_travel_px: number, 
/**
 * The time half of the same discrimination, milliseconds.
 */
rmb_click_ms: number, 
/**
 * **The GIS vector-import entity cap** (IB-14), remembered per user.
 *
 * The certification's complaint about this number was that it was
 * "reported and never silent, which is the right design — but with no
 * wizard there is nowhere for an author to raise it". This is the
 * somewhere: the wizard opens on it, `inf_gis::DEFAULT_MAX_ENTITIES` is
 * what it starts at, and an author who raises it once does not raise it
 * again on the next layer.
 *
 * Clamped to `1..=`[`inf_gis::ISLAND_MAX_ENTITIES`] by
 * [`Self::normalize`], because a settings file is a text file a human can
 * edit and a cap of zero imports nothing while looking like a preference.
 */
gis_max_entities: number, 
/**
 * 3D gizmo snap increments (was `inf.viewport.snap3d` in localStorage).
 */
snap_3d: Snap3DDto, 
/**
 * Foliage brush configuration (was `inf.viewport.foliage`).
 */
foliage: FoliageSettingsDto, 
/**
 * Keybinding OVERRIDES, chord → command id. An empty command id means
 * "this default chord is unbound". Defaults are not written here; only what
 * the user changed, so a new default chord reaches an existing user.
 */
keybindings: { [key in string]: string }, };
