// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FoliageSettingsDto } from "./FoliageSettingsDto";
import type { Snap3DDto } from "./Snap3DDto";

/**
 * Application-level (per-user) editor settings.
 *
 * This type is **also the wire type**: `ipc.rs` re-exports it and the ts-rs
 * harness roots it, so there is exactly one definition and a Dto mirror cannot
 * drift out of step with the file format.
 *
 * Field order is load-bearing for TOML: every scalar comes before every table,
 * because `toml` refuses to emit a value after a table.
 */
export type EditorSettings = { 
/**
 * On-disk schema version. Stamped by [`Self::normalize`]; a file written by
 * a NEWER editor is refused rather than downgraded.
 */
schema_version: number, 
/**
 * Selected theme id (`lib/theme.ts`). Unknown ids fall back in the shell.
 */
theme_id: string, 
/**
 * Whether the first-run tour has been seen/dismissed.
 */
tour_seen: boolean, 
/**
 * Crash-recovery autosave period, seconds.
 */
autosave_interval_s: number, 
/**
 * Editor flycam speed at session start, m/s (the wheel still scales it).
 */
camera_fly_speed_mps: number, 
/**
 * Mouse-look sensitivity multiplier (1.0 = the shipped feel).
 */
camera_look_sensitivity: number, 
/**
 * A right-button gesture that travels less than this (physical px) **and**
 * lasts less than [`Self::rmb_click_ms`] is a click (context menu); longer
 * or further is a flycam drag.
 */
rmb_click_travel_px: number, 
/**
 * The time half of the same discrimination, milliseconds.
 */
rmb_click_ms: number, 
/**
 * **The GIS vector-import entity cap** (IB-14), remembered per user.
 *
 * The certification's complaint about this number was that it was
 * "reported and never silent, which is the right design — but with no
 * wizard there is nowhere for an author to raise it". This is the
 * somewhere: the wizard opens on it, `inf_gis::DEFAULT_MAX_ENTITIES` is
 * what it starts at, and an author who raises it once does not raise it
 * again on the next layer.
 *
 * Clamped to `1..=`[`inf_gis::ISLAND_MAX_ENTITIES`] by
 * [`Self::normalize`], because a settings file is a text file a human can
 * edit and a cap of zero imports nothing while looking like a preference.
 */
gis_max_entities: number, 
/**
 * **The project the application opens when it is launched with none**
 * (wave CERT1) — rung 2 of `inf_project::boot::resolve`.
 *
 * An absolute project root, or **empty for "not pinned"**. A `String`
 * rather than an `Option<String>` because this file is TOML and TOML has no
 * `None` to write; the alternative is a `skip_serializing_if`, which is the
 * attribute this repository has been bitten by three times and which would
 * make an absent key and an empty key two different states for a reader to
 * hold.
 *
 * **Written by every successful project open** *unless
 * [`boot_project_deliberate`](Self::boot_project_deliberate) is set, which
 * an open never overwrites.* So the plain meaning is *the last project you
 * opened*, or *the project you made the default*, and the flag below says
 * which. A pin that names a project the author has since deleted is skipped
 * rather than fatal — `inf_project::boot` falls through to the showcase.
 */
boot_project: string, 
/**
 * **Whether [`boot_project`](Self::boot_project) was CHOSEN or merely
 * VISITED** (CERT1 audit ruling).
 *
 * `true` puts the pin at rung 2 of `inf_project::boot::resolve`, above the
 * showcase island; `false` puts it at rung 4, below it. That is the whole
 * of the ruling, and the reason it is a bit rather than a policy: the audit
 * measured that one pin at rung 2, written by every open, meant **the first
 * other project an author opened took the showcase's place for ever**, with
 * no UI to see or clear it. A visit is not a decision.
 *
 * Set only by Preferences ▸ General ▸ "Make this project the default", and
 * cleared only by "Reset to the showcase". `Default` is `false`, which is
 * what a settings file written before this field says too — so an existing
 * profile's pin is read as the visit it was.
 */
boot_project_deliberate: boolean, 
/**
 * 3D gizmo snap increments (was `inf.viewport.snap3d` in localStorage).
 */
snap_3d: Snap3DDto, 
/**
 * Foliage brush configuration (was `inf.viewport.foliage`).
 */
foliage: FoliageSettingsDto, 
/**
 * Keybinding OVERRIDES, chord → command id. An empty command id means
 * "this default chord is unbound". Defaults are not written here; only what
 * the user changed, so a new default chord reaches an existing user.
 */
keybindings: { [key in string]: string }, 
/**
 * **The GAME's binding overrides**, row id → source token (island wave I5).
 *
 * The same map, in the same format, that a shipped player writes into its
 * own settings file — `inf_ui::bindings`' row ids and name tokens, only
 * what differs from the shipped table. It lives here so an author can set a
 * project's controls from the editor's preferences and have Simulate and a
 * windowed PIE preview honour them, which is the second half of "rebinding
 * like UE5, in-game AND in the editor".
 *
 * **A different map from [`keybindings`](Self::keybindings)**, and
 * deliberately: that one is the *editor's* chords (Ctrl+Shift+P opens the
 * palette) and this one is the *game's* controls (C crouches). Folding them
 * together would put a chord and a key code in one namespace and make
 * "unbind" mean two things.
 */
game_bindings: { [key in string]: string }, };
