// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * **Which editors can open this entity** (`scene_entity_editors`, Wave E).
 *
 * One row per selected object. Every asset field is `Some` exactly when the
 * entity carries that link — and because those links are `#[reflect(ignore)]`
 * or unreflected, this DTO is the ONLY way the frontend can learn them.
 *
 * [`Self::no_editor_reason`] is `Some` exactly when every asset field is
 * `None`: a refusal is a value, so the UI shows a named reason (and the
 * remedy) instead of a dead menu item or an empty editor. Built by
 * [`crate::scene::editors`], which asserts that invariant.
 */
export type EntityEditorsDto = { 
/**
 * The entity GUID this row answers for.
 */
entity: string, 
/**
 * Display name (the Outliner label) — menus title themselves with it.
 */
name: string, 
/**
 * The UE-style type label ("Static Mesh", "Skeletal Mesh", "Terrain", …).
 */
kind: string, 
/**
 * `MeshRef::asset` — a `.inf_mesh` the Model Editor can open.
 */
mesh: string | null, 
/**
 * `SkeletalMesh::mesh` — also a `.inf_mesh`, and also openable.
 */
skeletal_mesh: string | null, 
/**
 * `SkeletalMesh::skeleton` — a `.inf_skel` the Skeleton Editor can open.
 */
skeleton: string | null, 
/**
 * `Material::asset` — a `.inf_mat` the material graph can open.
 */
material: string | null, 
/**
 * `ActorClass` — the `.inf_act` whose handlers the Blueprint panel raises.
 */
actor_class: string | null, 
/**
 * The built-in primitive drawn as a placeholder, if any ("Cube", …).
 * Present alongside `mesh`: the component carries both.
 */
primitive: string | null, 
/**
 * Why nothing can be opened, when nothing can. Never empty when set.
 */
no_editor_reason: string | null, };
