// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Hydraulic + thermal erosion parameters (`terrain_erode`). Defaults come from
 * [`inf_terrain::ErosionParams::default`]. Rates are per simulation step.
 */
export type ErosionParamsDto = { dt: number, rain_rate: number, rain_variation: number, rain_seed: number, rain_frequency: number, rain_octaves: number, evaporation: number, gravity: number, pipe_area: number, sediment_capacity: number, dissolving: number, deposition: number, min_tilt: number, max_erode_depth: number, thermal_talus_deg: number, thermal_rate: number, max_thermal_depth: number, thermal_every: number, };
