// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of an erosion bake (`terrain_erode`). `mass_delta` is the net terrain
 * volume change (world m³, negative = net-eroded), derived from the committed
 * delta so it is adapter-independent. `sediment_moved` is the CPU reference's
 * cumulative eroded volume — present only on the CPU (no-adapter) path, `None`
 * on the GPU path (GPU stat reductions are omitted; see the executor docs).
 */
export type ErosionReportDto = { cells_changed: number, 
/**
 * Data-map samples the bake moved (P19.1) — the flow / deposition / wear
 * accumulators it wrote. Always **at least** `cells_changed`: a height only
 * moves through the erode/deposit pass, which writes a map in the same
 * breath.
 */
map_cells_changed: number, mass_delta: number, sediment_moved: number | null, used_gpu: boolean, steps: number, };
