// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Foliage-brush configuration (`viewport_set_foliage`). `radius` is world
 * metres; `density` is target instances per m² of brush area; `kind` selects the
 * palette slot; `scale_jitter` is the ± fractional scale spread; `seed` makes a
 * stroke's scatter deterministically reproducible.
 */
export type FoliageSettingsDto = { radius: number, density: number, erase: boolean, kind: number, scale_jitter: number, align_to_normal: boolean, seed: number, };
