// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * [`inf_anim::locomotion::GaitParams`] on the wire. Angles are **degrees** (the
 * authoring boundary), rates are hertz, and the two `*_ratio` fields are
 * fractions of the rig's own hip height.
 */
export type GaitParamsDto = { walkCadenceHz: number, runCadenceHz: number, hipSwingDeg: number, kneeFlexDeg: number, armSwingDeg: number, runStrideScale: number, bobRatio: number, idlePeriodS: number, idleBobRatio: number, idlePitchDeg: number, keysPerCycle: number, };
