// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row of the **game's** binding table, as the preferences panel renders it
 * (island wave I5).
 *
 * A projection of `inf_ui::bindings::table`, not a second table: the in-game
 * dialog and this panel show the same rows in the same order from the same
 * source. A table restated in TypeScript is the "two copies across a language
 * boundary" defect `inf_input::default_map`'s own note records.
 */
export type GameBindingRowDto = { 
/**
 * The stable row id a settings file stores.
 */
id: string, 
/**
 * What a player reads.
 */
label: string, 
/**
 * What it is bound to; empty means unbound.
 */
token: string, 
/**
 * Whether this row has been moved off the shipped table.
 */
overridden: boolean, 
/**
 * Whether the control's consumer exists yet.
 */
wired: boolean, };
