// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a blueprint class's generated Rust landed, and whether it had to be
 * written (Wave D — the CODE TAB).
 */
export type GeneratedSourceDto = { 
/**
 * The absolute path, ready for `requestOpenFile`.
 */
path: string, 
/**
 * `false` when the file on disk already described this graph — the tab was
 * already current and nothing was touched.
 */
wrote: boolean, 
/**
 * `true` when the file did not exist before.
 */
created: boolean, };
