// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where on Earth world `(0, 0, 0)` is — `scene_get_geo_anchor` /
 * `scene_set_geo_anchor`.
 *
 * **A separate DTO rather than a field on [`LevelSettingsDto`]**, for the same
 * reason the anchor is a scene-file field rather than a settings block: it is
 * document provenance, not a simulation parameter. (It is also the practical
 * answer — `LevelSettingsDto` is `Copy`, and an anchor carries two strings.)
 *
 * Units, per the doctrine: the origin components are **metres**; latitude,
 * longitude and convergence are **degrees**, which is legal at a data boundary
 * for the same reason euler angles are.
 */
export type GeoAnchorDto = { 
/**
 * Whether this level is georeferenced at all.
 */
enabled: boolean, 
/**
 * The projected CRS the world plane lives in — an authority code
 * (`"EPSG:32610"`) or a full proj4 string.
 */
crs: string, 
/**
 * The CRS easting (metres) world `X = 0` means.
 */
origin_easting_m: number, 
/**
 * The CRS northing (metres) world `Z = 0` means. `+Z` is **south**.
 */
origin_northing_m: number, 
/**
 * The elevation (metres) world `Y = 0` means.
 */
origin_height_m: number, 
/**
 * Geodetic latitude of the origin, degrees, `+` north. Derived at the
 * import door; the panel shows it and does not ask for it.
 */
origin_latitude_deg: number, origin_longitude_deg: number, 
/**
 * Degrees from grid north to true north at the origin.
 */
grid_convergence_deg: number, 
/**
 * The vertical datum the heights are referenced to (informational — this
 * engine applies no geoid model).
 */
vertical_datum: string, 
/**
 * A human explanation of why this anchor cannot be used, or `null` when it
 * is fine. Computed by the same `validate` every import door calls, so the
 * panel and the importer cannot disagree about what is wrong.
 */
issue: string | null, };
