// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a georeferenced source says about where it is — the wizard's
 * "this DEM covers …" readout (Wave G).
 */
export type GeoReferenceDto = { 
/**
 * The EPSG code the file names, if any.
 */
epsg: number | null, 
/**
 * A human CRS name from the file, if it carries one.
 */
crs_name: string | null, 
/**
 * `true` when the CRS is geographic, so `pixel_size` is in DEGREES rather
 * than metres. The wizard must say which — a 0.000278 "metre" pixel is a
 * quarter of a millimetre and an author reading that will assume a bug.
 */
crs_is_geographic: boolean, 
/**
 * Ground size of one pixel, in the CRS's own units.
 */
pixel_size: number | null, 
/**
 * The model coordinate of the raster's top-left sample.
 */
origin_x: number | null, origin_y: number | null, 
/**
 * The no-data sentinel the file declares, if any.
 */
nodata: number | null, 
/**
 * The vertical unit label ("metres", "international feet", …).
 */
vertical_units: string, 
/**
 * `true` when the file carried enough to place itself on Earth.
 */
is_georeferenced: boolean, };
