// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One attribute field of a vector source, summarised over the whole layer.
 */
export type GisFieldDto = { name: string, present: number, numeric: number, sample: string | null, };
