// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a GIS import produced — the wizard's done state.
 */
export type GisImportResultDto = { layer_name: string, crs: string, spawned: number, too_short: number, unusable: number, truncated: number, cap: number, 
/**
 * The one-line summary, written once in Ring 0 and shown here, in the log
 * and by `inf gis`.
 */
summary: string, 
/**
 * A stable digest of the plan — the same number `inf gis plan` prints.
 */
digest: string, 
/**
 * The road surface's summary, when one was built.
 */
road_summary: string | null, 
/**
 * The land-cover paint's summary, when one was painted.
 */
biome_summary: string | null, 
/**
 * The footprint bake's summary, when buildings were built.
 */
building_summary: string | null, 
/**
 * GUIDs of every `.inf_mesh` the import wrote.
 */
meshes: Array<string>, advisories: Array<string>, };
