// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Everything the GIS wizard sends back.
 *
 * **The caps are here, which is the whole of IB-14's editor half.**
 */
export type GisImportSettingsDto = { 
/**
 * A [`inf_gis::LayerKind`] label: `roads`, `streams`, `lakes`, `biomes`,
 * `buildings`, `parcels`, `generic`.
 */
kind: string, 
/**
 * Empty reads the `.prj`.
 */
source_crs: string, 
/**
 * `0` reads the `.prj`'s vertical unit.
 */
vertical_unit_m: number, 
/**
 * The entity cap. See `inf_gis::DEFAULT_MAX_ENTITIES` and
 * `ISLAND_MAX_ENTITIES`.
 */
max_entities: number, min_length_m: number, reverse_flow: boolean, name_prefix: string, 
/**
 * Build a real road surface (`.inf_mesh` + entity) as well as the
 * centreline splines — IB-4.
 */
road_surface: boolean, road_lift_m: number, road_ground_step_m: number, 
/**
 * Paint the layer's classes into a terrain's biome ids — IB-5a. Empty
 * means "do not".
 */
biome_terrain: string, 
/**
 * The class attribute; empty probes the known spellings.
 */
biome_attribute: string, biome_classes: number, 
/**
 * Build each footprint into geometry — IB-5b + IB-6.
 */
buildings: boolean, max_buildings: number, furnish: boolean, };
