// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GisCrsDto } from "./GisCrsDto";
import type { GisFieldDto } from "./GisFieldDto";

/**
 * What is inside a vector source — the wizard's preview step.
 */
export type GisProbeDto = { path: string, format: string, layer_name: string, features: number, points: number, polylines: number, polygons: number, 
/**
 * `"point"`, `"polyline"` or `"polygon"` — what the layer mostly is, and
 * therefore which target kinds make sense.
 */
dominant_kind: string, fields: Array<GisFieldDto>, crs: GisCrsDto, 
/**
 * The layer's centre on Earth, degrees.
 */
centre_lat: number | null, centre_lon: number | null, 
/**
 * The UTM zone this engine suggests anchoring a world in.
 */
suggested_anchor_epsg: number | null, 
/**
 * The level's current anchor CRS, or `None` when it has no anchor. The
 * wizard shows both, because "the file says zone 10 and your world is
 * anchored in zone 11" is the question an author needs asked.
 */
level_anchor_crs: string | null, skipped: Array<string>, advisories: Array<string>, };
