// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitFileDto } from "./GitFileDto";

/**
 * The working-tree status (`git_status`).
 */
export type GitStatusDto = { 
/**
 * False when `repo` is not a git repository.
 */
is_repo: boolean, 
/**
 * Current branch (or detached HEAD label).
 */
branch: string, 
/**
 * Commits ahead of / behind the upstream.
 */
ahead: number, behind: number, files: Array<GitFileDto>, };
