// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Gizmo orientation frame (`viewport_set_gizmo_space`). `World` aligns handles
 * to the world axes; `Local` aligns them to the selection's own rotation.
 * Serializes as the tag string `"World"`/`"Local"`.
 */
export type GizmoSpaceDto = "World" | "Local";
