// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GeoReferenceDto } from "./GeoReferenceDto";
import type { TerrainImportSettingsDto } from "./TerrainImportSettingsDto";

/**
 * What `terrain_probe_heightmap` read out of a heightmap's **header** — no
 * pixels were decoded, so this is instant even for a 16 k × 16 k source.
 */
export type HeightmapProbeDto = { 
/**
 * Absolute source path (echoed so the wizard can keep one object).
 */
path: string, 
/**
 * "PNG" | "EXR" | "TIFF".
 */
format: string, width: number, height: number, 
/**
 * Bits per sample of the source.
 */
bit_depth: number, 
/**
 * `true` when the source carries IEEE floats.
 */
float_samples: boolean, 
/**
 * `true` when the samples are absolute elevations — i.e. when float-metres
 * mode is offered. Not the same question as `float_samples`: a 16-bit
 * integer GeoTIFF DEM is an elevation raster and is not a float.
 */
absolute_samples: boolean, 
/**
 * The channel the importer will read ("gray", "Y", …).
 */
channel: string, 
/**
 * GeoTIFF georeferencing, when the source carries any (Wave G).
 */
geo: GeoReferenceDto | null, 
/**
 * The settings the wizard opens with for this source.
 */
suggested: TerrainImportSettingsDto, };
