// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One import-progress event (`assets://import`).
 */
export type ImportEventDto = { job: number, source: string, 
/**
 * "started" | "finished" | "failed".
 */
phase: string, 
/**
 * GUIDs produced (on "finished").
 */
produced: Array<string>, primary: string | null, cached: boolean, error: string | null, };
