// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One import-progress event (`assets://import`).
 */
export type ImportEventDto = { job: number, source: string, 
/**
 * "started" | "progress" | "finished" | "failed".
 */
phase: string, 
/**
 * GUIDs produced (on "finished").
 */
produced: Array<string>, primary: string | null, cached: boolean, error: string | null, 
/**
 * Units of work completed / total (on "progress"; terrain imports report
 * tiles written across every LOD level). `null` for jobs with no progress
 * model.
 */
done: number | null, total: number | null, 
/**
 * A short stage label on "progress" ("tiles", "lod2", …).
 */
stage: string | null, };
