// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a still-water level lands on the terrain inside a rectangle
 * (`water_lake_preview`).
 */
export type LakePreviewDto = { level_m: number, 
/**
 * Fraction of the *known* samples at or below the level, `[0, 1]`.
 */
covered_fraction: number, max_depth_m: number, mean_depth_m: number, 
/**
 * Grid samples taken, and how many the terrain answered for. `known == 0`
 * means "there is no ground here", which is a different statement from
 * "the lake is empty".
 */
samples: number, known: number, 
/**
 * The waterline as flat `[x0, z0, x1, z1]` world-XZ segments. Flat rather
 * than nested so the JSON stays one array of numbers for a few thousand
 * segments.
 */
waterline: Array<number>, };
