// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A saved dock-layout preset (`layout_list` command).
 */
export type LayoutSummary = { name: string, 
/**
 * Last-modified time, unix epoch milliseconds.
 */
modified_ms: number, };
