// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RenderSettingsRecordDto } from "./RenderSettingsRecordDto";

/**
 * The level's file-level settings, as the World Settings panel edits them
 * (`scene_get_settings` / `scene_set_settings`). Mirrors
 * [`crate::scene::serialize::LevelSettings`]; `render` nests
 * [`RenderSettingsRecordDto`].
 */
export type LevelSettingsDto = { 
/**
 * 2D world gravity (m/s²) — `[x, y]`.
 */
gravity_2d: [number, number], 
/**
 * 3D world gravity (m/s²) — `[x, y, z]`.
 */
gravity_3d: [number, number, number], 
/**
 * Fixed simulation update rate (Hz).
 */
sim_hz: number, 
/**
 * Renderer HDR / post / lighting block.
 */
render: RenderSettingsRecordDto, };
