// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Log severity for the Output Log panel. Mirrors `tracing::Level`.
 */
export type LogLevel = "trace" | "debug" | "info" | "warn" | "error";
