// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogLevel } from "./LogLevel";

/**
 * One structured line on the `log://line` event channel (Output Log panel).
 * Produced by the studio's tracing subscriber layer; `seq` is a per-session
 * monotonic counter so the frontend can detect dropped lines and keep a
 * stable virtual-list identity.
 */
export type LogLine = { 
/**
 * Exported as `number`: session-lifetime counts stay far below 2^53.
 */
seq: number, level: LogLevel, 
/**
 * tracing target (module path), e.g. `inf_render::surface`.
 */
target: string, message: string, 
/**
 * Unix epoch milliseconds (f64 for lossless JS interop).
 */
timestamp_ms: number, };
