// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MatOverridesDto } from "./MatOverridesDto";
import type { MatValuesDto } from "./MatValuesDto";

/**
 * A material instance projected for the override editor
 * (`asset_get_material_instance`).
 */
export type MaterialInstanceDto = { 
/**
 * Parent material/instance GUID (string form).
 */
parent: string, 
/**
 * Parent display name (editor caption).
 */
parent_name: string, 
/**
 * The parent's resolved PBR baseline (inherited, grayed under unset overrides).
 */
resolved: MatValuesDto, 
/**
 * This instance's sparse overrides.
 */
overrides: MatOverridesDto, };
