// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The sparse overrides an instance carries (`null` = inherit the parent value).
 */
export type MatOverridesDto = { base_color: [number, number, number, number] | null, metallic: number | null, roughness: number | null, emissive: [number, number, number] | null, };
