// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Concrete resolved PBR values (the parent chain resolved) — the inherited
 * baseline the editor shows grayed under each unset override.
 */
export type MatValuesDto = { base_color: [number, number, number, number], metallic: number, roughness: number, emissive: [number, number, number], };
