// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One effect in a bus's chain, mirroring [`inf_audio::Effect`]. `Gain` is
 * fully engine-side and editable (a dB trim folded into the bus's linear gain);
 * `Lowpass` is a device-side DSP effect the editor shows read-only (its cutoff
 * is modelled + folded, but audible filtering needs the cpal sub-track wiring —
 * a documented follow-up). The tag mirrors [`PropValueDto`]'s `kind` convention.
 */
export type MixerEffectDto = { "kind": "gain", db: number, } | { "kind": "lowpass", cutoff_hz: number, };
