// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MixerBusDto } from "./MixerBusDto";

/**
 * The project mixer configuration (mirrors [`inf_audio::MixerConfig`], minus the
 * on-disk `schema_version`, which `mixer_save` stamps with the current version).
 */
export type MixerConfigDto = { 
/**
 * The buses, in declaration order (order is preserved on save).
 */
buses: Array<MixerBusDto>, };
