// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MixerEffectDto } from "./MixerEffectDto";

/**
 * One mixer bus (mirrors [`inf_audio::Bus`]): a unique name, an optional parent
 * for the routing hierarchy, a linear volume, and an ordered effect chain.
 */
export type MixerBusDto = { 
/**
 * Unique bus name — the key an entity's free-form `AudioSource.bus` matches.
 */
name: string, 
/**
 * Parent bus name; `None` for a root (`"master"` is the undeletable root).
 */
parent: string | null, 
/**
 * Linear volume (`1.0` = unity).
 */
volume: number, 
/**
 * Ordered effect chain (Gain editable, Lowpass read-only).
 */
effects: Array<MixerEffectDto>, };
