// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One per-kind asset count in a cook report (`PackageResultDto.kinds`). `kind`
 * is the asset-kind slug (`"mesh"`, `"level"`, `"blueprint"`, …).
 */
export type PackageKindCountDto = { kind: string, count: number, };
