// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A structured cook failure (the `Err` payload of `project_package`). `class`
 * is the error category slug; blueprint failures additionally carry the
 * blueprint class name (`blueprint_class`) and the handler/function where the
 * problem lives (`handler`) so the dialog can anchor the error. `guid` is the
 * offending asset GUID when one is known.
 */
export type PackageErrorDto = { 
/**
 * Error category: `"no_project"`, `"blueprint"`, `"scene"`, `"unknown_root"`,
 * `"bad_root"`, `"io"`, `"project"`, `"asset"`, `"manifest"`, `"internal"`.
 */
class: string, 
/**
 * Human-readable message.
 */
message: string, 
/**
 * The failing blueprint's class name (blueprint failures only).
 */
blueprint_class: string | null, 
/**
 * The handler/function anchor (blueprint failures only).
 */
handler: string | null, 
/**
 * The offending asset GUID, when known.
 */
guid: string | null, };
