// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageKindCountDto } from "./PackageKindCountDto";

/**
 * A successful cook, projected for the Package dialog (`project_package`).
 */
export type PackageResultDto = { project_name: string, engine_version: string, 
/**
 * Output directory the build was written to (forward-slashed).
 */
out_dir: string, 
/**
 * The written pack file (forward-slashed).
 */
pack_path: string, 
/**
 * The written manifest file (forward-slashed).
 */
manifest_path: string, 
/**
 * Total assets packed.
 */
asset_count: number, 
/**
 * Per-kind counts, sorted by slug.
 */
kinds: Array<PackageKindCountDto>, 
/**
 * Size of the written pack in bytes.
 */
pack_bytes: number, 
/**
 * Level GUIDs in the pack (sorted).
 */
levels: Array<string>, 
/**
 * The primary/boot level GUID (lowest), if any.
 */
root_level: string | null, 
/**
 * How many blueprint assets were validated.
 */
blueprints_validated: number, 
/**
 * How many levels were rewritten to the runtime schema.
 */
levels_rewritten: number, 
/**
 * Non-fatal advisories (e.g. "no levels").
 */
warnings: Array<string>, 
/**
 * The **cannot-ship** subset of [`warnings`](Self::warnings) (C4-40,
 * re-opened as round-2 finding B10 == R2.F8).
 *
 * `CookReport::has_blocking` is the one question `inf cook`'s exit code
 * asks, and it never reached the editor: `report_to_dto` dropped the field
 * and this DTO had no slot for it, so the Package dialog — **the door an
 * author actually uses** — rendered the identical strings inside a yellow
 * "N warnings" list under a full success panel, with `Boot Level: none` as
 * a plain stat beside it. The CLI refused to ship the same build.
 *
 * Carried as its own list rather than recovered from the message text,
 * exactly as `CookReport` carries it: which advisories block shipping is a
 * decision, not a spelling.
 */
blocking: Array<string>, };
