// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageKindCountDto } from "./PackageKindCountDto";

/**
 * A successful cook, projected for the Package dialog (`project_package`).
 */
export type PackageResultDto = { project_name: string, engine_version: string, 
/**
 * Output directory the build was written to (forward-slashed).
 */
out_dir: string, 
/**
 * The written pack file (forward-slashed).
 */
pack_path: string, 
/**
 * The written manifest file (forward-slashed).
 */
manifest_path: string, 
/**
 * Total assets packed.
 */
asset_count: number, 
/**
 * Per-kind counts, sorted by slug.
 */
kinds: Array<PackageKindCountDto>, 
/**
 * Size of the written pack in bytes.
 */
pack_bytes: number, 
/**
 * Level GUIDs in the pack (sorted).
 */
levels: Array<string>, 
/**
 * The primary/boot level GUID (lowest), if any.
 */
root_level: string | null, 
/**
 * How many blueprint assets were validated.
 */
blueprints_validated: number, 
/**
 * How many levels were rewritten to the runtime schema.
 */
levels_rewritten: number, 
/**
 * Non-fatal advisories (e.g. "no levels").
 */
warnings: Array<string>, };
