// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * World-partition settings, as the World Settings panel edits them (P16.5).
 * Mirrors [`crate::scene::serialize::PartitionSettings`].
 *
 * **The editor stays single-document.** Turning `enabled` on does not partition
 * the open level in the editor — nothing streams while authoring. It tells the
 * *cook* to split the level into cells and the *player* (PIE and shipping) to
 * stream them.
 */
export type PartitionSettingsDto = { 
/**
 * Whether this level is partitioned at cook time and streamed at runtime.
 */
enabled: boolean, 
/**
 * Square cell edge length (metres).
 */
cell_size_m: number, 
/**
 * How close a streaming source must come to a cell before its entities
 * **spawn** (metres). Sim-visible: it decides what exists.
 */
activation_radius_m: number, 
/**
 * Extra metres within which a cell may be *loaded* ahead of need.
 * **Not** sim-visible: a cell that reaches its activation step unloaded
 * blocks the step, so this buys latency and never changes a result.
 */
prefetch_margin_m: number, };
