// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * **What the editor camera's PCG streaming is doing** (`pcg://stream`, wave
 * EDIT1, clauses 1 and 5).
 *
 * The instrument, and the "Loading world…" indicator's source. Every count is
 * of *volumes carrying a graph* — a `PcgVolume` with none has nothing to
 * evaluate, so counting it would give the indicator a denominator it can never
 * reach.
 *
 * Emitted only when it changes (a settled editor is silent), and readable on
 * demand through `pcg_stream_status` for a panel that mounts after the last
 * event.
 */
export type PcgStreamStatusDto = { 
/**
 * Whether the camera is streaming at all (the editor preference).
 */
enabled: boolean, 
/**
 * The editor is behind its own camera — some volume inside the radius has
 * no population yet.
 */
loading: boolean, 
/**
 * Volumes in the level that name a graph.
 */
volumes: number, 
/**
 * Of those, how many are inside the prefetch radius.
 */
in_radius: number, 
/**
 * Of those, how many hold a population — the indicator's numerator.
 */
in_radius_populated: number, 
/**
 * How many hold a population anywhere in the level.
 */
populated: number, 
/**
 * Volumes evaluated by the last tick that did any work.
 */
last_tick_evaluated: number, 
/**
 * Wall milliseconds that tick spent evaluating…
 */
last_tick_ms: number, 
/**
 * …against this ceiling (`EDITOR_PCG_STEP_BUDGET_MS`). Both, because a
 * spend without its budget beside it is a number nobody can read.
 */
budget_ms: number, evaluated_total: bigint, released_total: bigint, 
/**
 * The radii in force, metres — the level's own partition block, scaled by
 * the editor preference.
 */
activation_m: number, prefetch_m: number, };
