// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row of the wizard's photograph table.
 */
export type PhotoEntryDto = { path: string, name: string, 
/**
 * `0` when the file did not decode.
 */
width: number, height: number, 
/**
 * Why it did not decode.
 */
error: string | null, };
