// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The currently-open project, as the editor start screen / title bar sees it.
 */
export type ProjectInfoDto = { name: string, 
/**
 * Absolute project root (forward-slashed).
 */
root: string, 
/**
 * Content root relative to the project.
 */
content_dir: string, 
/**
 * Levels root relative to the project.
 */
levels_dir: string, 
/**
 * Template slug the project was scaffolded from.
 */
template: string, };
