// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-project editor settings persisted under `<root>/.infinity/settings.toml`
 * (`project_settings_get` / `project_settings_set`).
 */
export type ProjectSettingsDto = { 
/**
 * Pixels-per-unit for 2D pixel snapping (default 100).
 */
pixels_per_unit: number, };
