// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A first-run project template (New Project dialog).
 */
export type ProjectTemplateDto = { slug: string, label: string, description: string, };
