// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectInfoDto } from "./ProjectInfoDto";

/**
 * **The project the application opens when it is launched with none** (wave
 * CERT1) — the answer `inf_project::boot::resolve` gave, with the rung that
 * gave it.
 *
 * The rung is carried rather than inferred because the status line the shell
 * prints says *why* a project opened, and "you pinned this" and "this is the
 * showcase the engine found beside your checkout" are two different sentences
 * for an author to act on.
 */
export type ProjectBootDto = { 
/**
 * The opened project.
 */
project: ProjectInfoDto, 
/**
 * `inf_project::BootSource::phrase` — a short human clause, already
 * wordable into a sentence ("opened Vancouver Island — the showcase
 * island").
 */
source: string, };
