// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A typed property value crossing to the Details panel. The `kind` tag selects
 * the widget; only the matching payload field is meaningful.
 */
export type PropValueDto = { "kind": "bool", value: boolean, } | { "kind": "number", value: number, } | { "kind": "text", value: string, } | { "kind": "vec3", value: Array<number>, } | { "kind": "color", value: Array<number>, } | { "kind": "enum", value: string, options: Array<string>, };
