// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PropValueDto } from "./PropValueDto";

/**
 * One editable field row.
 */
export type PropFieldDto = { 
/**
 * Reflect field key (write path).
 */
name: string, 
/**
 * Display label.
 */
label: string, value: PropValueDto, 
/**
 * Whether every selected object shares this value (multi-edit "—").
 */
same: boolean, };
