// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PropValueDto } from "./PropValueDto";

/**
 * One editable field row.
 */
export type PropFieldDto = { 
/**
 * Reflect field key (write path).
 */
name: string, 
/**
 * Display label.
 */
label: string, value: PropValueDto, 
/**
 * Whether every selected object shares this value (multi-edit "—").
 */
same: boolean, 
/**
 * The numeric widget's `[min, max, step]`, when the engine knows the
 * field's units (wave VIS1b, `inf_ecs::props::prop_range`). `None` ⇒ the
 * plain number box every reflected row has always drawn.
 *
 * A **hint**, carried on the same terms as `AssetRef`'s `asset_kind`: the
 * panel must not need a second source of truth about what a row means, and
 * the write door does not clamp to it.
 */
range: [number, number, number] | null, };
