// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry in the recent-projects list.
 */
export type RecentProjectDto = { name: string, path: string, };
