// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The persisted renderer HDR / post / lighting settings, as the World Settings
 * panel edits them (`scene_get_settings` / `scene_set_settings`). Mirrors
 * [`crate::scene::serialize::RenderSettingsRecord`] field-for-field.
 */
export type RenderSettingsRecordDto = { exposure: number, dither: boolean, bloom_enabled: boolean, bloom_threshold: number, bloom_knee: number, bloom_intensity: number, ssao_enabled: boolean, ssao_radius: number, ssao_intensity: number, ssao_bias: number, taa: boolean, shadows_enabled: boolean, shadows_max_distance: number, gi_enabled: boolean, gi_intensity: number, };
