// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The persisted renderer HDR / post / lighting settings, as the World Settings
 * panel edits them (`scene_get_settings` / `scene_set_settings`). Mirrors
 * [`crate::scene::serialize::RenderSettingsRecord`] field-for-field.
 */
export type RenderSettingsRecordDto = { exposure: number, dither: boolean, bloom_enabled: boolean, bloom_threshold: number, bloom_knee: number, bloom_intensity: number, ssao_enabled: boolean, ssao_radius: number, ssao_intensity: number, ssao_bias: number, taa: boolean, shadows_enabled: boolean, shadows_max_distance: number, gi_enabled: boolean, gi_intensity: number, ssr_enabled: boolean, ssr_distance: number, ssr_thickness: number, ssr_quality: number, ssr_intensity: number, ssr_roughness_cutoff: number, exposure_mode: number, exposure_compensation_ev: number, exposure_min_luminance: number, exposure_max_luminance: number, exposure_adaptation_speed: number, bloom_karis: boolean, flare_enabled: boolean, flare_intensity: number, flare_ghost_count: number, flare_halo: number, flare_streak: number, vignette_intensity: number, vignette_smoothness: number, chromatic_aberration: number, grain_intensity: number, grain_size: number, };
