// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RiverBedConflictDto } from "./RiverBedConflictDto";
import type { RiverClimbDto } from "./RiverClimbDto";

/**
 * The river tool's verdict on one river (`water_river_report`).
 */
export type RiverReportDto = { 
/**
 * The river entity's GUID.
 */
entity: string, length_m: number, points: number, 
/**
 * Source elevation minus mouth elevation, read the way the water flows.
 */
fall_m: number, 
/**
 * The two **cook** advisories, re-run here so the tool says what the build
 * will say.
 */
surface_climbs: Array<RiverClimbDto>, bed_climbs: Array<RiverClimbDto>, 
/**
 * The terrain-aware conflicts, which only the editor can produce.
 */
bed_conflicts: Array<RiverBedConflictDto>, 
/**
 * Frames the terrain answered for, out of the total — a report over 3 of 200
 * frames is not a clean bill of health.
 */
sampled_frames: number, total_frames: number, };
