// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One stretch where a river disagrees with the ground under it.
 */
export type RiverBedConflictDto = { 
/**
 * `"buried"` (terrain above the surface) or `"perched"` (terrain below the
 * authored bed) — `BedIssue::id()`, a stable id the frontend switches on.
 */
issue: string, from_s: number, to_s: number, worst_m: number, worst_x: number, worst_z: number, };
