// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What one `scene_save` actually accomplished (P16.4b).
 *
 * A level save is no longer a single all-or-nothing act: the `.inf_lvl` and the
 * `.inf_terrain` assets its streamed terrains reference are **separate files**,
 * and one can land while another does not. Returning this instead of `()` is
 * what lets the shell say "the level saved, this terrain did not" rather than
 * reporting a clean save that quietly did less than the user asked for.
 */
export type SaveResultDto = { 
/**
 * Absolute path of the `.inf_lvl` payload written.
 */
path: string, 
/**
 * How many `.inf_terrain` assets were rewritten with sculpt/paint edits.
 */
terrain_assets_written: number, 
/**
 * How many level-0 tiles were folded into those assets.
 */
terrain_tiles_written: number, 
/**
 * One line per terrain whose edits could **not** be written. Empty on a
 * fully clean save. These edits are still in memory, still marked unsaved,
 * and are retried by the next save — nothing was lost, but nothing was
 * persisted either, and the user has to be told.
 */
terrain_failures: Array<string>, 
/**
 * How many `.inf_voxel` assets were rewritten with carve edits (P21.2).
 */
voxel_assets_written: number, 
/**
 * How many chunks were folded into those assets.
 */
voxel_chunks_written: number, 
/**
 * Everything about this save that did **not** persist a cave, in two
 * flavours that read the same way to an author (P21.2):
 *
 * * a volume whose `.inf_voxel` could not be written — the terrain-failure
 *   twin, still in memory, still retried;
 * * an **inline-terrain hole advisory**: this document is carrying cave
 *   mouths on a terrain whose container cannot store them, so the save just
 *   sealed them. The carve tools refuse to create that state, so it means
 *   the document arrived in it; the line names the terrain and the fix.
 *
 * Separate from `terrain_failures` because they are separate assets with
 * separate outcomes — a save may write every tile and no chunk.
 */
voxel_warnings: Array<string>, };
