// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entity as the Outliner sees it. `guid` is the stable string identity.
 */
export type SceneNode = { guid: string, name: string, 
/**
 * UE-style type column ("Static Mesh", "Point Light", "Folder", …).
 */
kind: string, 
/**
 * This entity's own visibility toggle (the eye).
 */
visible: boolean, 
/**
 * Effective visibility (self AND every ancestor) — drives dimming.
 */
effective_visible: boolean, 
/**
 * Parent GUID, or `None` for a root.
 */
parent: string | null, 
/**
 * Ordered child GUIDs.
 */
children: Array<string>, };
