// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SceneNode } from "./SceneNode";

/**
 * An incremental world change (`world://delta` event). Structural edits ship
 * as added/removed/updated node sets; `roots`, `selection`, and the doc meta
 * are small so they ride along every delta for a trivially-correct reducer.
 */
export type SceneDelta = { version: number, added: Array<SceneNode>, removed: Array<string>, updated: Array<SceneNode>, roots: Array<string>, selection: Array<string>, dirty: boolean, title: string, can_undo: boolean, can_redo: boolean, undo_label: string | null, redo_label: string | null, };
