// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The sculpt brush operation. Serializes as its tag string.
 */
export type SculptOpDto = "Raise" | "Lower" | "Smooth" | "Flatten" | "Noise";
