// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SculptFalloffDto } from "./SculptFalloffDto";
import type { SculptOpDto } from "./SculptOpDto";

/**
 * Sculpt brush configuration pushed from the viewport toolbar
 * (`viewport_set_sculpt`). `radius` is world metres; `strength` is per-dab
 * metres at full weight for Raise/Lower/Noise, or a `[0,1]` blend fraction for
 * Smooth/Flatten.
 */
export type SculptSettingsDto = { op: SculptOpDto, radius: number, strength: number, falloff: SculptFalloffDto, };
