// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The sculpt brush operation. Serializes as its tag string. `Paint` is the
 * P10.4 splat sub-mode (edits layer weights, targeting `paint_layer`).
 */
export type SculptOpDto = "Raise" | "Lower" | "Smooth" | "Flatten" | "Noise" | "Paint";
