// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Options for `search_workspace`.
 */
export type SearchOptsDto = { regex: boolean, case_sensitive: boolean, };
