// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One `search_workspace` hit.
 */
export type SearchHitDto = { 
/**
 * Path relative to the searched root (forward-slashed).
 */
path: string, 
/**
 * 1-based line number.
 */
line: number, 
/**
 * 1-based column of the match start.
 */
column: number, 
/**
 * The matching line's text (trimmed to a sane length).
 */
text: string, };
