// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Keyframe interpolation for a sequencer track segment (mirrors
 * [`crate::sequencer::Interp`]).
 */
export type SeqInterpDto = "step" | "linear";
