// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SeqInterpDto } from "./SeqInterpDto";

/**
 * One keyframe on a scalar track: a time (seconds), a scalar value, and the
 * interpolation governing the segment starting here.
 */
export type SeqKeyDto = { t: number, value: number, interp: SeqInterpDto, };
