// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SeqTrackDto } from "./SeqTrackDto";

/**
 * A sequencer timeline (the panel's document view; mirrors
 * [`crate::sequencer::Sequence`]).
 */
export type SequenceDto = { name: string, duration: number, 
/**
 * Authoring frame rate hint — the retime/snap grid is `1 / fps_hint`.
 */
fps_hint: number, tracks: Array<SeqTrackDto>, };
