// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkelDocDto } from "./SkelDocDto";

/**
 * The answer to every mutating Skeleton Editor command.
 *
 * One shape for all of them (the [`DccApplyDto`] pattern) so the frontend has a
 * single reducer, and a refusal can never be mistaken for a success that
 * happened to change nothing.
 */
export type SkelApplyDto = { ok: boolean, 
/**
 * Why it refused — the Ring-1 error's own text, which names the joint, the
 * socket or the parameter. `None` when `ok`.
 */
refusal: string | null, 
/**
 * What a successful edit **cost**, when that is not nothing: a rename that
 * left the canonical vocabulary or broke a mirror pair. A warning, never a
 * refusal — the edit happened.
 */
warning: string | null, doc: SkelDocDto, };
