// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One socket, as the socket list reads it.
 */
export type SkelSocketDto = { name: string, joint: number, translation: [number, number, number], rotation: [number, number, number, number], scale: [number, number, number], };
