// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One joint, as the tree view reads it.
 */
export type SkelJointDto = { 
/**
 * Index into the skeleton's joints — the id every other command uses.
 */
index: number, name: string, 
/**
 * `None` for a root.
 */
parent: number | null, 
/**
 * Local **rest** translation (metres), rotation (`[x,y,z,w]`) and scale —
 * the values the transform editor writes back. Not the animated pose: a
 * skeleton asset has none.
 */
translation: [number, number, number], rotation: [number, number, number, number], scale: [number, number, number], 
/**
 * One of the canonical humanoid nineteen. The panel marks these because
 * renaming one costs `RetargetMap::humanoid_identity` a pairing.
 */
canonical: boolean, 
/**
 * This joint's left/right twin, when the rig has one.
 */
mirror: number | null, 
/**
 * The name says it has a side and the rig has no twin — mirroring across
 * this rig would weight the copy to the wrong side.
 */
sidedWithoutTwin: boolean, 
/**
 * The authored rotation limit, if any: min/max degrees about local X/Y/Z.
 * **Absent means unlimited**, which is why these are `Option` and not a
 * full-range default (`inf_anim::JointLimit`'s own rule).
 */
limitMinDeg: [number, number, number] | null, limitMaxDeg: [number, number, number] | null, };
