// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The level's **physical atmosphere** as the World Settings panel edits it
 * (P17.2) — the sky-authority entity's `inf_ecs::components::SkyAtmosphere`.
 *
 * Like [`TimeOfDayDto`] this is an entity projection, not a file-settings
 * record, and it rides the same [`present`](Self::present) create flag: the two
 * components live on the same authority, so opting into either creates both.
 *
 * **Deliberately numeric-and-boolean only.** `SkyAtmosphere` also carries five
 * `Color` fields (sun, moon, and the three gradient colours); those stay in the
 * reflection Details grid, which already has a colour widget, rather than
 * forcing one into the World Settings property-row kit. Nothing is lost — the
 * panel edits the block a level actually tunes, and Details edits the rest
 * through the same undo door.
 *
 * Units per architecture rule 6: the fog block and the P17.3 **cloud block** are
 * **SI metres** (`m⁻¹` extinction and falloff, metre heights, m/s wind); the disc
 * sizes are **degrees of angular diameter**; everything else is a dimensionless
 * multiplier over a physical constant that lives in `inf_render::atmosphere` or
 * `inf_render::clouds`.
 *
 * The cloud block follows the same numeric-and-boolean rule: `cloud_color` stays
 * in Details with the other five colours.
 */
export type SkyAtmosphereDto = { 
/**
 * Whether the level has a sky authority at all. `false` ⇒ these are the
 * component defaults shown as a preview; writing any row creates it.
 */
present: boolean, 
/**
 * Whether the sun/moon are projected as a directional light.
 */
enabled: boolean, 
/**
 * Draw the physically-based sky (LUTs, discs, stars) instead of the
 * three-colour gradient.
 */
physical: boolean, 
/**
 * Linear exposure multiplier on the sky's radiance.
 */
sky_intensity: number, 
/**
 * Aerosol density multiplier over clear air ("turbidity").
 */
turbidity: number, 
/**
 * Mie phase asymmetry `g`, `[-0.95, 0.95]`.
 */
mie_anisotropy: number, 
/**
 * Sun angular **diameter**, degrees (true ≈ 0.53).
 */
sun_disc_deg: number, 
/**
 * Moon angular diameter, degrees.
 */
moon_disc_deg: number, 
/**
 * Starfield brightness multiplier.
 */
star_intensity: number, 
/**
 * Blend back toward the authored gradient, `[0, 1]`.
 */
tint_strength: number, 
/**
 * Aerial-perspective strength on lit geometry (`1` = physical).
 */
aerial_perspective: number, 
/**
 * Height-fog extinction at `fog_height`, **m⁻¹**. `0` = no fog.
 */
fog_density: number, 
/**
 * Height-fog vertical falloff, **m⁻¹**.
 */
fog_falloff: number, 
/**
 * World altitude the fog density applies at, **m**.
 */
fog_height: number, 
/**
 * Draw volumetric clouds. Requires [`physical`](Self::physical).
 */
clouds_enabled: boolean, 
/**
 * Fractional sky coverage, `[0, 1]`.
 */
cloud_coverage: number, 
/**
 * Cloud type, `[0, 1]`: 0 = stratus sheet, 1 = cumulus tower.
 */
cloud_type: number, 
/**
 * Bottom of the cloud layer, **m** of world altitude.
 */
cloud_bottom: number, 
/**
 * Top of the cloud layer, **m**.
 */
cloud_top: number, 
/**
 * Cloud extinction at full density, **m⁻¹**.
 */
cloud_density: number, 
/**
 * Erosion detail strength, `[0, 1]`.
 */
cloud_detail: number, 
/**
 * Field seed (low 24 bits used).
 */
cloud_seed: number, 
/**
 * Wind velocity in world X, **m/s**.
 */
cloud_wind_x: number, 
/**
 * Wind velocity in world Z, **m/s**.
 */
cloud_wind_z: number, 
/**
 * Forward phase asymmetry `g`, `[0, 0.95]`.
 */
cloud_phase_g: number, 
/**
 * How much the layer darkens the sun on the ground, `[0, 1]`.
 */
cloud_shadow: number, 
/**
 * Ambient multiplier inside a cloud, `[0, 4]`.
 */
cloud_ambient: number, };
