// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The level's **physical atmosphere** as the World Settings panel edits it
 * (P17.2) — the sky-authority entity's `inf_ecs::components::SkyAtmosphere`.
 *
 * Like [`TimeOfDayDto`] this is an entity projection, not a file-settings
 * record, and it rides the same [`present`](Self::present) create flag: the two
 * components live on the same authority, so opting into either creates both.
 *
 * **Deliberately numeric-and-boolean only.** `SkyAtmosphere` also carries five
 * `Color` fields (sun, moon, and the three gradient colours); those stay in the
 * reflection Details grid, which already has a colour widget, rather than
 * forcing one into the World Settings property-row kit. Nothing is lost — the
 * panel edits the block a level actually tunes, and Details edits the rest
 * through the same undo door.
 *
 * Units per architecture rule 6: the fog block is **SI metres** (`m⁻¹`
 * extinction and falloff, metre height); the disc sizes are **degrees of
 * angular diameter**; everything else is a dimensionless multiplier over a
 * physical constant that lives in `inf_render::atmosphere`.
 */
export type SkyAtmosphereDto = { 
/**
 * Whether the level has a sky authority at all. `false` ⇒ these are the
 * component defaults shown as a preview; writing any row creates it.
 */
present: boolean, 
/**
 * Whether the sun/moon are projected as a directional light.
 */
enabled: boolean, 
/**
 * Draw the physically-based sky (LUTs, discs, stars) instead of the
 * three-colour gradient.
 */
physical: boolean, 
/**
 * Linear exposure multiplier on the sky's radiance.
 */
sky_intensity: number, 
/**
 * Aerosol density multiplier over clear air ("turbidity").
 */
turbidity: number, 
/**
 * Mie phase asymmetry `g`, `[-0.95, 0.95]`.
 */
mie_anisotropy: number, 
/**
 * Sun angular **diameter**, degrees (true ≈ 0.53).
 */
sun_disc_deg: number, 
/**
 * Moon angular diameter, degrees.
 */
moon_disc_deg: number, 
/**
 * Starfield brightness multiplier.
 */
star_intensity: number, 
/**
 * Blend back toward the authored gradient, `[0, 1]`.
 */
tint_strength: number, 
/**
 * Aerial-perspective strength on lit geometry (`1` = physical).
 */
aerial_perspective: number, 
/**
 * Height-fog extinction at `fog_height`, **m⁻¹**. `0` = no fog.
 */
fog_density: number, 
/**
 * Height-fog vertical falloff, **m⁻¹**.
 */
fog_falloff: number, 
/**
 * World altitude the fog density applies at, **m**.
 */
fog_height: number, };
