// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 2D-mode snapping configuration pushed from the viewport toolbar
 * (`viewport_set_snap2d`). Grid snap quantizes a translate to `grid_size` world
 * units; **pixel snap** (finer) to `1/pixels_per_unit`. Pixel snap wins when
 * both are enabled.
 */
export type Snap2DDto = { grid_enabled: boolean, grid_size: number, pixel_enabled: boolean, pixels_per_unit: number, };
