// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 3D transform-gizmo snap increments (`viewport_set_snap3d`). `translate` is
 * world metres, `rotate_deg` is degrees, `scale` is a ratio step. When
 * `always_on` is false, snapping is Shift-gated (matching the pre-Wave-2 feel).
 */
export type Snap3DDto = { translate: number, rotate_deg: number, scale: number, always_on: boolean, };
