// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One named sorting layer (`layers_get` / `layers_set`). `id` is the raw `i32`
 * the `Sprite.sorting_layer` field stores.
 */
export type SortingLayerDto = { id: number, name: string, };
