// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a dig puts the material it removes (P21.3). Serializes as its tag
 * string.
 */
export type SpoilModeDto = "Off" | "Auto" | "Site";
