// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpriteGridDto } from "./SpriteGridDto";
import type { SpriteRectDto } from "./SpriteRectDto";

/**
 * A texture's full slice model plus its pixel dimensions (`texture_get_slices`;
 * also the payload of `texture_set_slices`, where the dimensions are ignored).
 */
export type SpriteSheetDto = { 
/**
 * The texture asset GUID this model belongs to.
 */
texture_id: string, 
/**
 * Grid definition, or `None` when the sheet is manual-only.
 */
grid: SpriteGridDto | null, 
/**
 * Named manual rectangles.
 */
manual: Array<SpriteRectDto>, 
/**
 * Texture width/height in pixels (read from the payload; drives the overlay).
 */
tex_width: number, tex_height: number, };
