// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The Terrain Import wizard's settings block. Mirrors
 * `inf_editor_core::assets::TerrainImportSettings` and is persisted verbatim
 * into the asset's sidecar, so a reimport re-runs these exact choices.
 *
 * **Metric**: `meters_per_sample`, `min_height` and `max_height` are SI metres
 * (units doctrine). The wizard's kilometre readback is a display division by
 * 1000 and never a stored scale factor.
 */
export type TerrainImportSettingsDto = { tile_resolution: number, meters_per_sample: number, min_height: number, max_height: number, 
/**
 * Take the decoded float as absolute metres (float sources only).
 */
float_meters: boolean, 
/**
 * Straddle the world origin instead of growing into +X/+Z.
 */
center: boolean, max_pyramid_levels: number, min_pyramid_tiles: number, };
