// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The world a given source + settings pair will produce, recomputed on every
 * wizard edit so the extent readback is never stale.
 */
export type TerrainImportPlanDto = { 
/**
 * Real-world span in **metres**.
 */
extent_x_m: number, extent_z_m: number, 
/**
 * Level-0 tiles across / down.
 */
tiles_x: number, tiles_z: number, 
/**
 * Level-0 tiles in total.
 */
tiles: number, };
