// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One painted tile cell (`tilemap_get` output row / `tilemap_paint` input).
 */
export type TilemapCellDto = { x: number, y: number, 
/**
 * 1-based atlas index; `0` erases.
 */
tile: number, };
