// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TilemapCellDto } from "./TilemapCellDto";

/**
 * The selected entity's tilemap, projected for the paint panel (`tilemap_get`).
 */
export type TilemapDto = { 
/**
 * Owning entity GUID.
 */
entity: string, 
/**
 * Atlas texture asset GUID, if one is assigned.
 */
texture: string | null, 
/**
 * World units per tile cell.
 */
tile_width: number, tile_height: number, 
/**
 * Atlas grid the 1-based tile index maps into (tile→UV mapping).
 */
atlas_cols: number, atlas_rows: number, 
/**
 * Palette dimensions: the texture's P8.2a grid slicing when present, else
 * the atlas grid. The palette shows `palette_cols * palette_rows` numbered
 * swatches (indices `1..=count`).
 */
palette_cols: number, palette_rows: number, 
/**
 * Painted cells only (empty cells omitted), in deterministic chunk order.
 */
cells: Array<TilemapCellDto>, };
