// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The level's **time of day** as the World Settings panel edits it (P17.1).
 *
 * Unlike every other block on [`LevelSettingsDto`], this is **not** part of the
 * file-level `LevelSettings` record: the clock lives on an ECS component
 * (`inf_ecs::components::TimeOfDay`) carried by the level's *sky authority*
 * entity, because it has to persist per-entity, animate from Blueprints and key
 * from the sequencer. The panel is a view onto that component, which is why this
 * DTO carries [`present`](Self::present).
 *
 * Units per architecture rule 6: `seconds` is UTC seconds since midnight,
 * angles are degrees, `rate` is a dimensionless multiplier.
 */
export type TimeOfDayDto = { 
/**
 * Whether the level actually has a clock. `false` ⇒ the other fields are the
 * component defaults shown as a preview, and the level renders under the
 * renderer's retired fixed sun. Writing any row creates the authority.
 */
present: boolean, 
/**
 * UTC seconds since midnight, `[0, 86400)`.
 */
seconds: number, 
/**
 * Day of the year, `1..=365` (no leap day; the engine's year is fixed).
 */
day_of_year: number, 
/**
 * Latitude in degrees, `+` north.
 */
latitude_deg: number, 
/**
 * Longitude in degrees, `+` east.
 */
longitude_deg: number, 
/**
 * Simulated clock-seconds per simulated second. `0` freezes the sun.
 */
rate: number, 
/**
 * Read-only sun **altitude** above the horizon, degrees — a live readback so
 * the panel can say "the sun is 34° up" without duplicating the astronomy in
 * TypeScript. Derived, never written back.
 */
sun_elevation_deg: number, 
/**
 * Read-only sun **azimuth**, degrees clockwise from north. Derived.
 */
sun_azimuth_deg: number, };
