// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Active viewport tool (`viewport_set_tool_mode`). Serializes as the tag string
 * `"Select"` / `"Sculpt"`.
 */
export type ToolModeDto = "Select" | "Sculpt" | "Foliage" | "Biome" | "Water";
