// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The viewport hole's rectangle in PHYSICAL pixels relative to the window
 * client area (the frontend multiplies CSS px by `devicePixelRatio`; the
 * backend rounds to device pixels).
 */
export type ViewportRect = { x: number, y: number, width: number, height: number, };
