// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * **A double-click in the native 3D view** (`viewport://activate`, Wave E) —
 * "open this object", the gesture that routes to the Model Editor.
 */
export type ViewportActivateDto = { guid: string, 
/**
 * Stamped by Ring 2, as on [`ViewportContextMenuDto`].
 */
viewport: string, };
