// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * **A right-click in the native 3D view** (`viewport://context-menu`, Wave E).
 *
 * The airspace rule is why this is an event rather than a DOM handler: the
 * viewport is a native child window and swallows pointer events, so a
 * right-click there is not a DOM event and the frontend has no other way to
 * learn of it. `x`/`y` are PHYSICAL pixels relative to the hole's top-left —
 * the same contract [`ViewportDrop`] uses in the other direction, so the
 * frontend converts with `cssX = holeRect.left + x / dpr`.
 */
export type ViewportContextMenuDto = { x: number, y: number, 
/**
 * The entity under the cursor, if the right-click hit one.
 */
guid: string | null, 
/**
 * The selection AFTER the click resolved it (right-clicking an unselected
 * object selects it; right-clicking inside a multi-selection keeps it).
 */
selection: Array<string>, 
/**
 * Which viewport — stamped by Ring 2 on the way out, because the viewport
 * thread does not know its own key (the `ViewportKey` precedent).
 */
viewport: string, };
