// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GizmoModeDto } from "./GizmoModeDto";

/**
 * The `viewport://gizmo` payload (P23.2a): a gizmo-mode echo stamped with the
 * viewport that produced it.
 *
 * A **wrapper** rather than a field, because [`GizmoModeDto`] is an enum and an
 * enum has no tail to add to. The channel used to carry the bare mode; the id
 * is what lets a second viewport echo its own W/E/R without moving the scene
 * viewport's toolbar.
 */
export type ViewportGizmoDto = { mode: GizmoModeDto, 
/**
 * `"primary"` is the scene viewport.
 */
viewport: string, };
