// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The viewport's tool-state notice (`viewport://tool-status`, P16.4).
 *
 * One channel for both halves of the B2 status seam, because they change for
 * the same reason and land in the same corner of the UI: `message` is the
 * one-shot rejection a tool raised (drained from the host's `take_tool_status`)
 * and goes to the status bar; `terrain_streamed` is the standing fact that the
 * projected terrain pages from a `.inf_terrain` and therefore cannot be
 * sculpted yet, and disables the brush tools in the viewport toolbar.
 */
export type ViewportToolStatusDto = { message: string | null, terrain_streamed: boolean, };
