// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A keyboard chord the native viewport forwarded to the webview on
 * `viewport://key`. When the 3D view holds OS focus, WASD/camera keys are
 * consumed natively but global shortcuts (command palette, save, …) are
 * replayed into the frontend keybinding dispatcher (focus handoff, P2.3.4).
 * `chord` matches the frontend's `chordOf` format ("Ctrl+Shift+P", "F11").
 */
export type ViewportKey = { chord: string, };
