// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A drag that ended over the viewport hole. HTML drag ghosts die over the
 * native window (airspace rule), so the drop point crosses via IPC in
 * PHYSICAL pixels relative to the hole's top-left corner.
 */
export type ViewportDrop = { x: number, y: number, 
/**
 * Opaque payload (Phase 4 makes this an asset reference).
 */
payload: string, };
