// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Active viewport projection: perspective 3D or orthographic 2D editing
 * (`viewport_set_mode`). Serializes as the tag string `"Perspective"`/`"TwoD"`.
 */
export type ViewportModeDto = "Perspective" | "TwoD";
