// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Viewport shading view mode (R-P2; `viewport_set_view_mode`). Serializes as the
 * tag string `"Lit"`/`"Unlit"`/`"Wireframe"`/`"Biomes"`/`"VtResidency"`.
 * `Wireframe` degrades to `Unlit` in the renderer when the adapter lacks
 * `POLYGON_MODE_LINE`.
 */
export type ViewModeDto = "Lit" | "Unlit" | "Wireframe" | "Biomes" | "VtResidency";
