// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which cut the [`ToolModeDto::Voxel`] tool makes. Serializes as its tag string.
 *
 * Two sub-modes inside one tool mode rather than two modes — the water tool's
 * precedent — because they share the volume resolution, the surface-crossing
 * verdict, the carve/fill switch and the material. Only how the author
 * describes the path differs.
 */
export type VoxelToolKindDto = "Brush" | "Tunnel";
