// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Carve or fill — which way a voxel cut runs. Serializes as its tag string.
 *
 * Not a boolean: the Ring-0 ops it maps onto are named `Carve` and `Fill`, and
 * a `carve: bool` crossing three layers of IPC is three chances to invert it
 * silently.
 */
export type VoxelOpModeDto = "Carve" | "Fill";
