// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VoxelOpModeDto } from "./VoxelOpModeDto";
import type { VoxelToolKindDto } from "./VoxelToolKindDto";

/**
 * Voxel-tool configuration pushed from the viewport toolbar
 * (`viewport_set_voxel`).
 *
 * SI throughout (architecture rule 6): both lengths are world **metres**.
 */
export type VoxelSettingsDto = { kind: VoxelToolKindDto, 
/**
 * Cut radius — the sphere of a brush dab, the tube radius of a tunnel —
 * metres. One slider, one meaning in both sub-modes.
 */
radius_m: number, 
/**
 * How far below the picked surface the cut's centre sits, metres.
 *
 * This is what makes a tunnel a tunnel. At `0` the cut breaks the ground
 * where the author points (a cave mouth); past the radius it hollows rock
 * with no mouth, which is legal on any terrain because no hole is needed.
 */
depth_m: number, mode: VoxelOpModeDto, 
/**
 * The splat index a **fill** paints; ignored by a carve (an emptied voxel
 * carries no material). A voxel material index IS a terrain splat index,
 * which is what makes a cave wall shade like the hillside it opens out of.
 */
material: number, };
