// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which water body the [`ToolModeDto::Water`] tool places. Serializes as its tag
 * string.
 */
export type WaterToolKindDto = "River" | "Lake";
