// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the water tool suggests for a click at a world point (`water_defaults`) —
 * the P19.2 `BiomeDef::water_hint`'s first reader.
 */
export type WaterDefaultsDto = { 
/**
 * Suggested still-water level, metres of world Y.
 */
level_m: number, 
/**
 * Suggested river width / depth, metres.
 */
river_width_m: number, river_depth_m: number, 
/**
 * Terrain height under the point, or `null` where there is no ground.
 */
ground_m: number | null, 
/**
 * The painted biome id (`0` = unassigned) and its name (empty when none).
 */
biome_id: number, biome_name: string, 
/**
 * Whether `level_m` came from the biome's hint rather than from the ground.
 * The toolbar says which, because "why is my lake at 6.5 m?" should have a
 * visible answer.
 */
from_biome_hint: boolean, };
