// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WaterToolKindDto } from "./WaterToolKindDto";

/**
 * Water tool configuration pushed from the viewport toolbar
 * (`viewport_set_water`).
 *
 * Units are SI throughout (architecture rule 6): metres and m/s. `level_offset_m`
 * is added to whatever level the defaults suggest, so "a lake 2 m above the
 * ground I clicked" needs no arithmetic from the author.
 */
export type WaterSettingsDto = { kind: WaterToolKindDto, 
/**
 * Full width of a new river, metres.
 */
width_m: number, 
/**
 * Depth to the bed of a new river, metres.
 */
depth_m: number, 
/**
 * Surface flow speed of a new river, m/s. Negative reverses it.
 */
flow_m_s: number, 
/**
 * Added to the suggested still-water level, metres.
 */
level_offset_m: number, };
