// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The five named weather states (P17.4), as the panel's preset buttons name
 * them.
 *
 * A DTO twin of [`inf_ecs::components::WeatherPreset`] rather than the type
 * itself, because Ring 0 must not derive `ts_rs::TS` — the same arrangement
 * every other enum on this boundary uses. `rename_all = "lowercase"` makes the
 * generated TypeScript a union of string literals (`"clear" | "overcast" | …`),
 * which is exactly what a row of buttons wants, and it matches
 * [`WeatherPreset::as_str`](inf_ecs::components::WeatherPreset::as_str) so a
 * Blueprint and the panel spell a preset the same way.
 */
export type WeatherPresetDto = "clear" | "overcast" | "storm" | "fog" | "snow";
