// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WeatherPresetDto } from "./WeatherPresetDto";

/**
 * The level's **weather** block (P17.4) — the `weather_*` half of the sky
 * authority's `SkyAtmosphere`.
 *
 * A block of its own rather than more fields on [`SkyAtmosphereDto`], because
 * it is a different question with a different UI: the atmosphere section is a
 * list of physical knobs, while weather is *one coherent state* picked from
 * preset buttons and then, optionally, hand-tuned. Same authority entity, same
 * [`present`](Self::present) create flag.
 *
 * Numeric-and-boolean plus the preset enum: like [`SkyAtmosphereDto`], no
 * `Color` crosses here (the droplet tint is the cloud colour, edited in
 * Details).
 *
 * Units per architecture rule 6: wind **m/s**, fog extinction **m⁻¹** (SI),
 * blend times **seconds**, the rest dimensionless `[0, 1]`.
 */
export type WeatherDto = { 
/**
 * Whether the level has a sky authority at all. `false` ⇒ these are the
 * component defaults shown as a preview; writing any row creates it.
 */
present: boolean, 
/**
 * Whether the weather block **drives** the sky. `false` leaves the authored
 * cloud/fog rows in charge and stops all precipitation.
 */
enabled: boolean, 
/**
 * The preset the live values are blending toward (and equal, once settled).
 */
preset: WeatherPresetDto, 
/**
 * Default transition length, **seconds**, used by the preset buttons and by
 * a `sky.set_weather` that does not say.
 */
blend_seconds: number, 
/**
 * Seconds left in the transition in flight; `0` = settled. Read-only in the
 * panel — it is simulation state, not an authored value.
 */
blend_remaining: number, 
/**
 * Live cloud coverage `[0, 1]`.
 */
coverage: number, 
/**
 * Live cloud type `[0, 1]` (0 = stratus sheet, 1 = cumulus tower).
 */
cloud_type: number, 
/**
 * Live wind in world X, **m/s**.
 */
wind_x: number, 
/**
 * Live wind in world Z, **m/s**.
 */
wind_z: number, 
/**
 * Live height-fog extinction, **m⁻¹**.
 */
fog_density: number, 
/**
 * Live precipitation intensity `[0, 1]`.
 */
precipitation: number, 
/**
 * Live precipitation phase `[0, 1]`: 0 = rain, 1 = snow.
 */
snowiness: number, };
