[package]
name = "inf-anim"
description = "Animation: skeletal runtime, clips, blend spaces, state machines."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish = false

[dependencies]
glam = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
inf-asset = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
