//! **The ALS clip → mode map, and the graph it builds** (wave CHAR1b.1,
//! clause 2).
//!
//! P29 shipped a fourteen-mode movement catalogue, `RotationMode`,
//! turn-in-place rules, blend spaces, inertialization and a state-machine
//! runtime. What it never had was a *graph*: the island's hero — and every
//! committed sample — plays a three-state machine of `idle` / `walk` / `run`
//! generated by the P24 wizard, so eleven of the fourteen modes had no animation
//! at all and the three that did had one clip each and no direction.
//!
//! This module is the other half: a table saying which ALS sequence fills which
//! slot of a locomotion graph, and a builder that turns that table plus a
//! name→clip resolver into a [`StateMachine`].
//!
//! # Names, not assets
//!
//! **ALS-Community is MIT and its assets never enter this checkout.** What is
//! written down here is the *name* of each sequence — a fact about the donor's
//! catalogue, in the same way a port map records a function name — and a
//! resolver hands back whatever GUID the local import gave it. On a machine with
//! no ALS content [`build_locomotion_graph`] answers a graph with the slots it
//! could fill and a list of the ones it could not, which is what lets CI hold a
//! table it has no assets for.
//!
//! # Why a table and not a generator
//!
//! [`crate::locomotion`] *derives* a cycle from a rig, which is the right shape
//! when there is no content. Here there is content: 164 authored sequences whose
//! author decided what a left-forward run looks like. A generator would throw
//! that away. The table's job is to say which is which, once, where a reviewer
//! can read it against the donor's own folder listing.
//!
//! # The mode discriminants live in `inf-ecs` and are mirrored here
//!
//! `inf-anim` is below `inf-ecs` in the ring order and cannot name
//! `MovementMode`. [`LocoMode`] therefore carries the discriminant as a number
//! and `char1b_gate::the_two_mode_tables_agree` holds the two together — the
//! standing law about a table spelled in two crates.

use crate::blend_space::ClipRef;
use crate::blend_space::{BlendEntry2D, BlendSpace2D};
use crate::state_machine::{
    BlendCurve, CmpOp, Motion, SmCompare, SmCond, SmParam, SmState, SmTransition, StateMachine,
};

/// **The state whose blend space is the look/aim sweep** — the three
/// `ALS_N_Look_{U,F,D}_Sweep` sequences, sampled by `inf_ecs::pose`'s additive
/// layer at the aim's own pitch.
///
/// A name and not an index, because a machine a human edited afterwards has
/// different indices and the same names.
pub const LOOK_SWEEP_STATE: &str = "aim_look";
/// The state whose clip is the **breathing additive** (wave CHAR1b.2, carried
/// item 128) — `ALS_N_SecondaryMotion`, layered over the idle through the
/// upper-body mask rather than entered.
pub const BREATH_STATE: &str = "breath";
/// The two states whose clips are the **throw additives** (wave CHAR1b.2) —
/// `INF_Throw_Over` and `INF_Throw_Under`, layered over whatever the character
/// is doing rather than entered, so a grenade can be thrown mid-run.
pub const THROW_OVER_STATE: &str = "throw_over";
/// See [`THROW_OVER_STATE`].
pub const THROW_UNDER_STATE: &str = "throw_under";
/// The state whose clip is the **blind-fire additive** (wave WPN2e) —
/// `INF_Cover_BlindFire`, layered over whatever cover stance the machine is in
/// rather than entered, because a character firing blind is still in cover and a
/// state would replace the stance the shot is taken from.
pub const BLIND_FIRE_STATE: &str = "cover_blind_fire";

/// **The stance overlay every character wears** (wave WPN2b) —
/// `ALS_StanceVariation_Normal`, layered over the idle through the upper-body
/// mask.
///
/// ALS layers a stance variation at ALL times and this engine layered none,
/// which is the CHAR1b.1 audit's own finding: the idle's arms hang wide because
/// nothing was bringing them in. `inf_ecs::pose`'s overlay pass is the reader.
pub const OVERLAY_DEFAULT_STATE: &str = "overlay_default";

/// **The long-gun overlay** (wave WPN2b) — `ALS_Props_M4A1_Poses`, worn by
/// every weapon in the registry whose barrel is not a handgun's.
pub const OVERLAY_M4A1_STATE: &str = "overlay_m4a1";

/// **The two-handed pistol overlay** (wave WPN2b) —
/// `ALS_Props_Pistol_2H_Poses`, worn by the registry's ten handguns.
///
/// Two-handed and not `overlay_pistol_1h`, which is still reachable and still
/// undriven: a modern shooter holds a sidearm with both hands, and the one-handed
/// set is the casual carry an author asks for by name through
/// `CharacterMovement::overlay`.
pub const OVERLAY_PISTOL_2H_STATE: &str = "overlay_pistol_2h";

/// **The long-gun aim sweep** (wave WPN2b) — `ALS_Props_M4A1_Aim_Sweep` and its
/// crouched sample, layered in as the aim-down-sights blend comes up.
pub const AIM_M4A1_STATE: &str = "aim_m4a1";

/// **The two-handed pistol aim sweep** (wave WPN2b).
pub const AIM_PISTOL_2H_STATE: &str = "aim_pistol_2h";

/// **The coordinate a weapon aim sweep's STANDING sample sits at** (wave WPN2b).
///
/// The prop sweeps are two-sample blend spaces — `[0, 0]` standing and
/// `[0, -1]` crouched (see the rows below) — so their second axis is the STANCE
/// and not the pitch, which is what the look sweep's is. Driving one with the
/// other's coordinate would make a character aiming downhill crouch, and that is
/// the reason the two are separate constants rather than one.
pub const WEAPON_SWEEP_STANDING: [f64; 2] = [0.0, 0.0];

/// **The coordinate a weapon aim sweep's CROUCHED sample sits at** (wave WPN2b).
pub const WEAPON_SWEEP_CROUCHED: [f64; 2] = [0.0, -1.0];

/// The blend coordinate the look sweep's **neutral** sits at — the pose the
/// additive delta is measured from.
///
/// `ALS_N_Look_F_Sweep` is the middle sample and is what "looking straight
/// ahead" means, so the delta at that coordinate is exactly zero and a character
/// looking forward is byte-identical to one with no layer at all. That identity
/// is a gate arm.
pub const LOOK_SWEEP_NEUTRAL: [f64; 2] = [0.0, 0.0];

/// The parameter a machine reads for planar ground speed, m/s.
///
/// `inf_ecs::anim_bridge::params::SPEED` by construction, and
/// [`crate::locomotion::SPEED_VAR`] before that: three spellings of one word
/// would leave a character standing still, which is the defect P29.6 already
/// paid for once.
pub const SPEED_VAR: &str = crate::locomotion::SPEED_VAR;
/// The 0–3 gait scale — `inf_ecs::anim_bridge::params::GAIT`.
pub const GAIT_VAR: &str = "gait";
/// The [`LocoMode`] discriminant — `inf_ecs::anim_bridge::params::MODE`.
pub const MODE_VAR: &str = "mode";
/// `1` while the last sweep ended on the ground.
pub const GROUNDED_VAR: &str = "grounded";
/// Downward speed, m/s, positive falling.
pub const FALL_SPEED_VAR: &str = "fall_speed";
/// How close a predicted landing is, `[0, 1]`.
pub const LAND_ALPHA_VAR: &str = "land_alpha";
/// **What the landing classifier decided about the last landing** — the
/// `inf_ecs::components::LandingKind` discriminant.
///
/// The landing states are gated on this and not on [`LAND_ALPHA_VAR`], which is
/// a prediction the movement step CLEARS the moment the character is grounded:
/// a graph that read the prediction could never enter a landing state, because
/// at the instant `grounded` goes true the prediction is already zero. Found by
/// reading the producer rather than by watching a character never land.
pub const LANDING_VAR: &str = "landing";
/// **Seconds since that landing** — how a one-shot landing state knows it is
/// over, and what stops one firing again on the next step.
pub const TIME_SINCE_LAND_VAR: &str = "time_since_land";

/// `LandingKind::Soft` — under the hard threshold, keep running.
pub const LANDING_SOFT: f64 = 1.0;
/// `LandingKind::Hard` — plant, with the heavier braking friction.
pub const LANDING_HARD: f64 = 2.0;
/// `LandingKind::Roll` — a break-fall into a roll.
pub const LANDING_ROLL: f64 = 3.0;
/// How long after a touch a landing state may still be entered, seconds.
pub const LANDING_WINDOW_S: f64 = 0.12;
/// **How far a turn-in-place is turning**, degrees, signed — negative to the
/// character's left. `0` when none is running.
pub const TURN_DEG_VAR: &str = "turn_deg";
/// **Which foot is planted**: `-1` left, `+1` right, `0` neither.
pub const PLANTED_FOOT_VAR: &str = "planted_foot";
/// **Whether a ragdolled character is on its back**, `1` or `0`.
pub const FACE_UP_VAR: &str = "face_up";
/// **Which get-up a ragdoll ends in** (wave CHAR1b.2): `0` none, `1` face down,
/// `2` on its back, `3` still on its feet.
///
/// ALS chooses between its two get-ups by the pelvis's facing and ships only the
/// crouched pair, so a character whose ragdoll settled UPRIGHT — knocked about
/// and never actually floored — had nowhere to go but a get-up off the ground it
/// was not on. The third value is measured, not assumed: the ragdoll bridge has
/// recorded the pelvis's world position since P29.4, and "the pelvis is still
/// more than half a capsule above the feet" is what standing means.
///
/// [`FACE_UP_VAR`] stays published and unchanged; this is the parameter the
/// three get-up edges compare, because a two-valued signal cannot name three
/// outcomes.
///
/// # Why zero is NONE, and not "face down"
///
/// Because this parameter is also **what holds a get-up on the screen**. The
/// `Any → idle` edge exists so that a character in any grounded state with no
/// speed ends up standing; it has priority 5 and no exit time, so it took the
/// machine out of a get-up on the very next step after the get-up was entered —
/// measured on the island, `getup_back` lasted **one fixed step** and the
/// ragdoll then blended out into `idle` instead of into a get-up clip. The edge
/// is guarded on `getup == GETUP_NONE` now, so a running get-up is not cut
/// short, and that guard is only correct if a character that has never
/// ragdolled reads NONE — which is what a `SmParam::float`'s zero default gives
/// for free. Making "face down" the zero would have frozen the `Any → idle`
/// edge shut on every character in the engine.
pub const GETUP_VAR: &str = "getup";
/// [`GETUP_VAR`]'s value when no get-up is running — the declared default.
pub const GETUP_NONE: f64 = 0.0;
/// [`GETUP_VAR`]'s value for a character face down.
pub const GETUP_FRONT: f64 = 1.0;
/// [`GETUP_VAR`]'s value for a character on its back.
pub const GETUP_BACK: f64 = 2.0;
/// [`GETUP_VAR`]'s value for a character that never went down.
pub const GETUP_STANDING: f64 = 3.0;
/// The get-up states, by name — the family the `Any → idle` edge must not cut
/// short, and the family the movement step watches to know when to put
/// [`GETUP_VAR`] back to [`GETUP_NONE`].
pub const GETUP_STATES: [&str; 3] = ["getup_front", "getup_back", "getup_standing"];
/// **Which mantle is running** (wave CHAR1b.2), and which hand leads it.
///
/// `0` none, `1` a low mantle led by the right hand, `2` a low mantle led by the
/// left, `3` a high one. Four values in one parameter rather than two
/// parameters, because ALS's own classification is one enum
/// (`EALSMantleType` — `LowMantle`, `HighMantle`, `FallingCatch`) crossed with
/// `GetMantleAsset(MantleType, CurrentOverlayState)`
/// (`ALSMantleComponent.h:48`), which is where the 1 m clip's LH/RH pair comes
/// from: a character carrying something in its right hand reaches with its left.
pub const MANTLE_VAR: &str = "mantle";
/// [`MANTLE_VAR`]'s value for a low mantle led by the right hand.
pub const MANTLE_LOW_RH: f64 = 1.0;
/// [`MANTLE_VAR`]'s value for a low mantle led by the left hand.
pub const MANTLE_LOW_LH: f64 = 2.0;
/// [`MANTLE_VAR`]'s value for a high mantle.
pub const MANTLE_HIGH: f64 = 3.0;
/// **The clip time a mantle's animation should be entered at**, seconds — ALS's
/// `MantleParams.StartingPosition` (`ALSMantleComponent.cpp:103-108`), which the
/// height remap produces so a 0.6 m ledge and a 1.2 m one can share one clip.
///
/// P29.4 computed it (`inf_anim::HeightRemap::resolve`) and stored it on
/// `MantleState::clip_start_s`, and nothing could consume it because a state
/// machine had no way to enter a state anywhere but at its beginning. The pose
/// step reads it here and hands it to
/// `inf_anim::SmContext::with_entry_offset`.
pub const MANTLE_START_VAR: &str = "mantle_start";

/// Which state [`MANTLE_VAR`]'s value names, or `None` for "no mantle".
///
/// The one place the four values and the three state names are held together,
/// so a reader that needs to go from the parameter back to the row does not
/// re-spell the table.
pub fn mantle_state_name(param: f64) -> Option<&'static str> {
    if param == MANTLE_LOW_RH {
        Some("mantle_low")
    } else if param == MANTLE_LOW_LH {
        Some("mantle_low_lh")
    } else if param == MANTLE_HIGH {
        Some("mantle_high")
    } else {
        None
    }
}
/// **How fast the machine should play its cycle** (wave CHAR1b.2) — ALS's
/// `CalculateStandingPlayRate` (`ALSCharacterAnimInstance.cpp:754-769`).
///
/// The character's own ground speed divided by the speed the blended clip
/// depicts, so a sprint whose clip was authored at 5 m/s and a character
/// travelling at 6.5 m/s plays 1.3x and its feet keep up with the ground. This
/// is **stride warping's** first half: a foot that travels at the capsule's
/// speed does not slide.
pub const PLAY_RATE_VAR: &str = "play_rate";
/// **What class of cover the character is in** (wave COV1): `0` none, `1` low
/// (crouched behind a car or a counter), `2` high (standing against a wall).
///
/// A float and not a state name, which is the CHAR1b.2 law: the door is a MODE
/// plus a PARAMETER. `inf_ecs::cover::CoverClass::param` is the one place the
/// numbers are minted and `from_param` reads them back, so a gate compares
/// against the enum rather than against a literal.
pub const COVER_VAR: &str = "cover";
/// [`COVER_VAR`]'s value for a low (crouched) cover.
pub const COVER_LOW: f64 = 1.0;
/// [`COVER_VAR`]'s value for a high (standing) cover.
pub const COVER_HIGH: f64 = 2.0;
/// **Which way the character is leaning out of cover** (wave COV1): `0` tucked
/// in, `-1` around its left edge, `+1` around its right, `2` over the top.
///
/// Read by the POSE step's additive lean rather than by an edge — a peek is a
/// layer over the cover stance, not a state of its own, for the reason the
/// throws are overlays and not states.
pub const COVER_SIDE_VAR: &str = "cover_side";
/// **How far out that lean is**, `[0, 1]` (wave COV1). The additive's own alpha.
pub const COVER_PEEK_VAR: &str = "cover_peek";
/// **Lean, left/right**, `[-1, 1]` — ALS's `LeanAmount.LR`
/// (`ALSCharacterAnimInstance.cpp:633-637`), positive to the character's right.
pub const LEAN_X_VAR: &str = "lean_x";
/// **Lean, forward/back**, `[-1, 1]` — ALS's `LeanAmount.FB`, positive ahead.
pub const LEAN_Y_VAR: &str = "lean_y";
/// **How far the character will travel before it stops**, metres (wave
/// CHAR1b.2) — the input to distance matching on a stop.
///
/// `v^2 / (2 a)` at the current planar speed and braking deceleration, and `0`
/// while the stick is still pushed. A stop is a DECISION taken while the
/// character is still moving, which is what makes the two stop clips reachable:
/// waiting until the speed has already fallen is waiting until the stop is over.
pub const STOP_DISTANCE_VAR: &str = "stop_distance";
/// The angle at which a turn-in-place is a 180 rather than a 90, degrees.
///
/// Halfway between the two clips the donor ships, so each plays for the turns it
/// is nearer to — ALS picks the same way, off `TurnInPlaceValues`.
pub const TURN_180_DEG: f64 = 135.0;
/// The smallest turn that plays a clip at all, degrees — ALS's
/// `TurnCheckMinAngle`, which `inf_ecs::movement::turn_in_place` already gates
/// the runtime on. Repeated here as the graph's own floor, so a machine driven
/// by a hand-written parameter set behaves like one driven by the movement step.
pub const TURN_MIN_DEG: f64 = 45.0;
/// **The lateral half of the movement direction in the character's own frame**,
/// `[-1, 1]`, positive to its right (wave CHAR1b.1).
///
/// P29 published a four-value `direction` quadrant, which is enough to pick a
/// clip and not enough to *blend* between six of them. A blend space needs a
/// plane, so the movement step publishes one.
pub const MOVE_X_VAR: &str = "move_x";
/// The forward half of the same, positive ahead.
pub const MOVE_Y_VAR: &str = "move_y";

/// The engine movement mode a slot serves.
///
/// The discriminants are `inf_ecs::components::MovementMode`'s, mirrored because
/// the ring order forbids naming it; the gate holds them together.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub enum LocoMode {
    /// Standing locomotion.
    Grounded = 0,
    /// Crouched.
    Crouch = 1,
    /// Prone (wave CHAR1b.2).
    Prone = 2,
    /// A crouch-sprint slide (wave CHAR1b.2).
    Slide = 3,
    /// A roll.
    Roll = 4,
    /// Airborne with full authority — a deliberate jump.
    FallFree = 6,
    /// Airborne with reduced authority — walked off a ledge, or knocked back.
    FallControlled = 7,
    /// Swimming at the surface (wave CHAR1b.2).
    SwimSurface = 8,
    /// Fully submerged (wave CHAR1b.2).
    SwimUnder = 9,
    /// Mantling or vaulting a ledge (wave CHAR1b.2).
    Mantle = 10,
    /// Physics-driven ragdoll.
    Ragdoll = 11,
    /// **Taking cover** behind a surface (wave COV1). Claimed reserved slot 14,
    /// so the number is 14 and not 12 — `Driving` and `Flying` hold 12 and 13
    /// and are not animated by this graph.
    Cover = 14,
}

impl LocoMode {
    /// The `mode` parameter value a machine compares against.
    pub const fn param(self) -> f64 {
        self as u8 as f64
    }
}

/// What kind of thing a slot is, which decides where it is bound.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum SlotKind {
    /// A state of the locomotion graph — the machine plays it.
    State,
    /// A **weapon overlay pose set**, played on the additive layer rather than
    /// by the machine (ALS's own structure: an overlay is a layered blend over
    /// whatever the locomotion graph is doing). Listed here so the map is the
    /// one place a reader looks for "what plays what", and bound by
    /// [`crate::layers`]'s stack rather than by [`build_locomotion_graph`].
    Overlay,
    /// An **aim sweep** — a 2D additive blend space driven by aim yaw and pitch.
    AimSweep,
}

/// One slot of the locomotion graph: a state name, the mode it serves, and the
/// ALS sequences that fill it.
#[derive(Clone, Copy, Debug)]
pub struct LocoSlot {
    /// The machine state's name, or the layer's.
    pub state: &'static str,
    /// The engine mode this slot animates.
    pub mode: LocoMode,
    /// Where it is bound.
    pub kind: SlotKind,
    /// Whether the motion loops (a cycle) or holds its last pose (a one-shot).
    pub looping: bool,
    /// The ALS sequences and their blend coordinates in `(move_x, move_y)`.
    ///
    /// One entry is a single clip; more than one is a [`BlendSpace2D`] over
    /// those coordinates. The coordinates are the donor's own directions:
    /// forward is `+y`, the character's right is `+x`, and a diagonal is the
    /// unit-ish corner ALS authored it at.
    pub clips: &'static [(&'static str, [f64; 2])],
}

/// The forward sample of a direction blend.
const F: [f64; 2] = [0.0, 1.0];
/// Backward.
const B: [f64; 2] = [0.0, -1.0];
/// Left-forward. **On the diamond `|x| + |y| = 1`, not the square**: the
/// movement step publishes ALS's own normalization (`Sum = |X| + |Y|`, so a
/// diagonal is `0.5, 0.5`), and a sample at `(1, 1)` would be a clip the blend
/// could never reach.
const LF: [f64; 2] = [-0.5, 0.5];
/// Right-forward. See [`LF`].
const RF: [f64; 2] = [0.5, 0.5];
/// Left-backward. See [`LF`].
const LB: [f64; 2] = [-0.5, -0.5];
/// Right-backward. See [`LF`].
const RB: [f64; 2] = [0.5, -0.5];
/// Left.
const L: [f64; 2] = [-1.0, 0.0];
/// Right.
const R: [f64; 2] = [1.0, 0.0];
/// The single sample of a clip that is not a direction blend.
const O: [f64; 2] = [0.0, 0.0];

/// **THE MAP** — every slot of the locomotion graph, and the ALS sequence that
/// fills it.
///
/// Only what **ALS ships** is here. The sets it does not have — slide, throwing,
/// swimming, prone, the standing get-up, cover and vault — are authored or
/// sourced content and belong to the next slice; naming them here with no clip
/// would make an unbound row indistinguishable from a missing import, which is
/// exactly what the gate is for.
///
/// The mantle clips (`ALS_N_Mantle_1m_LH/RH`, `_2m`) are ALS's and are
/// deliberately absent: a mantle is a *warped, timeline-driven* traversal rather
/// than a machine state, and the mechanism that plays them is the next slice's.
pub const LOCOMOTION_MAP: &[LocoSlot] = &[
    // ── standing ─────────────────────────────────────────────────────────────
    LocoSlot {
        state: "idle",
        mode: LocoMode::Grounded,
        kind: SlotKind::State,
        looping: true,
        clips: &[("ALS_N_Pose", O)],
    },
    LocoSlot {
        state: "walk",
        mode: LocoMode::Grounded,
        kind: SlotKind::State,
        looping: true,
        clips: &[
            ("ALS_N_Walk_F", F),
            ("ALS_N_Walk_B", B),
            ("ALS_N_Walk_LF", LF),
            ("ALS_N_Walk_RF", RF),
            ("ALS_N_Walk_LB", LB),
            ("ALS_N_Walk_RB", RB),
        ],
    },
    LocoSlot {
        state: "run",
        mode: LocoMode::Grounded,
        kind: SlotKind::State,
        looping: true,
        clips: &[
            ("ALS_N_Run_F", F),
            ("ALS_N_Run_B", B),
            ("ALS_N_Run_LF", LF),
            ("ALS_N_Run_RF", RF),
            ("ALS_N_Run_LB", LB),
            ("ALS_N_Run_RB", RB),
        ],
    },
    LocoSlot {
        state: "sprint",
        mode: LocoMode::Grounded,
        kind: SlotKind::State,
        looping: true,
        clips: &[("ALS_N_Sprint_F", O)],
    },
    // ── stops and starts ─────────────────────────────────────────────────────
    LocoSlot {
        state: "stop_l",
        mode: LocoMode::Grounded,
        kind: SlotKind::State,
        looping: false,
        clips: &[("ALS_N_Stop_L_Down", O)],
    },
    LocoSlot {
        state: "stop_r",
        mode: LocoMode::Grounded,
        kind: SlotKind::State,
        looping: false,
        clips: &[("ALS_N_Stop_R_Down", O)],
    },
    LocoSlot {
        state: "start",
        mode: LocoMode::Grounded,
        kind: SlotKind::State,
        looping: false,
        clips: &[
            ("ALS_N_LocoDetail_Accel_F", F),
            ("ALS_N_LocoDetail_Accel_B", B),
            ("ALS_N_LocoDetail_Accel_L", L),
            ("ALS_N_LocoDetail_Accel_R", R),
        ],
    },
    // ── turn in place ────────────────────────────────────────────────────────
    LocoSlot {
        state: "turn_l90",
        mode: LocoMode::Grounded,
        kind: SlotKind::State,
        looping: false,
        clips: &[("ALS_N_TurnIP_L90", O)],
    },
    LocoSlot {
        state: "turn_r90",
        mode: LocoMode::Grounded,
        kind: SlotKind::State,
        looping: false,
        clips: &[("ALS_N_TurnIP_R90", O)],
    },
    LocoSlot {
        state: "turn_l180",
        mode: LocoMode::Grounded,
        kind: SlotKind::State,
        looping: false,
        clips: &[("ALS_N_TurnIP_L180", O)],
    },
    LocoSlot {
        state: "turn_r180",
        mode: LocoMode::Grounded,
        kind: SlotKind::State,
        looping: false,
        clips: &[("ALS_N_TurnIP_R180", O)],
    },
    // ── crouch ───────────────────────────────────────────────────────────────
    LocoSlot {
        state: "crouch_idle",
        mode: LocoMode::Crouch,
        kind: SlotKind::State,
        looping: true,
        clips: &[("ALS_CLF_Pose", O)],
    },
    LocoSlot {
        state: "crouch_walk",
        mode: LocoMode::Crouch,
        kind: SlotKind::State,
        looping: true,
        clips: &[
            ("ALS_CLF_Walk_F", F),
            ("ALS_CLF_Walk_B", B),
            ("ALS_CLF_Walk_L", L),
            ("ALS_CLF_Walk_R", R),
        ],
    },
    LocoSlot {
        state: "crouch_turn_l90",
        mode: LocoMode::Crouch,
        kind: SlotKind::State,
        looping: false,
        clips: &[("ALS_CLF_TurnIP_L90", O)],
    },
    LocoSlot {
        state: "crouch_turn_r90",
        mode: LocoMode::Crouch,
        kind: SlotKind::State,
        looping: false,
        clips: &[("ALS_CLF_TurnIP_R90", O)],
    },
    LocoSlot {
        state: "crouch_turn_l180",
        mode: LocoMode::Crouch,
        kind: SlotKind::State,
        looping: false,
        clips: &[("ALS_CLF_TurnIP_L180", O)],
    },
    LocoSlot {
        state: "crouch_turn_r180",
        mode: LocoMode::Crouch,
        kind: SlotKind::State,
        looping: false,
        clips: &[("ALS_CLF_TurnIP_R180", O)],
    },
    // ── the air ──────────────────────────────────────────────────────────────
    LocoSlot {
        state: "jump",
        mode: LocoMode::FallFree,
        kind: SlotKind::State,
        looping: true,
        clips: &[("ALS_N_JumpLoop", O)],
    },
    LocoSlot {
        state: "fall",
        mode: LocoMode::FallControlled,
        kind: SlotKind::State,
        looping: true,
        clips: &[("ALS_N_FallLoop", O)],
    },
    LocoSlot {
        state: "fall_fast",
        mode: LocoMode::FallControlled,
        kind: SlotKind::State,
        looping: true,
        clips: &[("ALS_N_FallLoop_Fast", O)],
    },
    LocoSlot {
        state: "land_light",
        mode: LocoMode::Grounded,
        kind: SlotKind::State,
        looping: false,
        clips: &[("ALS_N_Land_Light", O)],
    },
    LocoSlot {
        state: "land_heavy",
        mode: LocoMode::Grounded,
        kind: SlotKind::State,
        looping: false,
        clips: &[("ALS_N_Land_Heavy", O)],
    },
    LocoSlot {
        state: "roll",
        mode: LocoMode::Roll,
        kind: SlotKind::State,
        looping: false,
        clips: &[("ALS_N_LandRoll_F", O)],
    },
    // ── ragdoll ──────────────────────────────────────────────────────────────
    LocoSlot {
        state: "ragdoll",
        mode: LocoMode::Ragdoll,
        kind: SlotKind::State,
        looping: true,
        clips: &[("ALS_Flail", O)],
    },
    LocoSlot {
        state: "getup_front",
        mode: LocoMode::Grounded,
        kind: SlotKind::State,
        looping: false,
        clips: &[("ALS_CLF_GetUp_Front", O)],
    },
    LocoSlot {
        state: "getup_back",
        mode: LocoMode::Grounded,
        kind: SlotKind::State,
        looping: false,
        clips: &[("ALS_CLF_GetUp_Back", O)],
    },
    // ── the mantle (wave CHAR1b.2, clause 5) ─────────────────────────────────
    //
    // A mantle is a **warped, timeline-driven traversal** — `inf_physics`'
    // `try_mantle`/`step_mantle` own the transform and the clock, and the
    // machine owns the pose. Both halves are needed: without a row here the
    // hero climbed a two-metre wall in whatever pose the graph happened to be
    // holding (a jump loop), because `MovementMode::Mantle` matched no state's
    // mode and every `Any` edge in this table asks for a different one.
    //
    // Three rows for ALS's three sequences. `EALSMantleType` splits low from
    // high at a literal 125 cm (`ALSMantleComponent.cpp:282`, ported once as
    // `inf_anim::MANTLE_HIGH_SPLIT_M`); the 1 m pair is ALS's
    // `GetMantleAsset(MantleType, CurrentOverlayState)` (`.h:48`) — a character
    // whose right hand is holding something reaches with its **left**. The
    // engine publishes that choice as [`MANTLE_VAR`], latched at the probe.
    //
    // They are ONE-SHOTS with baked root motion, which is what makes
    // `inf_ecs::traversal_arc` non-empty and what turns `step_mantle`'s warp
    // from a clock ramp into the clip's own arc scaled onto the ledge.
    // ── the AUTHORED sets (wave CHAR1b.2, clause 2's tail) ─────────────────
    //
    // ALS ships none of these — a census by name found no slide, no throw, no
    // swim, no prone and no standing get-up among its 164 sequences — and this
    // engine's catalogue has a MODE for four of them. A mode with no clip is a
    // character sliding in its idle pose, which is what `MovementMode::Slide`,
    // `Prone`, `SwimSurface` and `SwimUnder` all did.
    //
    // `inf_anim::authored` derives them from the rig that will play them, for
    // `crate::locomotion`'s reason (a clip is bound to a skeleton by joint
    // INDEX), and each one's kinematics are written down in that module rather
    // than being a shape somebody liked. The `INF_` prefix is deliberate: these
    // sit beside 164 `ALS_*` files and nothing here is ALS's.
    LocoSlot {
        state: "slide",
        mode: LocoMode::Slide,
        kind: SlotKind::State,
        looping: false,
        clips: &[("INF_Slide", O)],
    },
    LocoSlot {
        state: "prone_idle",
        mode: LocoMode::Prone,
        kind: SlotKind::State,
        looping: true,
        clips: &[("INF_Prone_Idle", O)],
    },
    LocoSlot {
        state: "prone_crawl",
        mode: LocoMode::Prone,
        kind: SlotKind::State,
        looping: true,
        clips: &[("INF_Prone_Crawl", O)],
    },
    LocoSlot {
        state: "swim_surface",
        mode: LocoMode::SwimSurface,
        kind: SlotKind::State,
        looping: true,
        clips: &[("INF_Swim_Surface", O)],
    },
    LocoSlot {
        state: "swim_tread",
        mode: LocoMode::SwimSurface,
        kind: SlotKind::State,
        looping: true,
        clips: &[("INF_Swim_Tread", O)],
    },
    LocoSlot {
        state: "swim_under",
        mode: LocoMode::SwimUnder,
        kind: SlotKind::State,
        looping: true,
        clips: &[("INF_Swim_Under", O)],
    },
    LocoSlot {
        state: "getup_standing",
        mode: LocoMode::Grounded,
        kind: SlotKind::State,
        looping: false,
        clips: &[("INF_GetUp_Standing", O)],
    },
    // The two throws are an upper-body ADDITIVE, not a state: a character throws
    // a grenade while it is running, and a state would stop the run. WPN1's
    // throwable items are their consumer; the layer door is `crate::layers`,
    // exactly as the weapon overlays' is.
    LocoSlot {
        state: "throw_over",
        mode: LocoMode::Grounded,
        kind: SlotKind::Overlay,
        looping: false,
        clips: &[("INF_Throw_Over", O)],
    },
    LocoSlot {
        state: "throw_under",
        mode: LocoMode::Grounded,
        kind: SlotKind::Overlay,
        looping: false,
        clips: &[("INF_Throw_Under", O)],
    },
    // **BLIND FIRE** (wave WPN2e) -- the throws' third sibling, and an overlay
    // for their reason one mode along: a character firing blind is still in
    // cover, still crouched or still standing against its wall, and a STATE
    // would replace the stance the whole shot is taken from. `LocoMode::Cover`
    // rather than `Grounded` because it is only ever played there, which is what
    // makes an inspector reading the map able to see that.
    LocoSlot {
        state: "cover_blind_fire",
        mode: LocoMode::Cover,
        kind: SlotKind::Overlay,
        looping: false,
        clips: &[("INF_Cover_BlindFire", O)],
    },
    // ── the BREATH (wave CHAR1b.2, carried item 128) ────────────────────
    //
    // ALS's idle is `ALS_N_Pose` PLUS a breathing additive, and this sequence is
    // the additive. It was imported at CHAR1a.3 and left unbound because a row
    // with no reader is the defect the CHAR1b.1 audit spent its day on; it has a
    // reader now (`inf_ecs::pose::apply_breath`, over the upper-body mask), so it
    // has a row.
    //
    // An `Overlay` and not a `State`: the machine never ENTERS a breath, it
    // layers one over whatever it is in.
    LocoSlot {
        state: BREATH_STATE,
        mode: LocoMode::Grounded,
        kind: SlotKind::Overlay,
        looping: true,
        clips: &[("ALS_N_SecondaryMotion", O)],
    },
    // ── wave COV1: the cover set ─────────────────────────────────────────────
    //
    // Four authored clips, a stance and a move per class. ALS ships no cover
    // sequence at all (the CHAR1a census by name), so `inf_anim::authored`
    // derives these from the rig that will play them exactly as it derives the
    // slide and the swims — and the `INF_` prefix says whose they are.
    LocoSlot {
        state: "cover_low_idle",
        mode: LocoMode::Cover,
        kind: SlotKind::State,
        looping: true,
        clips: &[("INF_Cover_Low_Idle", O)],
    },
    LocoSlot {
        state: "cover_low_move",
        mode: LocoMode::Cover,
        kind: SlotKind::State,
        looping: true,
        clips: &[("INF_Cover_Low_Move", O)],
    },
    LocoSlot {
        state: "cover_high_idle",
        mode: LocoMode::Cover,
        kind: SlotKind::State,
        looping: true,
        clips: &[("INF_Cover_High_Idle", O)],
    },
    LocoSlot {
        state: "cover_high_move",
        mode: LocoMode::Cover,
        kind: SlotKind::State,
        looping: true,
        clips: &[("INF_Cover_High_Move", O)],
    },
    LocoSlot {
        state: "mantle_low",
        mode: LocoMode::Mantle,
        kind: SlotKind::State,
        looping: false,
        clips: &[("ALS_N_Mantle_1m_RH", O)],
    },
    LocoSlot {
        state: "mantle_low_lh",
        mode: LocoMode::Mantle,
        kind: SlotKind::State,
        looping: false,
        clips: &[("ALS_N_Mantle_1m_LH", O)],
    },
    LocoSlot {
        state: "mantle_high",
        mode: LocoMode::Mantle,
        kind: SlotKind::State,
        looping: false,
        clips: &[("ALS_N_Mantle_2m", O)],
    },
    // ── the STANCE overlays (audit CHAR1b.1) ─────────────────────────────────
    //
    // ALS's overlay state machine has one state per `EALSOverlayState`, and the
    // enum's first five — `Default`, `Masculine`, `Feminine`, `Injured`,
    // `HandsTied` (`ALSCharacterEnumLibrary.h:65-80`) — are served by the five
    // `ALS_StanceVariation_*` sequences, not by a prop pose set. The map named
    // the eight prop overlays and none of these, which left a **shipped set**
    // unbound and made an unbound row indistinguishable from a missing import,
    // the very thing clause 2's rule exists to prevent.
    //
    // Inert exactly as the weapon overlays are, and for the same reason: nothing
    // drives an overlay stack yet (WPN1's), so a row here is a name the layer
    // door can resolve and one `SmState` in the file.
    //
    // **`Default` is not why the hero's arms hang wide** — that was measured, not
    // assumed. On the donor's own rig `ALS_N_Pose` holds the upper arms at
    // **13.59°** from vertical and `ALS_StanceVariation_Normal` at
    // **14.82°/14.46°**, so layering the default overlay moves the arms OUT by
    // about a degree. The wide arms were a clip bound to the wrong rig; see
    // `ue_import::rebind_locomotion_graph`.
    LocoSlot {
        state: OVERLAY_DEFAULT_STATE,
        mode: LocoMode::Grounded,
        kind: SlotKind::Overlay,
        looping: false,
        clips: &[("ALS_StanceVariation_Normal", O)],
    },
    LocoSlot {
        state: "overlay_masculine",
        mode: LocoMode::Grounded,
        kind: SlotKind::Overlay,
        looping: false,
        clips: &[("ALS_StanceVariation_Masculine", O)],
    },
    LocoSlot {
        state: "overlay_feminine",
        mode: LocoMode::Grounded,
        kind: SlotKind::Overlay,
        looping: false,
        clips: &[("ALS_StanceVariation_Feminine", O)],
    },
    LocoSlot {
        state: "overlay_injured",
        mode: LocoMode::Grounded,
        kind: SlotKind::Overlay,
        looping: false,
        clips: &[("ALS_StanceVariation_Injured", O)],
    },
    LocoSlot {
        state: "overlay_hands_tied",
        mode: LocoMode::Grounded,
        kind: SlotKind::Overlay,
        looping: false,
        clips: &[("ALS_StanceVariation_HandsTied", O)],
    },
    // ── the weapon overlays (WPN1's items; the additive layer plays them) ─────
    LocoSlot {
        state: OVERLAY_M4A1_STATE,
        mode: LocoMode::Grounded,
        kind: SlotKind::Overlay,
        looping: false,
        clips: &[("ALS_Props_M4A1_Poses", O)],
    },
    LocoSlot {
        state: "overlay_pistol_1h",
        mode: LocoMode::Grounded,
        kind: SlotKind::Overlay,
        looping: false,
        clips: &[("ALS_Props_Pistol_1H_Poses", O)],
    },
    LocoSlot {
        state: OVERLAY_PISTOL_2H_STATE,
        mode: LocoMode::Grounded,
        kind: SlotKind::Overlay,
        looping: false,
        clips: &[("ALS_Props_Pistol_2H_Poses", O)],
    },
    LocoSlot {
        state: "overlay_bow",
        mode: LocoMode::Grounded,
        kind: SlotKind::Overlay,
        looping: false,
        clips: &[("ALS_Props_Bow_Poses", O)],
    },
    LocoSlot {
        state: "overlay_torch",
        mode: LocoMode::Grounded,
        kind: SlotKind::Overlay,
        looping: false,
        clips: &[("ALS_Props_Torch_Poses", O)],
    },
    LocoSlot {
        state: "overlay_binoculars",
        mode: LocoMode::Grounded,
        kind: SlotKind::Overlay,
        looping: false,
        clips: &[("ALS_Props_Binoculars_Poses", O)],
    },
    LocoSlot {
        state: "overlay_box",
        mode: LocoMode::Grounded,
        kind: SlotKind::Overlay,
        looping: false,
        clips: &[("ALS_Props_Box_Poses", O)],
    },
    LocoSlot {
        state: "overlay_barrel",
        mode: LocoMode::Grounded,
        kind: SlotKind::Overlay,
        looping: false,
        clips: &[("ALS_Props_Barrel_Poses", O)],
    },
    // ── the aim sweeps (the additive layer's 2D blend spaces) ────────────────
    LocoSlot {
        state: "aim_look",
        mode: LocoMode::Grounded,
        kind: SlotKind::AimSweep,
        looping: false,
        clips: &[
            ("ALS_N_Look_U_Sweep", [0.0, 1.0]),
            ("ALS_N_Look_F_Sweep", [0.0, 0.0]),
            ("ALS_N_Look_D_Sweep", [0.0, -1.0]),
        ],
    },
    LocoSlot {
        state: AIM_M4A1_STATE,
        mode: LocoMode::Grounded,
        kind: SlotKind::AimSweep,
        looping: false,
        clips: &[
            ("ALS_Props_M4A1_Aim_Sweep", [0.0, 0.0]),
            ("ALS_Props_M4A1_Aim_Sweep_Crouched", [0.0, -1.0]),
        ],
    },
    LocoSlot {
        state: "aim_pistol_1h",
        mode: LocoMode::Grounded,
        kind: SlotKind::AimSweep,
        looping: false,
        clips: &[
            ("ALS_Props_Pistol_1H_Aim_Sweep", [0.0, 0.0]),
            ("ALS_Props_Pistol_1H_Aim_Sweep_Crouched", [0.0, -1.0]),
        ],
    },
    LocoSlot {
        state: AIM_PISTOL_2H_STATE,
        mode: LocoMode::Grounded,
        kind: SlotKind::AimSweep,
        looping: false,
        clips: &[
            ("ALS_Props_Pistol_2H_Aim_Sweep", [0.0, 0.0]),
            ("ALS_Props_Pistol_2H_Aim_Sweep_Crouched", [0.0, -1.0]),
        ],
    },
    LocoSlot {
        state: "aim_bow",
        mode: LocoMode::Grounded,
        kind: SlotKind::AimSweep,
        looping: false,
        clips: &[
            ("ALS_Props_Bow_Aim_Sweep", [0.0, 0.0]),
            ("ALS_Props_Bow_Aim_Sweep_Crouched", [0.0, -1.0]),
        ],
    },
    LocoSlot {
        state: "aim_torch",
        mode: LocoMode::Grounded,
        kind: SlotKind::AimSweep,
        looping: false,
        clips: &[
            ("ALS_Props_Torch_Aim_Sweep", [0.0, 0.0]),
            ("ALS_Props_Torch_Aim_Sweep_Crouched", [0.0, -1.0]),
        ],
    },
    LocoSlot {
        state: "aim_binoculars",
        mode: LocoMode::Grounded,
        kind: SlotKind::AimSweep,
        looping: false,
        clips: &[
            ("ALS_Props_Binoculars_Aim_Sweep", [0.0, 0.0]),
            ("ALS_Props_Binoculars_Aim_Sweep_Crouched", [0.0, -1.0]),
        ],
    },
];

/// What [`build_locomotion_graph`] managed to bind.
#[derive(Clone, Debug, Default, PartialEq)]
pub struct LocoBindReport {
    /// `(state, clip name)` for every clip that resolved, in table order.
    pub bound: Vec<(String, String)>,
    /// `(state, clip name)` for every clip that did not.
    pub unbound: Vec<(String, String)>,
    /// States that ended up in the graph.
    pub states: Vec<String>,
    /// States the table names that could not be built at all, because **none**
    /// of their clips resolved.
    pub missing_states: Vec<String>,
}

impl LocoBindReport {
    /// Whether every clip the table names resolved.
    pub fn is_complete(&self) -> bool {
        self.unbound.is_empty()
    }

    /// A one-line summary for an import advisory.
    pub fn summary(&self) -> String {
        format!(
            "{} states, {} clips bound, {} unbound{}",
            self.states.len(),
            self.bound.len(),
            self.unbound.len(),
            if self.missing_states.is_empty() {
                String::new()
            } else {
                format!(" ({} states unfilled)", self.missing_states.len())
            }
        )
    }
}

/// **Build the locomotion graph** from [`LOCOMOTION_MAP`] and a name→clip
/// resolver.
///
/// **Every** row becomes a state, including the overlays and the aim sweeps —
/// and those two families have **no transitions into them**, deliberately.
///
/// A `.inf_sm` is the one asset a character carries that names clips, and the
/// additive layer needs to name some too: an aim offset is three sequences and a
/// weapon overlay is one, and neither is a thing the machine ever *enters*. The
/// alternatives were a second asset kind (a schema, for one `Vec` of GUIDs) or a
/// runtime table nobody could author. So the machine is the character's
/// **animation manifest**, an unreachable state is a named clip set, and
/// `inf_ecs::pose` reads the look sweep off [`LOOK_SWEEP_STATE`] by name. UE's
/// own anim graphs hold their aim offsets exactly this way — as a node in the
/// graph that the state machine does not route through.
///
/// An unreachable state costs one `SmState` in the file and nothing at runtime:
/// `SmRuntime` can only be in a state something transitioned it into.
///
/// A state whose clips all fail to resolve is **left out** rather than pointed at
/// a null GUID: a state that plays nothing is a T-pose with a name, and the
/// report says which ones went. A state whose clips *partly* resolve keeps the
/// samples it has, because a five-sample direction blend is a worse walk and not
/// a broken one.
///
/// The entry state is `idle` when it exists and the first state otherwise.
pub fn build_locomotion_graph(
    resolve: &dyn Fn(&str) -> Option<ClipRef>,
) -> (StateMachine, LocoBindReport) {
    let mut report = LocoBindReport::default();
    let mut states: Vec<SmState> = Vec::new();
    let mut index: std::collections::BTreeMap<&'static str, usize> =
        std::collections::BTreeMap::new();

    for slot in LOCOMOTION_MAP {
        let mut got: Vec<BlendEntry2D> = Vec::new();
        for (name, pos) in slot.clips {
            match resolve(name) {
                Some(clip) => {
                    report.bound.push((slot.state.into(), (*name).into()));
                    got.push(BlendEntry2D { pos: *pos, clip });
                }
                None => report.unbound.push((slot.state.into(), (*name).into())),
            }
        }
        if got.is_empty() {
            report.missing_states.push(slot.state.into());
            continue;
        }
        let motion = if got.len() == 1 {
            Motion::Clip(got[0].clip)
        } else {
            Motion::Blend2D(BlendSpace2D::new(MOVE_X_VAR, MOVE_Y_VAR, got))
        };
        index.insert(slot.state, states.len());
        // The canvas position is the table's own order, laid out in rows of
        // four: an authored graph a human opens should not be a pile at 0,0.
        let n = states.len();
        states.push(SmState {
            name: slot.state.into(),
            motion,
            looping: slot.looping,
            speed: 1.0,
            position: ((n % 4) as f32 * 260.0, (n / 4) as f32 * 180.0),
            on_enter: Vec::new(),
            on_exit: Vec::new(),
        });
        report.states.push(slot.state.into());
    }

    let transitions = transitions_for(&index);
    let entry = index.get("idle").copied().unwrap_or(0);
    (
        StateMachine {
            states,
            transitions,
            entry,
            params: vec![
                SmParam::float(SPEED_VAR),
                SmParam::float(GAIT_VAR),
                SmParam::float(MODE_VAR),
                SmParam::float(GROUNDED_VAR),
                SmParam::float(FALL_SPEED_VAR),
                SmParam::float(LAND_ALPHA_VAR),
                SmParam::float(LANDING_VAR),
                SmParam::float(TIME_SINCE_LAND_VAR),
                SmParam::float(MOVE_X_VAR),
                SmParam::float(MOVE_Y_VAR),
                SmParam::float(TURN_DEG_VAR),
                SmParam::float(PLANTED_FOOT_VAR),
                SmParam::float(FACE_UP_VAR),
                // ── wave CHAR1b.2 ────────────────────────────────────────
                SmParam::float(MANTLE_VAR),
                SmParam::float(MANTLE_START_VAR),
                SmParam::float(GETUP_VAR),
                SmParam::float(STOP_DISTANCE_VAR),
                // Declared but read by the POSE step rather than by an edge:
                // a `.inf_sm` is the character's animation manifest (see this
                // function's own docs), and a parameter a consumer reads is
                // part of it whether or not a transition compares against it.
                SmParam::float(PLAY_RATE_VAR),
                SmParam::float(LEAN_X_VAR),
                SmParam::float(LEAN_Y_VAR),
                // ── wave COV1 ────────────────────────────────────────────
                //
                // The class is compared by an EDGE; the side and the peek are
                // read by the pose step's additive lean, and are declared for
                // `PLAY_RATE_VAR`'s reason — the machine is the character's
                // animation manifest.
                SmParam::float(COVER_VAR),
                SmParam::float(COVER_SIDE_VAR),
                SmParam::float(COVER_PEEK_VAR),
            ],
            profiles: Vec::new(),
        },
        report,
    )
}

/// The gait thresholds the graph switches on, m/s.
///
/// `GAIT_VAR` is the 0–3 scale, so these are its own boundaries and not speeds:
/// 1 is walk, 2 run, 3 sprint ([`crate::derive::gait_of`]). Switching on the
/// *scale* rather than on metres per second is what lets one graph serve a
/// 1.6 m character and a 2.0 m one.
const WALK_AT: f64 = 0.1;
/// See [`WALK_AT`].
const RUN_AT: f64 = 1.5;
/// See [`WALK_AT`].
const SPRINT_AT: f64 = 2.5;

/// **The shortest stopping distance worth playing a stop clip across**, metres.
///
/// Below it the character is already where it is going to end up and a stop
/// one-shot would be a pose change rather than a movement — which is what the
/// `Any -> idle` edge is for. A walk released at 1.5 m/s against the default
/// braking curve has about 14 cm of travel left, so this is set under that: the
/// two stop clips serve a released walk as well as a released sprint, which is
/// what ALS uses them for.
const STOP_MIN_M: f64 = 0.10;

/// The cross-fade every locomotion edge uses, seconds.
///
/// ALS's own `Blend Time` on the cycle-blending layers. Long enough to hide the
/// pose discontinuity between two cadences, short enough that the character is
/// not still blending when the player has let go of the stick.
const FADE_S: f64 = 0.15;
/// The fade into and out of an action (a land, a turn, a get-up), which is
/// shorter because an action's first frame is its statement.
const ACTION_FADE_S: f64 = 0.08;

/// Every edge of the graph, over whichever states exist.
///
/// Written as a table over *names* and filtered to the states that were built,
/// so a project with no crouch set gets a graph with no crouch edges rather than
/// a machine that fails `validate`.
fn transitions_for(index: &std::collections::BTreeMap<&'static str, usize>) -> Vec<SmTransition> {
    let mut out = Vec::new();
    let at = |n: &str| index.get(n).copied();

    // ── the gait ladder, inside `Grounded` ───────────────────────────────────
    //
    // Each pair of conditions is an exact complement on the same constant, so
    // the machine cannot chatter and needs no hysteresis band — the rule
    // `locomotion_machine` established at P24.5 and the reason there is no
    // idle→run edge: one fixed step of latency through `walk` buys four edges
    // instead of six.
    let ladder = [
        ("idle", "walk", WALK_AT),
        ("walk", "run", RUN_AT),
        ("run", "sprint", SPRINT_AT),
    ];
    for (lo, hi, at_gait) in ladder {
        if let (Some(a), Some(b)) = (at(lo), at(hi)) {
            out.push(
                SmTransition::on(a, b, FADE_S, GAIT_VAR, CmpOp::Gt, at_gait)
                    .with_curve(BlendCurve::EaseInOut)
                    .when(SmCond::from_flat_and(vec![
                        SmCompare::float(GAIT_VAR, CmpOp::Gt, at_gait),
                        SmCompare::float(MODE_VAR, CmpOp::Eq, LocoMode::Grounded.param()),
                    ])),
            );
            out.push(
                SmTransition::on(b, a, FADE_S, GAIT_VAR, CmpOp::Le, at_gait)
                    .with_curve(BlendCurve::EaseInOut),
            );
        }
    }

    // ── the START, between standing still and walking ───────────────────────
    //
    // ALS's `LocoDetail_Accel_*` is what a character does in its first stride,
    // and it is a one-shot: `idle → start → walk`, with the start priced above
    // the ladder's own `idle → walk` edge so it is not skipped.
    if let (Some(i), Some(st)) = (at("idle"), at("start")) {
        out.push(
            SmTransition::on(i, st, ACTION_FADE_S, GAIT_VAR, CmpOp::Gt, WALK_AT)
                .with_curve(BlendCurve::EaseInOut)
                .with_priority(2),
        );
        if let Some(w) = at("walk") {
            out.push(
                SmTransition::new(st, w, FADE_S)
                    .with_exit_time(0.6)
                    .with_curve(BlendCurve::EaseInOut),
            );
            // …and a start that is abandoned goes back rather than finishing.
            out.push(
                SmTransition::on(st, i, FADE_S, GAIT_VAR, CmpOp::Le, WALK_AT)
                    .with_curve(BlendCurve::EaseInOut)
                    .with_priority(3),
            );
        }
    }

    // ── the STOP, and which foot it is on ───────────────────────────────────
    //
    // ALS ships two stop-down clips because which foot is under you when you
    // stop decides what stopping looks like. The engine publishes the animator's
    // own `FootLock_*` window as `planted_foot`, so the choice is the CLIP's and
    // not this table's; a cycle that authors neither lock takes neither stop and
    // falls through to `idle`, which is the pre-CHAR1b behaviour.
    for (name, foot) in [("stop_l", -0.5), ("stop_r", 0.5)] {
        let Some(st) = at(name) else { continue };
        for from in ["walk", "run", "sprint"] {
            let Some(f) = at(from) else { continue };
            let cmp = if foot < 0.0 { CmpOp::Lt } else { CmpOp::Gt };
            out.push(
                SmTransition::new(f, st, ACTION_FADE_S)
                    .when(SmCond::from_flat_and(vec![
                        // **DISTANCE MATCHING** (wave CHAR1b.2, clause 6).
                        //
                        // This condition was `gait <= 0.1` — *the character has
                        // already almost stopped* — and the CHAR1b.1 audit
                        // measured the whole precondition holding on **0 steps**
                        // of five run-and-stops at five phases plus a sprint
                        // stop. It could not have held often: by the time the
                        // gait scale has fallen below the walk threshold the
                        // cycle has faded, the foot locks have gone with it, and
                        // there is no stopping distance left to play a stop
                        // across.
                        //
                        // A stop is a decision taken WHILE MOVING, and the thing
                        // it is taken on is how far there is left to travel:
                        // `stop_distance` is `v^2 / 2a` and is exactly zero while
                        // the stick is pushed, so this fires on the release and
                        // the clip is then played at the rate that lands its own
                        // travel on that distance (`stride_play_rate`, which
                        // matches the clip's depicted ground speed to the
                        // character's on every step of the deceleration).
                        SmCompare::float(STOP_DISTANCE_VAR, CmpOp::Gt, STOP_MIN_M),
                        SmCompare::float(PLANTED_FOOT_VAR, cmp, foot),
                        SmCompare::float(MODE_VAR, CmpOp::Eq, LocoMode::Grounded.param()),
                    ]))
                    .with_curve(BlendCurve::EaseInOut)
                    .with_priority(6),
            );
        }
        if let Some(i) = at("idle") {
            // **The stop ends when the CHARACTER stops, not when the clip runs
            // out.** `ALS_N_Stop_*_Down` is 2.333 s and a braking character comes
            // to rest in about half of that, so an exit-time edge alone left the
            // hero holding a decelerating pose for a second after it had already
            // stopped — measured on the island at a **114.966 mm p50** foot
            // residual across `stop_l`, against 0.000 in every other state,
            // because the clip's planted foot and the ground under the
            // stationary character had stopped agreeing.
            //
            // `stop_distance` is zero both while the stick is pushed and once the
            // speed has gone; the gait separates them.
            out.push(
                SmTransition::new(st, i, FADE_S)
                    .when(SmCond::from_flat_and(vec![
                        SmCompare::float(GAIT_VAR, CmpOp::Le, WALK_AT),
                        SmCompare::float(STOP_DISTANCE_VAR, CmpOp::Le, 0.0),
                    ]))
                    .with_curve(BlendCurve::EaseInOut)
                    .with_priority(5),
            );
            // …and the clip running out is still a way home, for a stop nothing
            // else releases.
            out.push(
                SmTransition::new(st, i, FADE_S)
                    .with_exit_time(0.7)
                    .with_curve(BlendCurve::EaseInOut),
            );
        }
        // …and a stop the player changes their mind about goes back to the
        // ladder rather than finishing. Above the exit-time edge, because a
        // stick pushed again is an instruction and a clip running out is not.
        //
        // **AND THE STICK MUST ACTUALLY BE PUSHED.** `stop_distance` is exactly
        // zero while there is movement input and positive while the character is
        // braking, so `> WALK_AT` alone is true for the whole of a stop — the
        // character is still travelling, which is the point — and the two edges
        // chatter: walk -> stop -> walk -> stop, once every few steps. Measured
        // before this term: **226 transitions over a 1 102-step tour**, one every
        // 4.9 steps, and a post-transition p99 of 44.008 deg against the gait's
        // own 19.866.
        if let Some(w) = at("walk") {
            out.push(
                SmTransition::new(st, w, FADE_S)
                    .when(SmCond::from_flat_and(vec![
                        SmCompare::float(GAIT_VAR, CmpOp::Gt, WALK_AT),
                        SmCompare::float(STOP_DISTANCE_VAR, CmpOp::Le, 0.0),
                    ]))
                    .with_curve(BlendCurve::EaseInOut)
                    .with_priority(4),
            );
        }
    }

    // ── TURN IN PLACE ───────────────────────────────────────────────────────
    //
    // P29.4 ported ALS's whole rule set — the delay, the two thresholds, the
    // aim-yaw-rate limit — onto the runtime, and the eight clips crossed the
    // bridge, and no machine could see that a turn was happening. `turn_deg` is
    // the seam: signed, and zero when no turn is running.
    for (stand, crouch, lo, hi, left) in [
        (
            "turn_l90",
            "crouch_turn_l90",
            TURN_MIN_DEG,
            TURN_180_DEG,
            true,
        ),
        (
            "turn_r90",
            "crouch_turn_r90",
            TURN_MIN_DEG,
            TURN_180_DEG,
            false,
        ),
        ("turn_l180", "crouch_turn_l180", TURN_180_DEG, 360.0, true),
        ("turn_r180", "crouch_turn_r180", TURN_180_DEG, 360.0, false),
    ] {
        for (name, from, mode) in [
            (stand, "idle", LocoMode::Grounded),
            (crouch, "crouch_idle", LocoMode::Crouch),
        ] {
            let (Some(to), Some(f)) = (at(name), at(from)) else {
                continue;
            };
            let terms = if left {
                vec![
                    SmCompare::float(TURN_DEG_VAR, CmpOp::Lt, -lo),
                    SmCompare::float(TURN_DEG_VAR, CmpOp::Ge, -hi),
                    SmCompare::float(MODE_VAR, CmpOp::Eq, mode.param()),
                ]
            } else {
                vec![
                    SmCompare::float(TURN_DEG_VAR, CmpOp::Gt, lo),
                    SmCompare::float(TURN_DEG_VAR, CmpOp::Le, hi),
                    SmCompare::float(MODE_VAR, CmpOp::Eq, mode.param()),
                ]
            };
            out.push(
                SmTransition::new(f, to, ACTION_FADE_S)
                    .when(SmCond::from_flat_and(terms))
                    .with_curve(BlendCurve::EaseInOut)
                    // Above the `Any -> idle` / `Any -> crouch_idle` edges, so a
                    // turn is not a race the stance edge wins on some steps.
                    .with_priority(7),
            );
            // A turn plays out and hands back to the stance it came from.
            out.push(
                SmTransition::new(to, f, FADE_S)
                    .with_exit_time(0.9)
                    .with_curve(BlendCurve::EaseInOut),
            );
        }
    }

    // ── crouch: the whole standing family drops into it, and back ────────────
    if let Some(c) = at("crouch_idle") {
        out.push(
            SmTransition::any(c, FADE_S)
                .when(SmCond::from_flat_and(vec![
                    SmCompare::float(MODE_VAR, CmpOp::Eq, LocoMode::Crouch.param()),
                    // **AND STILL** — without this the `Any` edge outvotes the
                    // crouch ladder every step and `crouch_walk` is unreachable,
                    // which is what the reachability arm caught. The same shape
                    // as the `idle` edge below, for the same reason.
                    SmCompare::float(GAIT_VAR, CmpOp::Le, WALK_AT),
                ]))
                .with_curve(BlendCurve::EaseInOut)
                // Below the mode edges below, so an airborne character does not
                // crouch on the way past.
                .with_priority(10),
        );
    }
    if let (Some(ci), Some(cw)) = (at("crouch_idle"), at("crouch_walk")) {
        out.push(
            SmTransition::on(ci, cw, FADE_S, GAIT_VAR, CmpOp::Gt, WALK_AT)
                .with_curve(BlendCurve::EaseInOut),
        );
        out.push(
            SmTransition::on(cw, ci, FADE_S, GAIT_VAR, CmpOp::Le, WALK_AT)
                .with_curve(BlendCurve::EaseInOut),
        );
    }
    if let Some(i) = at("idle") {
        out.push(
            SmTransition::any(i, FADE_S)
                .when(SmCond::from_flat_and(vec![
                    SmCompare::float(MODE_VAR, CmpOp::Eq, LocoMode::Grounded.param()),
                    SmCompare::float(GROUNDED_VAR, CmpOp::Gt, 0.5),
                    SmCompare::float(GAIT_VAR, CmpOp::Le, WALK_AT),
                    // **…AND NO GET-UP IS RUNNING** (wave CHAR1b.2).
                    //
                    // `SmSource::Any` excludes the state the machine is in, so
                    // an action state cannot hold itself by re-entry: the step
                    // after a get-up is entered, this edge is the only eligible
                    // one and it fires. Measured on the island: `getup_back`
                    // lasted exactly **one fixed step**, and the ragdoll's
                    // 0.35 s blend then interpolated a heap on the ground into a
                    // standing idle — 386.5 mm on one joint in one step, which
                    // is the largest reading this wave took anywhere.
                    //
                    // The guard is a parameter rather than a state list because
                    // that is the vocabulary an edge has. It costs nothing on a
                    // character that has never ragdolled: `getup` is a declared
                    // float and its default is `GETUP_NONE`.
                    SmCompare::float(GETUP_VAR, CmpOp::Lt, GETUP_FRONT),
                ]))
                .with_curve(BlendCurve::EaseInOut)
                .with_priority(5),
        );
    }

    // ── the air ──────────────────────────────────────────────────────────────
    for (name, mode) in [
        ("jump", LocoMode::FallFree),
        ("fall", LocoMode::FallControlled),
    ] {
        if let Some(s) = at(name) {
            let mut terms = vec![SmCompare::float(MODE_VAR, CmpOp::Eq, mode.param())];
            if name == "fall" {
                // **AND SLOWLY** — the `Any` edge would otherwise outvote the
                // `fall → fall_fast` edge below on every step and the fast loop
                // would be unreachable. Caught by the reachability arm.
                terms.push(SmCompare::float(FALL_SPEED_VAR, CmpOp::Le, 9.0));
            }
            out.push(
                SmTransition::any(s, ACTION_FADE_S)
                    .when(SmCond::from_flat_and(terms))
                    .with_curve(BlendCurve::EaseInOut)
                    .with_priority(20),
            );
        }
    }
    // A long fall speeds up: ALS swaps `FallLoop` for `FallLoop_Fast`.
    if let (Some(f), Some(ff)) = (at("fall"), at("fall_fast")) {
        out.push(
            SmTransition::on(f, ff, FADE_S, FALL_SPEED_VAR, CmpOp::Gt, 9.0)
                .with_curve(BlendCurve::EaseInOut),
        );
        out.push(
            SmTransition::on(ff, f, FADE_S, FALL_SPEED_VAR, CmpOp::Le, 9.0)
                .with_curve(BlendCurve::EaseInOut),
        );
    }
    // **The landing**, taken off the classifier's LATCH inside a short window
    // after the touch — see [`LANDING_VAR`] for why not off the prediction.
    for (name, kind, prio) in [
        ("land_light", LANDING_SOFT, 30),
        ("land_heavy", LANDING_HARD, 31),
    ] {
        if let Some(s) = at(name) {
            out.push(
                SmTransition::any(s, ACTION_FADE_S)
                    .when(SmCond::from_flat_and(vec![
                        SmCompare::float(GROUNDED_VAR, CmpOp::Gt, 0.5),
                        SmCompare::float(LANDING_VAR, CmpOp::Eq, kind),
                        SmCompare::float(TIME_SINCE_LAND_VAR, CmpOp::Lt, LANDING_WINDOW_S),
                        SmCompare::float(MODE_VAR, CmpOp::Eq, LocoMode::Grounded.param()),
                    ]))
                    .with_curve(BlendCurve::EaseInOut)
                    .with_priority(prio),
            );
        }
    }
    // …and a break-fall goes to the roll rather than to a stand-up.
    if let Some(r) = at("roll") {
        out.push(
            SmTransition::any(r, ACTION_FADE_S)
                .when(SmCond::from_flat_and(vec![
                    SmCompare::float(GROUNDED_VAR, CmpOp::Gt, 0.5),
                    SmCompare::float(LANDING_VAR, CmpOp::Eq, LANDING_ROLL),
                    SmCompare::float(TIME_SINCE_LAND_VAR, CmpOp::Lt, LANDING_WINDOW_S),
                ]))
                .with_curve(BlendCurve::EaseInOut)
                .with_priority(32),
        );
    }
    // …and a landing plays out and hands back to the ladder.
    for name in [
        "land_light",
        "land_heavy",
        "getup_front",
        "getup_back",
        "getup_standing",
        "slide",
    ] {
        if let (Some(s), Some(i)) = (at(name), at("idle")) {
            out.push(
                SmTransition::new(s, i, ACTION_FADE_S)
                    .with_exit_time(0.9)
                    .with_curve(BlendCurve::EaseInOut),
            );
        }
    }

    // ── THE MANTLE (wave CHAR1b.2) ──────────────────────────────────────────
    //
    // Entered from ANYWHERE, because `try_mantle` is reached from the ground
    // (a jump at a wall with the stick forward) and from the air (the falling
    // catch) — `ALSMantleComponent.cpp:396-413`, `OnOwnerJumpInput`. The
    // priority is above the landing family and below the ragdoll's, which is
    // the donor's own precedence: a ragdoll stops a running mantle outright
    // (`OnOwnerRagdollStateChanged`, `.cpp:416-423`).
    //
    // Each row's own value of `mantle` selects it, so the three edges are
    // mutually exclusive by construction and no hysteresis band is needed.
    for (name, which) in [
        ("mantle_low", MANTLE_LOW_RH),
        ("mantle_low_lh", MANTLE_LOW_LH),
        ("mantle_high", MANTLE_HIGH),
    ] {
        let Some(s) = at(name) else { continue };
        out.push(
            SmTransition::any(s, ACTION_FADE_S)
                .when(SmCond::from_flat_and(vec![
                    SmCompare::float(MODE_VAR, CmpOp::Eq, LocoMode::Mantle.param()),
                    SmCompare::float(MANTLE_VAR, CmpOp::Eq, which),
                ]))
                .with_curve(BlendCurve::EaseInOut)
                .with_priority(35),
        );
        // …and it hands back when the mantle ends, which the movement step
        // signals by leaving `Mantle` — never by the clip running out, because
        // the clock is the ledge height's and not the clip's.
        if let Some(i) = at("idle") {
            out.push(
                SmTransition::new(s, i, ACTION_FADE_S)
                    .when(SmCond::float(
                        MODE_VAR,
                        CmpOp::Eq,
                        LocoMode::Grounded.param(),
                    ))
                    .with_curve(BlendCurve::EaseInOut),
            );
        }
    }

    // ── THE AUTHORED SETS (wave CHAR1b.2) ───────────────────────────────────
    //
    // Every one is a MODE edge, because every one of them is a mode this
    // engine's movement step already enters and had no clip for. `Any`, for the
    // reason the mantle's rows are `Any`: a slide is entered from a sprint, a
    // dive or a crouch, and enumerating the sources would be a table that goes
    // stale the day the movement model grows a fourth.
    if let Some(s) = at("slide") {
        out.push(
            SmTransition::any(s, ACTION_FADE_S)
                .when(SmCond::float(MODE_VAR, CmpOp::Eq, LocoMode::Slide.param()))
                .with_curve(BlendCurve::EaseInOut)
                .with_priority(33),
        );
    }
    // Prone and the swims split on the gait the same way the standing ladder
    // does: still is the idle member, moving is the travelling one. The
    // conditions are exact complements on one constant, so neither can chatter.
    for (still, moving, mode) in [
        ("prone_idle", "prone_crawl", LocoMode::Prone),
        ("swim_tread", "swim_surface", LocoMode::SwimSurface),
    ] {
        if let Some(s) = at(still) {
            out.push(
                SmTransition::any(s, FADE_S)
                    .when(SmCond::from_flat_and(vec![
                        SmCompare::float(MODE_VAR, CmpOp::Eq, mode.param()),
                        SmCompare::float(GAIT_VAR, CmpOp::Le, WALK_AT),
                    ]))
                    .with_curve(BlendCurve::EaseInOut)
                    .with_priority(22),
            );
        }
        if let Some(m) = at(moving) {
            out.push(
                SmTransition::any(m, FADE_S)
                    .when(SmCond::from_flat_and(vec![
                        SmCompare::float(MODE_VAR, CmpOp::Eq, mode.param()),
                        SmCompare::float(GAIT_VAR, CmpOp::Gt, WALK_AT),
                    ]))
                    .with_curve(BlendCurve::EaseInOut)
                    .with_priority(22),
            );
        }
    }
    // ── COVER (wave COV1) ───────────────────────────────────────────────────
    //
    // Two conditions on every edge and both are necessary: the MODE says the
    // character is in cover and the CLASS says which stance the surface asked
    // for, which is the whole of "crouching or standing depending on the
    // object". The gait splits still from moving exactly as prone and the swims
    // do, on the same constant, so neither can chatter.
    //
    // The priority is the prone/swim block's 22 rather than the mantle's 35: a
    // mantle is a warp that owns the character outright and outranks everything,
    // and a cover stance is an ordinary grounded mode that a ragdoll or a fall
    // must be able to take away.
    for (still, moving, class) in [
        ("cover_low_idle", "cover_low_move", COVER_LOW),
        ("cover_high_idle", "cover_high_move", COVER_HIGH),
    ] {
        if let Some(s) = at(still) {
            out.push(
                SmTransition::any(s, FADE_S)
                    .when(SmCond::from_flat_and(vec![
                        SmCompare::float(MODE_VAR, CmpOp::Eq, LocoMode::Cover.param()),
                        SmCompare::float(COVER_VAR, CmpOp::Eq, class),
                        SmCompare::float(GAIT_VAR, CmpOp::Le, WALK_AT),
                    ]))
                    .with_curve(BlendCurve::EaseInOut)
                    .with_priority(22),
            );
        }
        if let Some(m) = at(moving) {
            out.push(
                SmTransition::any(m, FADE_S)
                    .when(SmCond::from_flat_and(vec![
                        SmCompare::float(MODE_VAR, CmpOp::Eq, LocoMode::Cover.param()),
                        SmCompare::float(COVER_VAR, CmpOp::Eq, class),
                        SmCompare::float(GAIT_VAR, CmpOp::Gt, WALK_AT),
                    ]))
                    .with_curve(BlendCurve::EaseInOut)
                    .with_priority(22),
            );
        }
    }
    if let Some(s) = at("swim_under") {
        out.push(
            SmTransition::any(s, FADE_S)
                .when(SmCond::float(
                    MODE_VAR,
                    CmpOp::Eq,
                    LocoMode::SwimUnder.param(),
                ))
                .with_curve(BlendCurve::EaseInOut)
                .with_priority(22),
        );
    }

    // ── roll and ragdoll ─────────────────────────────────────────────────────
    for (name, mode) in [("roll", LocoMode::Roll), ("ragdoll", LocoMode::Ragdoll)] {
        if let Some(s) = at(name) {
            out.push(
                SmTransition::any(s, ACTION_FADE_S)
                    .when(SmCond::float(MODE_VAR, CmpOp::Eq, mode.param()))
                    .with_curve(BlendCurve::EaseInOut)
                    .with_priority(40),
            );
        }
    }
    if let (Some(r), Some(i)) = (at("roll"), at("idle")) {
        out.push(
            SmTransition::new(r, i, ACTION_FADE_S)
                .with_exit_time(0.85)
                .when(SmCond::float(
                    MODE_VAR,
                    CmpOp::Eq,
                    LocoMode::Grounded.param(),
                ))
                .with_curve(BlendCurve::EaseInOut),
        );
    }
    // **Getting up**, and which way up it ended.
    //
    // ALS chooses between its two get-ups by the pelvis's facing, and this
    // engine's ragdoll bridge has recorded that as `RagdollRuntime::face_up`
    // since P29.4 with nothing reading it. It is published now, so both clips
    // are reachable and neither is a default nobody chose.
    //
    // ALS ships only the CROUCHED get-ups (`ALS_CLF_GetUp_Front/Back`); a
    // standing one has to be authored, and is CHAR1b.2's.
    for (name, which) in [
        ("getup_front", GETUP_FRONT),
        ("getup_back", GETUP_BACK),
        ("getup_standing", GETUP_STANDING),
    ] {
        let (Some(rag), Some(g)) = (at("ragdoll"), at(name)) else {
            continue;
        };
        out.push(
            SmTransition::new(rag, g, ACTION_FADE_S)
                .when(SmCond::from_flat_and(vec![
                    SmCompare::float(MODE_VAR, CmpOp::Eq, LocoMode::Grounded.param()),
                    SmCompare::float(GROUNDED_VAR, CmpOp::Gt, 0.5),
                    // `getup`, not `face_up` (wave CHAR1b.2): a two-valued
                    // signal cannot name three outcomes, and a ragdoll that
                    // settles on its feet is the third.
                    SmCompare::float(GETUP_VAR, CmpOp::Eq, which),
                ]))
                .with_curve(BlendCurve::EaseInOut)
                // **Above the `Any → idle` edge**, or a character that stops
                // ragdolling goes straight to standing and the get-ups are clips
                // that never play. The reachability arm caught it.
                .with_priority(8),
        );
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Every clip resolves to a distinct id, so the graph is fully bound.
    fn all_clips() -> impl Fn(&str) -> Option<ClipRef> {
        |name: &str| {
            let mut id = [0u8; 16];
            for (i, b) in name.as_bytes().iter().enumerate() {
                id[i % 16] ^= *b;
            }
            // A name the table does not use would collide with nothing, which is
            // what makes the `is_complete` claim below mean something.
            Some(id)
        }
    }

    #[test]
    fn the_map_is_a_table_of_distinct_states_and_distinct_clips() {
        let mut states: Vec<&str> = LOCOMOTION_MAP.iter().map(|s| s.state).collect();
        let n = states.len();
        states.sort_unstable();
        states.dedup();
        assert_eq!(states.len(), n, "two slots share a state name");
        let mut clips: Vec<&str> = LOCOMOTION_MAP
            .iter()
            .flat_map(|s| s.clips.iter().map(|(n, _)| *n))
            .collect();
        let m = clips.len();
        clips.sort_unstable();
        clips.dedup();
        assert_eq!(clips.len(), m, "one ALS sequence fills two slots");
        assert!(m >= 60, "the map names only {m} sequences");
    }

    #[test]
    fn a_full_resolve_builds_a_graph_that_validates() {
        let (sm, report) = build_locomotion_graph(&all_clips());
        assert!(report.is_complete(), "unbound: {:?}", report.unbound);
        assert!(report.missing_states.is_empty());
        sm.validate().expect("the built graph validates");
        // Every row is a state — including the overlays and the sweeps, which
        // are the additive layer's named clip sets (see the builder's docs).
        assert_eq!(sm.states.len(), LOCOMOTION_MAP.len(), "{:?}", report.states);
        // …and the two families the machine never enters really have no edge
        // into them, which is what "unreachable" has to mean to be true.
        let sweep = sm
            .states
            .iter()
            .position(|s| s.name == LOOK_SWEEP_STATE)
            .expect("the look sweep is a state");
        assert!(
            !sm.transitions.iter().any(|t| t.to == sweep),
            "something routes into the look sweep"
        );
        assert!(sm.transitions.len() > 20, "{} edges", sm.transitions.len());
        // The direction blends really are blend spaces over the two published
        // axes, and not six states somebody flattened.
        let walk = sm.states.iter().find(|s| s.name == "walk").unwrap();
        match &walk.motion {
            Motion::Blend2D(b) => {
                assert_eq!(b.params, (MOVE_X_VAR.into(), MOVE_Y_VAR.into()));
                assert_eq!(b.entries.len(), 6);
            }
            other => panic!("the walk is not a direction blend: {other:?}"),
        }
    }

    /// **A project with no ALS content still gets a graph** — the CI case.
    #[test]
    fn an_empty_resolve_answers_an_empty_graph_and_says_what_is_missing() {
        let (sm, report) = build_locomotion_graph(&|_| None);
        assert!(sm.states.is_empty());
        assert!(sm.transitions.is_empty());
        assert!(report.bound.is_empty());
        assert_eq!(
            report.unbound.len(),
            LOCOMOTION_MAP.iter().map(|s| s.clips.len()).sum::<usize>()
        );
        assert_eq!(report.missing_states.len(), LOCOMOTION_MAP.len());
        assert!(report.summary().contains("unbound"), "{}", report.summary());
    }

    /// A partial resolve — the crouch set absent — builds the rest and leaves no
    /// dangling edge, which is what `validate` is for.
    #[test]
    fn a_partial_resolve_drops_the_states_it_cannot_fill_and_their_edges() {
        let (sm, report) = build_locomotion_graph(&|name: &str| {
            (!name.contains("CLF")).then(|| all_clips()(name)).flatten()
        });
        sm.validate().expect("a partial graph still validates");
        assert!(
            report
                .missing_states
                .iter()
                .any(|s| s.starts_with("crouch")),
            "{:?}",
            report.missing_states
        );
        assert!(
            !sm.states.iter().any(|s| s.name.starts_with("crouch")),
            "a crouch state was built with no clips"
        );
        assert!(
            sm.states.iter().any(|s| s.name == "walk"),
            "the standing set went with the crouch set"
        );
    }
}
