//! **The ALS clip → mode map, and the graph it builds** (wave CHAR1b.1,
//! clause 2).
//!
//! P29 shipped a fourteen-mode movement catalogue, `RotationMode`,
//! turn-in-place rules, blend spaces, inertialization and a state-machine
//! runtime. What it never had was a *graph*: the island's hero — and every
//! committed sample — plays a three-state machine of `idle` / `walk` / `run`
//! generated by the P24 wizard, so eleven of the fourteen modes had no animation
//! at all and the three that did had one clip each and no direction.
//!
//! This module is the other half: a table saying which ALS sequence fills which
//! slot of a locomotion graph, and a builder that turns that table plus a
//! name→clip resolver into a [`StateMachine`].
//!
//! # Names, not assets
//!
//! **ALS-Community is MIT and its assets never enter this checkout.** What is
//! written down here is the *name* of each sequence — a fact about the donor's
//! catalogue, in the same way a port map records a function name — and a
//! resolver hands back whatever GUID the local import gave it. On a machine with
//! no ALS content [`build_locomotion_graph`] answers a graph with the slots it
//! could fill and a list of the ones it could not, which is what lets CI hold a
//! table it has no assets for.
//!
//! # Why a table and not a generator
//!
//! [`crate::locomotion`] *derives* a cycle from a rig, which is the right shape
//! when there is no content. Here there is content: 164 authored sequences whose
//! author decided what a left-forward run looks like. A generator would throw
//! that away. The table's job is to say which is which, once, where a reviewer
//! can read it against the donor's own folder listing.
//!
//! # The mode discriminants live in `inf-ecs` and are mirrored here
//!
//! `inf-anim` is below `inf-ecs` in the ring order and cannot name
//! `MovementMode`. [`LocoMode`] therefore carries the discriminant as a number
//! and `char1b_gate::the_two_mode_tables_agree` holds the two together — the
//! standing law about a table spelled in two crates.

use crate::blend_space::ClipRef;
use crate::blend_space::{BlendEntry2D, BlendSpace2D};
use crate::state_machine::{
    BlendCurve, CmpOp, Motion, SmCompare, SmCond, SmParam, SmState, SmTransition, StateMachine,
};

/// The parameter a machine reads for planar ground speed, m/s.
///
/// `inf_ecs::anim_bridge::params::SPEED` by construction, and
/// [`crate::locomotion::SPEED_VAR`] before that: three spellings of one word
/// would leave a character standing still, which is the defect P29.6 already
/// paid for once.
pub const SPEED_VAR: &str = crate::locomotion::SPEED_VAR;
/// The 0–3 gait scale — `inf_ecs::anim_bridge::params::GAIT`.
pub const GAIT_VAR: &str = "gait";
/// The [`LocoMode`] discriminant — `inf_ecs::anim_bridge::params::MODE`.
pub const MODE_VAR: &str = "mode";
/// `1` while the last sweep ended on the ground.
pub const GROUNDED_VAR: &str = "grounded";
/// Downward speed, m/s, positive falling.
pub const FALL_SPEED_VAR: &str = "fall_speed";
/// How close a predicted landing is, `[0, 1]`.
pub const LAND_ALPHA_VAR: &str = "land_alpha";
/// **The lateral half of the movement direction in the character's own frame**,
/// `[-1, 1]`, positive to its right (wave CHAR1b.1).
///
/// P29 published a four-value `direction` quadrant, which is enough to pick a
/// clip and not enough to *blend* between six of them. A blend space needs a
/// plane, so the movement step publishes one.
pub const MOVE_X_VAR: &str = "move_x";
/// The forward half of the same, positive ahead.
pub const MOVE_Y_VAR: &str = "move_y";

/// The engine movement mode a slot serves.
///
/// The discriminants are `inf_ecs::components::MovementMode`'s, mirrored because
/// the ring order forbids naming it; the gate holds them together.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub enum LocoMode {
    /// Standing locomotion.
    Grounded = 0,
    /// Crouched.
    Crouch = 1,
    /// A roll.
    Roll = 4,
    /// Airborne with full authority — a deliberate jump.
    FallFree = 6,
    /// Airborne with reduced authority — walked off a ledge, or knocked back.
    FallControlled = 7,
    /// Physics-driven ragdoll.
    Ragdoll = 11,
}

impl LocoMode {
    /// The `mode` parameter value a machine compares against.
    pub const fn param(self) -> f64 {
        self as u8 as f64
    }
}

/// What kind of thing a slot is, which decides where it is bound.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum SlotKind {
    /// A state of the locomotion graph — the machine plays it.
    State,
    /// A **weapon overlay pose set**, played on the additive layer rather than
    /// by the machine (ALS's own structure: an overlay is a layered blend over
    /// whatever the locomotion graph is doing). Listed here so the map is the
    /// one place a reader looks for "what plays what", and bound by
    /// [`crate::layers`]'s stack rather than by [`build_locomotion_graph`].
    Overlay,
    /// An **aim sweep** — a 2D additive blend space driven by aim yaw and pitch.
    AimSweep,
}

/// One slot of the locomotion graph: a state name, the mode it serves, and the
/// ALS sequences that fill it.
#[derive(Clone, Copy, Debug)]
pub struct LocoSlot {
    /// The machine state's name, or the layer's.
    pub state: &'static str,
    /// The engine mode this slot animates.
    pub mode: LocoMode,
    /// Where it is bound.
    pub kind: SlotKind,
    /// Whether the motion loops (a cycle) or holds its last pose (a one-shot).
    pub looping: bool,
    /// The ALS sequences and their blend coordinates in `(move_x, move_y)`.
    ///
    /// One entry is a single clip; more than one is a [`BlendSpace2D`] over
    /// those coordinates. The coordinates are the donor's own directions:
    /// forward is `+y`, the character's right is `+x`, and a diagonal is the
    /// unit-ish corner ALS authored it at.
    pub clips: &'static [(&'static str, [f64; 2])],
}

/// The forward sample of a direction blend.
const F: [f64; 2] = [0.0, 1.0];
/// Backward.
const B: [f64; 2] = [0.0, -1.0];
/// Left-forward. **On the diamond `|x| + |y| = 1`, not the square**: the
/// movement step publishes ALS's own normalization (`Sum = |X| + |Y|`, so a
/// diagonal is `0.5, 0.5`), and a sample at `(1, 1)` would be a clip the blend
/// could never reach.
const LF: [f64; 2] = [-0.5, 0.5];
/// Right-forward. See [`LF`].
const RF: [f64; 2] = [0.5, 0.5];
/// Left-backward. See [`LF`].
const LB: [f64; 2] = [-0.5, -0.5];
/// Right-backward. See [`LF`].
const RB: [f64; 2] = [0.5, -0.5];
/// Left.
const L: [f64; 2] = [-1.0, 0.0];
/// Right.
const R: [f64; 2] = [1.0, 0.0];
/// The single sample of a clip that is not a direction blend.
const O: [f64; 2] = [0.0, 0.0];

/// **THE MAP** — every slot of the locomotion graph, and the ALS sequence that
/// fills it.
///
/// Only what **ALS ships** is here. The sets it does not have — slide, throwing,
/// swimming, prone, the standing get-up, cover and vault — are authored or
/// sourced content and belong to the next slice; naming them here with no clip
/// would make an unbound row indistinguishable from a missing import, which is
/// exactly what the gate is for.
///
/// The mantle clips (`ALS_N_Mantle_1m_LH/RH`, `_2m`) are ALS's and are
/// deliberately absent: a mantle is a *warped, timeline-driven* traversal rather
/// than a machine state, and the mechanism that plays them is the next slice's.
pub const LOCOMOTION_MAP: &[LocoSlot] = &[
    // ── standing ─────────────────────────────────────────────────────────────
    LocoSlot {
        state: "idle",
        mode: LocoMode::Grounded,
        kind: SlotKind::State,
        looping: true,
        clips: &[("ALS_N_Pose", O)],
    },
    LocoSlot {
        state: "walk",
        mode: LocoMode::Grounded,
        kind: SlotKind::State,
        looping: true,
        clips: &[
            ("ALS_N_Walk_F", F),
            ("ALS_N_Walk_B", B),
            ("ALS_N_Walk_LF", LF),
            ("ALS_N_Walk_RF", RF),
            ("ALS_N_Walk_LB", LB),
            ("ALS_N_Walk_RB", RB),
        ],
    },
    LocoSlot {
        state: "run",
        mode: LocoMode::Grounded,
        kind: SlotKind::State,
        looping: true,
        clips: &[
            ("ALS_N_Run_F", F),
            ("ALS_N_Run_B", B),
            ("ALS_N_Run_LF", LF),
            ("ALS_N_Run_RF", RF),
            ("ALS_N_Run_LB", LB),
            ("ALS_N_Run_RB", RB),
        ],
    },
    LocoSlot {
        state: "sprint",
        mode: LocoMode::Grounded,
        kind: SlotKind::State,
        looping: true,
        clips: &[("ALS_N_Sprint_F", O)],
    },
    // ── stops and starts ─────────────────────────────────────────────────────
    LocoSlot {
        state: "stop_l",
        mode: LocoMode::Grounded,
        kind: SlotKind::State,
        looping: false,
        clips: &[("ALS_N_Stop_L_Down", O)],
    },
    LocoSlot {
        state: "stop_r",
        mode: LocoMode::Grounded,
        kind: SlotKind::State,
        looping: false,
        clips: &[("ALS_N_Stop_R_Down", O)],
    },
    LocoSlot {
        state: "start",
        mode: LocoMode::Grounded,
        kind: SlotKind::State,
        looping: false,
        clips: &[
            ("ALS_N_LocoDetail_Accel_F", F),
            ("ALS_N_LocoDetail_Accel_B", B),
            ("ALS_N_LocoDetail_Accel_L", L),
            ("ALS_N_LocoDetail_Accel_R", R),
        ],
    },
    // ── turn in place ────────────────────────────────────────────────────────
    LocoSlot {
        state: "turn_l90",
        mode: LocoMode::Grounded,
        kind: SlotKind::State,
        looping: false,
        clips: &[("ALS_N_TurnIP_L90", O)],
    },
    LocoSlot {
        state: "turn_r90",
        mode: LocoMode::Grounded,
        kind: SlotKind::State,
        looping: false,
        clips: &[("ALS_N_TurnIP_R90", O)],
    },
    LocoSlot {
        state: "turn_l180",
        mode: LocoMode::Grounded,
        kind: SlotKind::State,
        looping: false,
        clips: &[("ALS_N_TurnIP_L180", O)],
    },
    LocoSlot {
        state: "turn_r180",
        mode: LocoMode::Grounded,
        kind: SlotKind::State,
        looping: false,
        clips: &[("ALS_N_TurnIP_R180", O)],
    },
    // ── crouch ───────────────────────────────────────────────────────────────
    LocoSlot {
        state: "crouch_idle",
        mode: LocoMode::Crouch,
        kind: SlotKind::State,
        looping: true,
        clips: &[("ALS_CLF_Pose", O)],
    },
    LocoSlot {
        state: "crouch_walk",
        mode: LocoMode::Crouch,
        kind: SlotKind::State,
        looping: true,
        clips: &[
            ("ALS_CLF_Walk_F", F),
            ("ALS_CLF_Walk_B", B),
            ("ALS_CLF_Walk_L", L),
            ("ALS_CLF_Walk_R", R),
        ],
    },
    LocoSlot {
        state: "crouch_turn_l90",
        mode: LocoMode::Crouch,
        kind: SlotKind::State,
        looping: false,
        clips: &[("ALS_CLF_TurnIP_L90", O)],
    },
    LocoSlot {
        state: "crouch_turn_r90",
        mode: LocoMode::Crouch,
        kind: SlotKind::State,
        looping: false,
        clips: &[("ALS_CLF_TurnIP_R90", O)],
    },
    LocoSlot {
        state: "crouch_turn_l180",
        mode: LocoMode::Crouch,
        kind: SlotKind::State,
        looping: false,
        clips: &[("ALS_CLF_TurnIP_L180", O)],
    },
    LocoSlot {
        state: "crouch_turn_r180",
        mode: LocoMode::Crouch,
        kind: SlotKind::State,
        looping: false,
        clips: &[("ALS_CLF_TurnIP_R180", O)],
    },
    // ── the air ──────────────────────────────────────────────────────────────
    LocoSlot {
        state: "jump",
        mode: LocoMode::FallFree,
        kind: SlotKind::State,
        looping: true,
        clips: &[("ALS_N_JumpLoop", O)],
    },
    LocoSlot {
        state: "fall",
        mode: LocoMode::FallControlled,
        kind: SlotKind::State,
        looping: true,
        clips: &[("ALS_N_FallLoop", O)],
    },
    LocoSlot {
        state: "fall_fast",
        mode: LocoMode::FallControlled,
        kind: SlotKind::State,
        looping: true,
        clips: &[("ALS_N_FallLoop_Fast", O)],
    },
    LocoSlot {
        state: "land_light",
        mode: LocoMode::Grounded,
        kind: SlotKind::State,
        looping: false,
        clips: &[("ALS_N_Land_Light", O)],
    },
    LocoSlot {
        state: "land_heavy",
        mode: LocoMode::Grounded,
        kind: SlotKind::State,
        looping: false,
        clips: &[("ALS_N_Land_Heavy", O)],
    },
    LocoSlot {
        state: "roll",
        mode: LocoMode::Roll,
        kind: SlotKind::State,
        looping: false,
        clips: &[("ALS_N_LandRoll_F", O)],
    },
    // ── ragdoll ──────────────────────────────────────────────────────────────
    LocoSlot {
        state: "ragdoll",
        mode: LocoMode::Ragdoll,
        kind: SlotKind::State,
        looping: true,
        clips: &[("ALS_Flail", O)],
    },
    LocoSlot {
        state: "getup_front",
        mode: LocoMode::Grounded,
        kind: SlotKind::State,
        looping: false,
        clips: &[("ALS_CLF_GetUp_Front", O)],
    },
    LocoSlot {
        state: "getup_back",
        mode: LocoMode::Grounded,
        kind: SlotKind::State,
        looping: false,
        clips: &[("ALS_CLF_GetUp_Back", O)],
    },
    // ── the weapon overlays (WPN1's items; the additive layer plays them) ─────
    LocoSlot {
        state: "overlay_m4a1",
        mode: LocoMode::Grounded,
        kind: SlotKind::Overlay,
        looping: false,
        clips: &[("ALS_Props_M4A1_Poses", O)],
    },
    LocoSlot {
        state: "overlay_pistol_1h",
        mode: LocoMode::Grounded,
        kind: SlotKind::Overlay,
        looping: false,
        clips: &[("ALS_Props_Pistol_1H_Poses", O)],
    },
    LocoSlot {
        state: "overlay_pistol_2h",
        mode: LocoMode::Grounded,
        kind: SlotKind::Overlay,
        looping: false,
        clips: &[("ALS_Props_Pistol_2H_Poses", O)],
    },
    LocoSlot {
        state: "overlay_bow",
        mode: LocoMode::Grounded,
        kind: SlotKind::Overlay,
        looping: false,
        clips: &[("ALS_Props_Bow_Poses", O)],
    },
    LocoSlot {
        state: "overlay_torch",
        mode: LocoMode::Grounded,
        kind: SlotKind::Overlay,
        looping: false,
        clips: &[("ALS_Props_Torch_Poses", O)],
    },
    LocoSlot {
        state: "overlay_binoculars",
        mode: LocoMode::Grounded,
        kind: SlotKind::Overlay,
        looping: false,
        clips: &[("ALS_Props_Binoculars_Poses", O)],
    },
    LocoSlot {
        state: "overlay_box",
        mode: LocoMode::Grounded,
        kind: SlotKind::Overlay,
        looping: false,
        clips: &[("ALS_Props_Box_Poses", O)],
    },
    LocoSlot {
        state: "overlay_barrel",
        mode: LocoMode::Grounded,
        kind: SlotKind::Overlay,
        looping: false,
        clips: &[("ALS_Props_Barrel_Poses", O)],
    },
    // ── the aim sweeps (the additive layer's 2D blend spaces) ────────────────
    LocoSlot {
        state: "aim_look",
        mode: LocoMode::Grounded,
        kind: SlotKind::AimSweep,
        looping: false,
        clips: &[
            ("ALS_N_Look_U_Sweep", [0.0, 1.0]),
            ("ALS_N_Look_F_Sweep", [0.0, 0.0]),
            ("ALS_N_Look_D_Sweep", [0.0, -1.0]),
        ],
    },
    LocoSlot {
        state: "aim_m4a1",
        mode: LocoMode::Grounded,
        kind: SlotKind::AimSweep,
        looping: false,
        clips: &[
            ("ALS_Props_M4A1_Aim_Sweep", [0.0, 0.0]),
            ("ALS_Props_M4A1_Aim_Sweep_Crouched", [0.0, -1.0]),
        ],
    },
    LocoSlot {
        state: "aim_pistol_1h",
        mode: LocoMode::Grounded,
        kind: SlotKind::AimSweep,
        looping: false,
        clips: &[
            ("ALS_Props_Pistol_1H_Aim_Sweep", [0.0, 0.0]),
            ("ALS_Props_Pistol_1H_Aim_Sweep_Crouched", [0.0, -1.0]),
        ],
    },
    LocoSlot {
        state: "aim_pistol_2h",
        mode: LocoMode::Grounded,
        kind: SlotKind::AimSweep,
        looping: false,
        clips: &[
            ("ALS_Props_Pistol_2H_Aim_Sweep", [0.0, 0.0]),
            ("ALS_Props_Pistol_2H_Aim_Sweep_Crouched", [0.0, -1.0]),
        ],
    },
    LocoSlot {
        state: "aim_bow",
        mode: LocoMode::Grounded,
        kind: SlotKind::AimSweep,
        looping: false,
        clips: &[
            ("ALS_Props_Bow_Aim_Sweep", [0.0, 0.0]),
            ("ALS_Props_Bow_Aim_Sweep_Crouched", [0.0, -1.0]),
        ],
    },
    LocoSlot {
        state: "aim_torch",
        mode: LocoMode::Grounded,
        kind: SlotKind::AimSweep,
        looping: false,
        clips: &[
            ("ALS_Props_Torch_Aim_Sweep", [0.0, 0.0]),
            ("ALS_Props_Torch_Aim_Sweep_Crouched", [0.0, -1.0]),
        ],
    },
    LocoSlot {
        state: "aim_binoculars",
        mode: LocoMode::Grounded,
        kind: SlotKind::AimSweep,
        looping: false,
        clips: &[
            ("ALS_Props_Binoculars_Aim_Sweep", [0.0, 0.0]),
            ("ALS_Props_Binoculars_Aim_Sweep_Crouched", [0.0, -1.0]),
        ],
    },
];

/// What [`build_locomotion_graph`] managed to bind.
#[derive(Clone, Debug, Default, PartialEq)]
pub struct LocoBindReport {
    /// `(state, clip name)` for every clip that resolved, in table order.
    pub bound: Vec<(String, String)>,
    /// `(state, clip name)` for every clip that did not.
    pub unbound: Vec<(String, String)>,
    /// States that ended up in the graph.
    pub states: Vec<String>,
    /// States the table names that could not be built at all, because **none**
    /// of their clips resolved.
    pub missing_states: Vec<String>,
}

impl LocoBindReport {
    /// Whether every clip the table names resolved.
    pub fn is_complete(&self) -> bool {
        self.unbound.is_empty()
    }

    /// A one-line summary for an import advisory.
    pub fn summary(&self) -> String {
        format!(
            "{} states, {} clips bound, {} unbound{}",
            self.states.len(),
            self.bound.len(),
            self.unbound.len(),
            if self.missing_states.is_empty() {
                String::new()
            } else {
                format!(" ({} states unfilled)", self.missing_states.len())
            }
        )
    }
}

/// **Build the locomotion graph** from [`LOCOMOTION_MAP`] and a name→clip
/// resolver.
///
/// Only [`SlotKind::State`] rows become states; overlays and aim sweeps are the
/// additive layer's and are reported as bound or unbound without entering the
/// machine.
///
/// A state whose clips all fail to resolve is **left out** rather than pointed at
/// a null GUID: a state that plays nothing is a T-pose with a name, and the
/// report says which ones went. A state whose clips *partly* resolve keeps the
/// samples it has, because a five-sample direction blend is a worse walk and not
/// a broken one.
///
/// The entry state is `idle` when it exists and the first state otherwise.
pub fn build_locomotion_graph(
    resolve: &dyn Fn(&str) -> Option<ClipRef>,
) -> (StateMachine, LocoBindReport) {
    let mut report = LocoBindReport::default();
    let mut states: Vec<SmState> = Vec::new();
    let mut index: std::collections::BTreeMap<&'static str, usize> =
        std::collections::BTreeMap::new();

    for slot in LOCOMOTION_MAP {
        let mut got: Vec<BlendEntry2D> = Vec::new();
        for (name, pos) in slot.clips {
            match resolve(name) {
                Some(clip) => {
                    report.bound.push((slot.state.into(), (*name).into()));
                    got.push(BlendEntry2D { pos: *pos, clip });
                }
                None => report.unbound.push((slot.state.into(), (*name).into())),
            }
        }
        if slot.kind != SlotKind::State {
            continue;
        }
        if got.is_empty() {
            report.missing_states.push(slot.state.into());
            continue;
        }
        let motion = if got.len() == 1 {
            Motion::Clip(got[0].clip)
        } else {
            Motion::Blend2D(BlendSpace2D::new(MOVE_X_VAR, MOVE_Y_VAR, got))
        };
        index.insert(slot.state, states.len());
        // The canvas position is the table's own order, laid out in rows of
        // four: an authored graph a human opens should not be a pile at 0,0.
        let n = states.len();
        states.push(SmState {
            name: slot.state.into(),
            motion,
            looping: slot.looping,
            speed: 1.0,
            position: ((n % 4) as f32 * 260.0, (n / 4) as f32 * 180.0),
            on_enter: Vec::new(),
            on_exit: Vec::new(),
        });
        report.states.push(slot.state.into());
    }

    let transitions = transitions_for(&index);
    let entry = index.get("idle").copied().unwrap_or(0);
    (
        StateMachine {
            states,
            transitions,
            entry,
            params: vec![
                SmParam::float(SPEED_VAR),
                SmParam::float(GAIT_VAR),
                SmParam::float(MODE_VAR),
                SmParam::float(GROUNDED_VAR),
                SmParam::float(FALL_SPEED_VAR),
                SmParam::float(LAND_ALPHA_VAR),
                SmParam::float(MOVE_X_VAR),
                SmParam::float(MOVE_Y_VAR),
            ],
            profiles: Vec::new(),
        },
        report,
    )
}

/// The gait thresholds the graph switches on, m/s.
///
/// `GAIT_VAR` is the 0–3 scale, so these are its own boundaries and not speeds:
/// 1 is walk, 2 run, 3 sprint ([`crate::derive::gait_of`]). Switching on the
/// *scale* rather than on metres per second is what lets one graph serve a
/// 1.6 m character and a 2.0 m one.
const WALK_AT: f64 = 0.1;
/// See [`WALK_AT`].
const RUN_AT: f64 = 1.5;
/// See [`WALK_AT`].
const SPRINT_AT: f64 = 2.5;

/// The cross-fade every locomotion edge uses, seconds.
///
/// ALS's own `Blend Time` on the cycle-blending layers. Long enough to hide the
/// pose discontinuity between two cadences, short enough that the character is
/// not still blending when the player has let go of the stick.
const FADE_S: f64 = 0.15;
/// The fade into and out of an action (a land, a turn, a get-up), which is
/// shorter because an action's first frame is its statement.
const ACTION_FADE_S: f64 = 0.08;

/// Every edge of the graph, over whichever states exist.
///
/// Written as a table over *names* and filtered to the states that were built,
/// so a project with no crouch set gets a graph with no crouch edges rather than
/// a machine that fails `validate`.
fn transitions_for(index: &std::collections::BTreeMap<&'static str, usize>) -> Vec<SmTransition> {
    let mut out = Vec::new();
    let at = |n: &str| index.get(n).copied();

    // ── the gait ladder, inside `Grounded` ───────────────────────────────────
    //
    // Each pair of conditions is an exact complement on the same constant, so
    // the machine cannot chatter and needs no hysteresis band — the rule
    // `locomotion_machine` established at P24.5 and the reason there is no
    // idle→run edge: one fixed step of latency through `walk` buys four edges
    // instead of six.
    let ladder = [
        ("idle", "walk", WALK_AT),
        ("walk", "run", RUN_AT),
        ("run", "sprint", SPRINT_AT),
    ];
    for (lo, hi, at_gait) in ladder {
        if let (Some(a), Some(b)) = (at(lo), at(hi)) {
            out.push(
                SmTransition::on(a, b, FADE_S, GAIT_VAR, CmpOp::Gt, at_gait)
                    .with_curve(BlendCurve::EaseInOut)
                    .when(SmCond::from_flat_and(vec![
                        SmCompare::float(GAIT_VAR, CmpOp::Gt, at_gait),
                        SmCompare::float(MODE_VAR, CmpOp::Eq, LocoMode::Grounded.param()),
                    ])),
            );
            out.push(
                SmTransition::on(b, a, FADE_S, GAIT_VAR, CmpOp::Le, at_gait)
                    .with_curve(BlendCurve::EaseInOut),
            );
        }
    }

    // ── crouch: the whole standing family drops into it, and back ────────────
    if let Some(c) = at("crouch_idle") {
        out.push(
            SmTransition::any(c, FADE_S)
                .when(SmCond::float(MODE_VAR, CmpOp::Eq, LocoMode::Crouch.param()))
                .with_curve(BlendCurve::EaseInOut)
                // Below the mode edges below, so an airborne character does not
                // crouch on the way past.
                .with_priority(10),
        );
    }
    if let (Some(ci), Some(cw)) = (at("crouch_idle"), at("crouch_walk")) {
        out.push(
            SmTransition::on(ci, cw, FADE_S, GAIT_VAR, CmpOp::Gt, WALK_AT)
                .with_curve(BlendCurve::EaseInOut),
        );
        out.push(
            SmTransition::on(cw, ci, FADE_S, GAIT_VAR, CmpOp::Le, WALK_AT)
                .with_curve(BlendCurve::EaseInOut),
        );
    }
    if let Some(i) = at("idle") {
        out.push(
            SmTransition::any(i, FADE_S)
                .when(SmCond::from_flat_and(vec![
                    SmCompare::float(MODE_VAR, CmpOp::Eq, LocoMode::Grounded.param()),
                    SmCompare::float(GROUNDED_VAR, CmpOp::Gt, 0.5),
                    SmCompare::float(GAIT_VAR, CmpOp::Le, WALK_AT),
                ]))
                .with_curve(BlendCurve::EaseInOut)
                .with_priority(5),
        );
    }

    // ── the air ──────────────────────────────────────────────────────────────
    for (name, mode) in [
        ("jump", LocoMode::FallFree),
        ("fall", LocoMode::FallControlled),
    ] {
        if let Some(s) = at(name) {
            out.push(
                SmTransition::any(s, ACTION_FADE_S)
                    .when(SmCond::float(MODE_VAR, CmpOp::Eq, mode.param()))
                    .with_curve(BlendCurve::EaseInOut)
                    .with_priority(20),
            );
        }
    }
    // A long fall speeds up: ALS swaps `FallLoop` for `FallLoop_Fast`.
    if let (Some(f), Some(ff)) = (at("fall"), at("fall_fast")) {
        out.push(
            SmTransition::on(f, ff, FADE_S, FALL_SPEED_VAR, CmpOp::Gt, 9.0)
                .with_curve(BlendCurve::EaseInOut),
        );
        out.push(
            SmTransition::on(ff, f, FADE_S, FALL_SPEED_VAR, CmpOp::Le, 9.0)
                .with_curve(BlendCurve::EaseInOut),
        );
    }
    // The landing, classified by how hard it is about to be.
    if let Some(l) = at("land_light") {
        out.push(
            SmTransition::any(l, ACTION_FADE_S)
                .when(SmCond::from_flat_and(vec![
                    SmCompare::float(GROUNDED_VAR, CmpOp::Gt, 0.5),
                    SmCompare::float(LAND_ALPHA_VAR, CmpOp::Gt, 0.5),
                    SmCompare::float(FALL_SPEED_VAR, CmpOp::Le, 6.0),
                    SmCompare::float(MODE_VAR, CmpOp::Eq, LocoMode::Grounded.param()),
                ]))
                .with_curve(BlendCurve::EaseInOut)
                .with_priority(30),
        );
    }
    if let Some(h) = at("land_heavy") {
        out.push(
            SmTransition::any(h, ACTION_FADE_S)
                .when(SmCond::from_flat_and(vec![
                    SmCompare::float(GROUNDED_VAR, CmpOp::Gt, 0.5),
                    SmCompare::float(LAND_ALPHA_VAR, CmpOp::Gt, 0.5),
                    SmCompare::float(FALL_SPEED_VAR, CmpOp::Gt, 6.0),
                    SmCompare::float(MODE_VAR, CmpOp::Eq, LocoMode::Grounded.param()),
                ]))
                .with_curve(BlendCurve::EaseInOut)
                .with_priority(31),
        );
    }
    // …and a landing plays out and hands back to the ladder.
    for name in ["land_light", "land_heavy", "getup_front", "getup_back"] {
        if let (Some(s), Some(i)) = (at(name), at("idle")) {
            out.push(
                SmTransition::new(s, i, ACTION_FADE_S)
                    .with_exit_time(0.9)
                    .with_curve(BlendCurve::EaseInOut),
            );
        }
    }

    // ── roll and ragdoll ─────────────────────────────────────────────────────
    for (name, mode) in [("roll", LocoMode::Roll), ("ragdoll", LocoMode::Ragdoll)] {
        if let Some(s) = at(name) {
            out.push(
                SmTransition::any(s, ACTION_FADE_S)
                    .when(SmCond::float(MODE_VAR, CmpOp::Eq, mode.param()))
                    .with_curve(BlendCurve::EaseInOut)
                    .with_priority(40),
            );
        }
    }
    if let (Some(r), Some(i)) = (at("roll"), at("idle")) {
        out.push(
            SmTransition::new(r, i, ACTION_FADE_S)
                .with_exit_time(0.85)
                .when(SmCond::float(
                    MODE_VAR,
                    CmpOp::Eq,
                    LocoMode::Grounded.param(),
                ))
                .with_curve(BlendCurve::EaseInOut),
        );
    }
    // Getting up: the ragdoll ends and the character is on its front or back.
    // Which one is a gameplay fact the mode does not carry, so the graph takes
    // the FRONT get-up by default and a project that knows better arms the other
    // through `anim.set_param`. Named here rather than silently preferred.
    if let (Some(rag), Some(g)) = (at("ragdoll"), at("getup_front")) {
        out.push(
            SmTransition::new(rag, g, ACTION_FADE_S)
                .when(SmCond::from_flat_and(vec![
                    SmCompare::float(MODE_VAR, CmpOp::Eq, LocoMode::Grounded.param()),
                    SmCompare::float(GROUNDED_VAR, CmpOp::Gt, 0.5),
                ]))
                .with_curve(BlendCurve::EaseInOut),
        );
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Every clip resolves to a distinct id, so the graph is fully bound.
    fn all_clips() -> impl Fn(&str) -> Option<ClipRef> {
        |name: &str| {
            let mut id = [0u8; 16];
            for (i, b) in name.as_bytes().iter().enumerate() {
                id[i % 16] ^= *b;
            }
            // A name the table does not use would collide with nothing, which is
            // what makes the `is_complete` claim below mean something.
            Some(id)
        }
    }

    #[test]
    fn the_map_is_a_table_of_distinct_states_and_distinct_clips() {
        let mut states: Vec<&str> = LOCOMOTION_MAP.iter().map(|s| s.state).collect();
        let n = states.len();
        states.sort_unstable();
        states.dedup();
        assert_eq!(states.len(), n, "two slots share a state name");
        let mut clips: Vec<&str> = LOCOMOTION_MAP
            .iter()
            .flat_map(|s| s.clips.iter().map(|(n, _)| *n))
            .collect();
        let m = clips.len();
        clips.sort_unstable();
        clips.dedup();
        assert_eq!(clips.len(), m, "one ALS sequence fills two slots");
        assert!(m >= 60, "the map names only {m} sequences");
    }

    #[test]
    fn a_full_resolve_builds_a_graph_that_validates() {
        let (sm, report) = build_locomotion_graph(&all_clips());
        assert!(report.is_complete(), "unbound: {:?}", report.unbound);
        assert!(report.missing_states.is_empty());
        sm.validate().expect("the built graph validates");
        // Every `State` row is a state, and nothing else is.
        let want = LOCOMOTION_MAP
            .iter()
            .filter(|s| s.kind == SlotKind::State)
            .count();
        assert_eq!(sm.states.len(), want, "{:?}", report.states);
        assert!(sm.transitions.len() > 20, "{} edges", sm.transitions.len());
        // The direction blends really are blend spaces over the two published
        // axes, and not six states somebody flattened.
        let walk = sm.states.iter().find(|s| s.name == "walk").unwrap();
        match &walk.motion {
            Motion::Blend2D(b) => {
                assert_eq!(b.params, (MOVE_X_VAR.into(), MOVE_Y_VAR.into()));
                assert_eq!(b.entries.len(), 6);
            }
            other => panic!("the walk is not a direction blend: {other:?}"),
        }
    }

    /// **A project with no ALS content still gets a graph** — the CI case.
    #[test]
    fn an_empty_resolve_answers_an_empty_graph_and_says_what_is_missing() {
        let (sm, report) = build_locomotion_graph(&|_| None);
        assert!(sm.states.is_empty());
        assert!(sm.transitions.is_empty());
        assert!(report.bound.is_empty());
        assert_eq!(
            report.unbound.len(),
            LOCOMOTION_MAP.iter().map(|s| s.clips.len()).sum::<usize>()
        );
        assert_eq!(
            report.missing_states.len(),
            LOCOMOTION_MAP
                .iter()
                .filter(|s| s.kind == SlotKind::State)
                .count()
        );
        assert!(report.summary().contains("unbound"), "{}", report.summary());
    }

    /// A partial resolve — the crouch set absent — builds the rest and leaves no
    /// dangling edge, which is what `validate` is for.
    #[test]
    fn a_partial_resolve_drops_the_states_it_cannot_fill_and_their_edges() {
        let (sm, report) = build_locomotion_graph(&|name: &str| {
            (!name.contains("CLF")).then(|| all_clips()(name)).flatten()
        });
        sm.validate().expect("a partial graph still validates");
        assert!(
            report
                .missing_states
                .iter()
                .any(|s| s.starts_with("crouch")),
            "{:?}",
            report.missing_states
        );
        assert!(
            !sm.states.iter().any(|s| s.name.starts_with("crouch")),
            "a crouch state was built with no clips"
        );
        assert!(
            sm.states.iter().any(|s| s.name == "walk"),
            "the standing set went with the crouch set"
        );
    }
}
