//! **The default locomotion set** (P24.5): idle / walk / run synthesized from a
//! body plan, and the state machine that wires them to one `speed` parameter.
//!
//! # Why this is generated and not shipped
//!
//! The P24.5 wizard's promise is *pick a plan → shape it → auto-rig → a default
//! locomotion set wired to a state machine*, and the honest reading of "default
//! locomotion set" was measured before it was written: **nothing in this
//! repository ships stock clips**. `samples/character-demo` commits three
//! hand-authored `.inf_anim` files bound to *its own* six-joint placeholder rig,
//! and [`crate::root_motion::straight_line_clip`] is a one-joint test helper. A
//! stock clip is bound to the skeleton it was authored against — joint *indices*,
//! not names — so a shipped walk cycle would fit exactly one rig and every
//! template proportion would break it.
//!
//! So the set is **derived from the rig it will drive**. That is what makes it
//! work for a 1.2 m biped, a 2.4 m one, a quadruped and a hexapod from one
//! generator, and it is why changing a proportion changes the animation as well
//! as the skeleton.
//!
//! # It is a POSE cycle, not root motion
//!
//! Nothing here translates the character. The hips bob and the legs swing **in
//! place**; forward movement is gameplay's (`physics3d.move_and_slide`, a
//! character controller, whatever the actor does), exactly as
//! `samples/character-demo` already works. A generated clip that translated its
//! root would slide a state-machine-driven character across the world, because
//! root-motion *extraction* reads `AnimPlayer` and a machine-driven entity has
//! none.
//!
//! [`LocomotionSet::walk_speed_m_s`] is therefore a **threshold**, not a
//! measurement of the clip: it is the ground speed the depicted stride would
//! carry the body at (`stride_m × cadence`, where `stride_m = 2 L sin θ` for a
//! leg of length `L` swinging `±θ`), and it exists so the generated machine
//! compares gameplay's speed against a number that came from *this* creature's
//! legs rather than from a constant. A 0.9 m-legged human and a 0.3 m-legged
//! terrier break into a run at different speeds because their legs are different
//! lengths, and that falls out of the arithmetic rather than being tuned.
//!
//! # Determinism
//!
//! Every angle is computed in `f64` through [`inf_math::psin64`] /
//! [`inf_math::pcos64`] and cast to `f32` once, at the wire — the
//! [`crate::template`] doctrine. **No `std` transcendental is called**, and no
//! `glam` constructor that would call one: a rotation about local X is written
//! out as `(sin(a/2), 0, 0, cos(a/2))` by hand, because `Quat::from_rotation_x`
//! is `f32::sin_cos` and these clips are *committed content* — a `.inf_anim` on
//! disk whose bytes a cook, a pack and a determinism gate all compare. That is
//! the P14 law, and P22 restated it: it reaches further than serialization.
//!
//! Two generations from the same rig and the same parameters are byte-identical
//! (`the_same_rig_generates_the_same_clips`).
//!
//! # The joints it addresses
//!
//! By **name**, through [`crate::template::leg_suffix`] — the same function
//! [`crate::template::build_template`] names them with, so there is one spelling
//! of the rule rather than two that have to agree. A rig that is missing one is a
//! named refusal ([`LocomotionError::MissingJoint`]) and not a silently empty
//! track, because a walk cycle with no legs in it is the failure that looks most
//! like success.

use serde::{Deserialize, Serialize};
use thiserror::Error;

use inf_math::{pcos64, psin64};

use crate::asset::SkeletonAsset;
use crate::blend_space::ClipRef;
use crate::clip::{AnimClip, Interpolation, JointTrack, QuatTrack, Vec3Track};
use crate::skeleton::Skeleton;
use crate::state_machine::{BlendCurve, CmpOp, SmParam, SmState, SmTransition, StateMachine};
use crate::template::{leg_suffix, BodyPlan};

/// τ, as `f64`. Written out rather than imported so the reduction inside
/// [`psin64`] sees the same constant this module's tests do.
const TAU: f64 = std::f64::consts::TAU;

/// The most keyframes a generated cycle may carry, per cycle.
///
/// A sanity bound in [`crate::template::MAX_LEGS`]' spirit: past this the extra
/// keys are below the interpolator's own error, and an unbounded count turns a
/// typo in a UI field into a multi-megabyte clip.
pub const MAX_KEYS_PER_CYCLE: u32 = 64;

/// The state-machine variable the generated machine reads.
///
/// `speed` and not `velocity` or `move_speed`: it is the name
/// `samples/character-demo`'s Blueprint already sets and the one the P11.2 state
/// machine docs use, so a character generated by the wizard drops into an
/// existing project's conventions rather than importing a new one.
pub const SPEED_VAR: &str = "speed";

/// The names of the three generated states, in index order — `entry` is `0`.
pub const STATE_NAMES: [&str; 3] = ["idle", "walk", "run"];

/// How the generated gait is shaped. Every angle is **degrees** (the authoring
/// convention), every rate is **hertz**, every length a fraction of something the
/// rig measures — nothing here is an absolute metre, because the whole point is
/// that it fits a creature of any size.
#[derive(Clone, Copy, Debug, PartialEq, Serialize, Deserialize)]
pub struct GaitParams {
    /// Walk cadence: complete gait cycles per second.
    pub walk_cadence_hz: f64,
    /// Run cadence: complete gait cycles per second.
    pub run_cadence_hz: f64,
    /// Peak hip swing at a walk, degrees either side of the bind pose.
    pub hip_swing_deg: f64,
    /// Peak knee flex at a walk, degrees. Applied as a **negative** rotation
    /// about the knee's local X, which is the direction
    /// [`crate::template`]'s hinge limit permits — a knee that bends the other
    /// way is the single most visible rig failure there is.
    pub knee_flex_deg: f64,
    /// Peak arm counter-swing at a walk, degrees. Bipeds only (no other plan has
    /// arms).
    pub arm_swing_deg: f64,
    /// How much larger a running stride is than a walking one. Multiplies the
    /// three angles above.
    pub run_stride_scale: f64,
    /// Vertical bob of the hips while moving, as a fraction of the hips' bind
    /// height. Two bobs per gait cycle (one per step).
    pub bob_ratio: f64,
    /// Seconds of one idle breath cycle.
    pub idle_period_s: f64,
    /// Vertical bob of the hips while idle, as a fraction of the hips' bind
    /// height.
    pub idle_bob_ratio: f64,
    /// Chest pitch while idle, degrees.
    pub idle_pitch_deg: f64,
    /// Keyframes sampled per cycle. The clip carries `keys_per_cycle + 1` keys:
    /// the closing one repeats the first so the loop seam is exact rather than
    /// nearly exact.
    pub keys_per_cycle: u32,
}

impl Default for GaitParams {
    /// A walking creature: a 0.9 Hz walk and a 1.6 Hz run, a 22° hip swing, a 45°
    /// knee flex, arms counter-swinging 18°, and a 2 % bob.
    ///
    /// These are *shape* numbers, not measurements of any animal — the speed a
    /// generated character walks at comes from its own leg length, not from
    /// here.
    fn default() -> Self {
        Self {
            walk_cadence_hz: 0.9,
            run_cadence_hz: 1.6,
            hip_swing_deg: 22.0,
            knee_flex_deg: 45.0,
            arm_swing_deg: 18.0,
            run_stride_scale: 1.6,
            bob_ratio: 0.02,
            idle_period_s: 4.0,
            idle_bob_ratio: 0.006,
            idle_pitch_deg: 2.0,
            keys_per_cycle: 12,
        }
    }
}

/// Why a locomotion set refused to generate.
#[derive(Debug, Error, PartialEq)]
pub enum LocomotionError {
    /// The rig does not carry a joint the plan's naming contract requires.
    #[error(
        "this rig has no joint named `{name}`, which a {plan} locomotion set drives \
         (generate the rig from a template, or rename the joint to the canonical name)"
    )]
    MissingJoint { name: String, plan: &'static str },
    /// A gait parameter was NaN, infinite or outside its documented range.
    #[error("gait parameter `{param}` is {value}, which is not a usable value ({why})")]
    BadParam {
        param: &'static str,
        value: String,
        why: &'static str,
    },
    /// A leg has no length in the bind pose, so it has no stride and no speed.
    #[error("leg `{name}` is {length_m:.4} m long in the bind pose — it has no stride to walk on")]
    DegenerateLeg { name: String, length_m: f64 },
}

/// A generated locomotion set: three clips and the two speeds the machine's
/// thresholds are derived from.
#[derive(Debug, Clone, PartialEq)]
pub struct LocomotionSet {
    /// A breathing sway, in place.
    pub idle: AnimClip,
    /// The walk cycle.
    pub walk: AnimClip,
    /// The run cycle: the same generator at a higher cadence and a longer stride.
    pub run: AnimClip,
    /// The ground speed the **walk** cycle's stride depicts (m/s). See the module
    /// docs: a threshold derived from this rig's legs, not a property of the clip.
    pub walk_speed_m_s: f64,
    /// The ground speed the **run** cycle's stride depicts (m/s).
    pub run_speed_m_s: f64,
    /// The legs the generator found and drove, longest first is *not* the order —
    /// it is girdle-then-side, the order [`crate::template`] emits them in.
    pub legs: Vec<LegSummary>,
}

/// One driven leg, as the wizard's preview reports it.
#[derive(Debug, Clone, PartialEq)]
pub struct LegSummary {
    /// The `upper_leg_*` joint's name — the whole leg is identified by it.
    pub name: String,
    /// Hip-to-foot distance in the bind pose (metres).
    pub length_m: f64,
    /// Where in the gait cycle this leg's swing starts, in `[0, 1)`.
    pub phase: f64,
}

impl LocomotionSet {
    /// The speed at which the machine leaves `idle` for `walk`.
    ///
    /// A quarter of the walk cycle's own depicted speed: low enough that a
    /// character nudging forward is already stepping, high enough that
    /// floating-point residue on a stationary controller does not start the feet
    /// moving.
    pub fn walk_threshold_m_s(&self) -> f64 {
        self.walk_speed_m_s * 0.25
    }

    /// The speed at which the machine leaves `walk` for `run` — halfway between
    /// the two cycles' depicted speeds, so each state is used where its own
    /// stride is the closer match.
    pub fn run_threshold_m_s(&self) -> f64 {
        (self.walk_speed_m_s + self.run_speed_m_s) * 0.5
    }
}

/// Build the idle / walk / run set for `rig`, which must be shaped like a `plan`
/// generated by [`crate::template::build_template`] (or fitted from one — the
/// auto-fit keeps the names).
///
/// The clips are authored against `rig`'s **joint indices**, so they are only
/// valid for this skeleton; that is the whole reason they are generated rather
/// than shipped.
pub fn build_locomotion(
    plan: BodyPlan,
    rig: &SkeletonAsset,
    gait: &GaitParams,
) -> Result<LocomotionSet, LocomotionError> {
    validate_gait(gait)?;
    let skeleton = &rig.skeleton;
    let globals = bind_globals(skeleton);
    let legs = legs_of(plan, rig, &globals)?;
    let arms = arms_of(plan, skeleton)?;

    let hips = joint(skeleton, "hips", plan)?;
    let chest = joint(skeleton, "chest", plan)?;
    let hips_bind = skeleton.joints()[hips as usize].local_bind.translation;
    // The hips' bind height is what both bobs are a fraction of. A rig whose hips
    // sit at the origin (a fitted rig centred on its mesh, say) gets its scale
    // from the longest leg instead — a bob of zero would be a silently missing
    // channel, which is the failure this crate keeps refusing to ship.
    let hip_height_m = {
        let h = globals[hips as usize].y as f64;
        if h.abs() > 1.0e-4 {
            h.abs()
        } else {
            legs.iter().map(|l| l.length_m).fold(0.0, f64::max)
        }
    };

    // The stride the WALK depicts: a leg of length L swinging ±θ sweeps its foot
    // through `2 L sin θ` of ground, and one gait cycle plants each leg once.
    // Measured on the *mean* leg, because a hexapod's girdles are not all the
    // same height and one arbitrary leg is not the creature.
    let mean_leg_m = legs.iter().map(|l| l.length_m).sum::<f64>() / legs.len() as f64;
    let walk_swing_rad = gait.hip_swing_deg.to_radians();
    let run_swing_rad = (gait.hip_swing_deg * gait.run_stride_scale).to_radians();
    let walk_stride_m = 2.0 * mean_leg_m * psin64(walk_swing_rad);
    let run_stride_m = 2.0 * mean_leg_m * psin64(run_swing_rad);

    let knee_limit = knee_flex_ceiling(rig, &legs);

    let idle = idle_clip(gait, hips, chest, hips_bind, hip_height_m);
    let walk = gait_clip(
        "walk",
        gait,
        1.0,
        gait.walk_cadence_hz,
        knee_limit,
        hips,
        hips_bind,
        hip_height_m,
        &legs,
        &arms,
    );
    let run = gait_clip(
        "run",
        gait,
        gait.run_stride_scale,
        gait.run_cadence_hz,
        knee_limit,
        hips,
        hips_bind,
        hip_height_m,
        &legs,
        &arms,
    );

    Ok(LocomotionSet {
        idle,
        walk,
        run,
        walk_speed_m_s: walk_stride_m * gait.walk_cadence_hz,
        run_speed_m_s: run_stride_m * gait.run_cadence_hz,
        legs: legs
            .iter()
            .map(|l| LegSummary {
                name: l.name.clone(),
                length_m: l.length_m,
                phase: l.phase,
            })
            .collect(),
    })
}

/// Wire a generated set into a three-state machine on one `speed` parameter.
///
/// `idle` / `walk` / `run` are the clips' asset GUIDs (raw bytes — this crate
/// stays `uuid`-free, like every other `ClipRef` in it). The caller writes the
/// three `.inf_anim` assets first and hands their ids here, which is the only
/// order that works: a machine references clips by GUID and a GUID exists once
/// the asset does.
///
/// # The transition table
///
/// ```text
///   idle ──(speed >  walk_threshold)──▶ walk ──(speed >  run_threshold)──▶ run
///   idle ◀─(speed <= walk_threshold)── walk ◀─(speed <= run_threshold)─── run
/// ```
///
/// The two conditions out of each state are **exact complements** (`>` against
/// `<=` on the same constant), so the machine cannot chatter between them and
/// needs no hysteresis band. It also cannot go from `idle` straight to `run`:
/// that costs one fixed step of latency through `walk`, which at 60 Hz is 16 ms
/// and buys a table with four edges instead of six.
pub fn locomotion_machine(
    set: &LocomotionSet,
    idle: ClipRef,
    walk: ClipRef,
    run: ClipRef,
) -> StateMachine {
    let walk_at = set.walk_threshold_m_s();
    let run_at = set.run_threshold_m_s();
    let state = |name: &str, clip: ClipRef, x: f32| SmState::clip_at(name, clip, (x, 0.0));
    // The cross-fade `samples/character-demo` uses; long enough to hide the pose
    // discontinuity between two cycles at different cadences, short enough that
    // the character is not still blending when the player has let go of the
    // stick. `EaseInOut` (v2) is what makes a fade that short read as deliberate:
    // zero slope at both ends, and it costs nothing — it is a polynomial.
    let edge = |from: usize, to: usize, op: CmpOp, value: f64| {
        SmTransition::on(from, to, 0.15, SPEED_VAR, op, value).with_curve(BlendCurve::EaseInOut)
    };
    StateMachine {
        states: vec![
            state(STATE_NAMES[0], idle, 0.0),
            state(STATE_NAMES[1], walk, 240.0),
            state(STATE_NAMES[2], run, 480.0),
        ],
        transitions: vec![
            edge(0, 1, CmpOp::Gt, walk_at),
            edge(1, 0, CmpOp::Le, walk_at),
            edge(1, 2, CmpOp::Gt, run_at),
            edge(2, 1, CmpOp::Le, run_at),
        ],
        entry: 0,
        // **The generated machine DECLARES its parameter** (v2). Nothing forces
        // it to — an undeclared name still reads as a `Float` defaulting to 0,
        // which is v1's rule — but a declared table is what the editor's rule
        // builder, the `anim.*` kit and a reviewer read to know what this machine
        // expects from gameplay. A machine derived by a generator should not be
        // the one that leaves that implicit.
        params: vec![SmParam::float(SPEED_VAR)],
        profiles: Vec::new(),
    }
}

// ── the generator's internals ───────────────────────────────────────────────

/// One leg, resolved to joint indices.
#[derive(Debug, Clone)]
struct Leg {
    name: String,
    upper: u16,
    lower: u16,
    length_m: f64,
    phase: f64,
    /// `0` for the left side, `1` for the right — the arm on the same side
    /// counter-swings against it.
    side: usize,
}

/// One arm, resolved to a joint index. Bipeds only.
#[derive(Debug, Clone, Copy)]
struct Arm {
    upper: u16,
    side: usize,
}

fn plan_label(plan: BodyPlan) -> &'static str {
    match plan {
        BodyPlan::Biped => "biped",
        BodyPlan::Quadruped => "quadruped",
        BodyPlan::Hexapod => "hexapod",
        BodyPlan::Npedal { .. } => "n-pedal",
    }
}

fn joint(skeleton: &Skeleton, name: &str, plan: BodyPlan) -> Result<u16, LocomotionError> {
    skeleton
        .index_of(name)
        .ok_or_else(|| LocomotionError::MissingJoint {
            name: name.to_string(),
            plan: plan_label(plan),
        })
}

/// Bind-pose **global translations**, composed down the parent chain.
///
/// Multiplies and adds only — no inverse, no trigonometry — so a rig with
/// rotated bind joints composes correctly and a rig without them costs nothing.
/// The joint list is topological by [`Skeleton::new`]'s own invariant, so one
/// forward pass is enough.
fn bind_globals(skeleton: &Skeleton) -> Vec<glam::Vec3> {
    let mut mats: Vec<glam::Mat4> = Vec::with_capacity(skeleton.len());
    for j in skeleton.joints() {
        let local = j.local_bind.to_mat4();
        let m = match j.parent {
            Some(p) => mats[p as usize] * local,
            None => local,
        };
        mats.push(m);
    }
    mats.iter().map(|m| m.w_axis.truncate()).collect()
}

/// Resolve the plan's legs, in girdle-then-side order, with their gait phases.
///
/// # The phase rule
///
/// `phase(side, girdle) = side/2 + girdle/(2 · girdles)`.
///
/// One line, and it is a real gait for every plan the template generates:
///
/// * a **biped** (1 girdle) gets `l = 0`, `r = ½` — exact antiphase, which is
///   what walking is;
/// * a **quadruped** (2 girdles) gets `0, ¼, ½, ¾` in the order rear-left,
///   front-left, rear-right, front-right — the lateral-sequence walk, the gait a
///   horse uses at low speed;
/// * a **hexapod** (3 girdles) gets sixths, which is a metachronal wave — the
///   gait an insect walks with.
///
/// So the same arithmetic produces the right-looking gait for each, rather than
/// a per-plan table that would have to grow a row for every new plan.
fn legs_of(
    plan: BodyPlan,
    rig: &SkeletonAsset,
    globals: &[glam::Vec3],
) -> Result<Vec<Leg>, LocomotionError> {
    let skeleton = &rig.skeleton;
    let girdles = (plan.legs() / 2) as usize;
    let mut out = Vec::with_capacity(plan.legs() as usize);
    for g in 0..girdles {
        for (side, tag) in ["l", "r"].iter().enumerate() {
            let suffix = leg_suffix(tag, g, girdles);
            let upper = joint(skeleton, &format!("upper_leg_{suffix}"), plan)?;
            let lower = joint(skeleton, &format!("lower_leg_{suffix}"), plan)?;
            let foot = joint(skeleton, &format!("foot_{suffix}"), plan)?;
            let length_m = (globals[foot as usize] - globals[upper as usize]).length() as f64;
            if !(length_m.is_finite() && length_m > 1.0e-4) {
                return Err(LocomotionError::DegenerateLeg {
                    name: format!("upper_leg_{suffix}"),
                    length_m,
                });
            }
            out.push(Leg {
                name: format!("upper_leg_{suffix}"),
                upper,
                lower,
                length_m,
                phase: side as f64 * 0.5 + g as f64 / (2.0 * girdles as f64),
                side,
            });
        }
    }
    Ok(out)
}

/// Resolve the biped's two arms. Every other plan has none, and asking for them
/// would be a refusal on a rig that is exactly right.
fn arms_of(plan: BodyPlan, skeleton: &Skeleton) -> Result<Vec<Arm>, LocomotionError> {
    if !plan.has_arms() {
        return Ok(Vec::new());
    }
    let mut out = Vec::with_capacity(2);
    for (side, tag) in ["l", "r"].iter().enumerate() {
        out.push(Arm {
            upper: joint(skeleton, &format!("upper_arm_{tag}"), plan)?,
            side,
        });
    }
    Ok(out)
}

/// The largest knee flex this rig's own limits permit, in **degrees**, or `None`
/// when no knee carries one.
///
/// [`crate::template::build_template`] emits `hinge_x(knee, -150, 0)` precisely
/// so a solver — and now a generator — can respect it. A generated clip is not
/// run through [`crate::ik::solve_chain`]'s clamp (nothing solves a clip), so
/// this is the only thing standing between a large `knee_flex_deg` and a knee
/// hyper-extending through its own authored range in committed content.
///
/// The **smallest** magnitude across the knees, not the largest: a table where
/// one knee is tighter than the others describes a creature that cannot flex
/// that one further, and a set that flexed the others further would be internally
/// inconsistent.
///
/// # The bound this leaves, stated rather than glossed
///
/// The flex direction is **fixed negative**, so a knee whose authored range lies
/// entirely on the positive side (`min = 0`, `max = 150` — an inverted hinge)
/// yields a ceiling of zero and a leg that walks with a **straight knee**,
/// silently. Nothing this engine generates falls in the gap:
/// `build_template` emits `hinge_x(knee, -150, 0)` and nothing else, and the
/// Skeleton Editor is the only way to author the other sign. The fix is to pick
/// the side of zero the limit permits and sign the flex with it, which changes
/// what the generator emits for a rig class that does not exist yet;
/// `an_inverted_knee_hinge_walks_stiff_legged_and_that_is_ledgered` asserts the
/// current behaviour, so the day that lands the test fails and this paragraph is
/// rewritten instead of forgotten (the `a_multi_axis_limit_is_not_applied`
/// discipline, P24.3).
fn knee_flex_ceiling(rig: &SkeletonAsset, legs: &[Leg]) -> Option<f64> {
    let mut ceiling: Option<f64> = None;
    for leg in legs {
        let Some(limit) = rig.limit(leg.lower) else {
            continue;
        };
        if !limit.is_free(0) {
            continue;
        }
        // The flex direction is negative about local X, so the range that matters
        // is how far below zero the limit reaches.
        let reach = (-limit.min_deg[0] as f64).max(0.0);
        ceiling = Some(match ceiling {
            Some(c) => c.min(reach),
            None => reach,
        });
    }
    ceiling
}

/// A rotation of `angle_rad` about the joint's local **X**, written out rather
/// than built.
///
/// `Quat::from_rotation_x` is `f32::sin_cos`, which is libm, which is not
/// bit-portable — and these values are written into a `.inf_anim` on disk. The
/// half-angle identity is the whole of the construction, so there is nothing to
/// lose by spelling it.
fn quat_x(angle_rad: f64) -> [f32; 4] {
    let half = angle_rad * 0.5;
    [psin64(half) as f32, 0.0, 0.0, pcos64(half) as f32]
}

/// The key times of one cycle: `n + 1` of them, closing exactly on `period`.
fn cycle_times(period: f64, n: u32) -> Vec<f32> {
    (0..=n)
        .map(|i| (period * i as f64 / n as f64) as f32)
        .collect()
}

/// The idle clip: a breath. The hips rise and fall once per cycle and the chest
/// pitches with them.
fn idle_clip(
    gait: &GaitParams,
    hips: u16,
    chest: u16,
    hips_bind: [f32; 3],
    hip_height_m: f64,
) -> AnimClip {
    let n = gait.keys_per_cycle;
    let times = cycle_times(gait.idle_period_s, n);
    let bob = gait.idle_bob_ratio * hip_height_m;
    let pitch = gait.idle_pitch_deg.to_radians();

    let mut hip_track = JointTrack::new(hips);
    hip_track.translation = Some(Vec3Track::new(
        times.clone(),
        (0..=n)
            .map(|i| {
                let u = i as f64 / n as f64;
                [
                    hips_bind[0],
                    hips_bind[1] + (bob * psin64(TAU * u)) as f32,
                    hips_bind[2],
                ]
            })
            .collect(),
        Interpolation::Linear,
    ));

    let mut chest_track = JointTrack::new(chest);
    chest_track.rotation = Some(QuatTrack::new(
        times,
        (0..=n)
            .map(|i| {
                let u = i as f64 / n as f64;
                quat_x(pitch * psin64(TAU * u))
            })
            .collect(),
        Interpolation::Linear,
    ));

    AnimClip::new("idle", vec![hip_track, chest_track])
}

/// One gait cycle: hips bobbing twice, every leg swinging on its own phase, and
/// (on a biped) the arms counter-swinging against the leg on the same side.
#[allow(clippy::too_many_arguments)]
fn gait_clip(
    name: &str,
    gait: &GaitParams,
    stride_scale: f64,
    cadence_hz: f64,
    knee_ceiling_deg: Option<f64>,
    hips: u16,
    hips_bind: [f32; 3],
    hip_height_m: f64,
    legs: &[Leg],
    arms: &[Arm],
) -> AnimClip {
    let n = gait.keys_per_cycle;
    let period = 1.0 / cadence_hz;
    let times = cycle_times(period, n);

    let swing = (gait.hip_swing_deg * stride_scale).to_radians();
    let flex_deg = match knee_ceiling_deg {
        Some(ceiling) => (gait.knee_flex_deg * stride_scale).min(ceiling),
        None => gait.knee_flex_deg * stride_scale,
    };
    let flex = flex_deg.to_radians();
    let arm_swing = (gait.arm_swing_deg * stride_scale).to_radians();
    let bob = gait.bob_ratio * hip_height_m * stride_scale;

    let mut tracks: Vec<JointTrack> = Vec::with_capacity(1 + legs.len() * 2 + arms.len());

    // The hips: two bobs per cycle (one per step), highest at the seam so the
    // loop closes on the same value it opened with.
    let mut hip_track = JointTrack::new(hips);
    hip_track.translation = Some(Vec3Track::new(
        times.clone(),
        (0..=n)
            .map(|i| {
                let u = i as f64 / n as f64;
                [
                    hips_bind[0],
                    hips_bind[1] + (bob * pcos64(2.0 * TAU * u)) as f32,
                    hips_bind[2],
                ]
            })
            .collect(),
        Interpolation::Linear,
    ));
    tracks.push(hip_track);

    for leg in legs {
        // The hip swings forward at a quarter cycle. Forward is **+Z** (the
        // template's torso runs +Z from the rear girdle to the shoulders) and a
        // positive rotation about local X takes a down-hanging bone toward −Z, so
        // the sign is negated here rather than in the caller's head.
        let mut upper = JointTrack::new(leg.upper);
        upper.rotation = Some(QuatTrack::new(
            times.clone(),
            (0..=n)
                .map(|i| {
                    let u = i as f64 / n as f64 + leg.phase;
                    quat_x(-swing * psin64(TAU * u))
                })
                .collect(),
            Interpolation::Linear,
        ));
        tracks.push(upper);

        // The knee flexes through the swing phase and is straight at the moment
        // the foot is under the body. `−A·½(1 + cos)` peaks at `u = 0` (mid
        // swing) and is exactly zero at `u = ½` (mid stance), and it never leaves
        // `[−A, 0]` — the half of the hinge the limit table permits.
        let mut lower = JointTrack::new(leg.lower);
        lower.rotation = Some(QuatTrack::new(
            times.clone(),
            (0..=n)
                .map(|i| {
                    let u = i as f64 / n as f64 + leg.phase;
                    quat_x(-flex * 0.5 * (1.0 + pcos64(TAU * u)))
                })
                .collect(),
            Interpolation::Linear,
        ));
        tracks.push(lower);
    }

    // The arms swing **against** the leg on their own side, which is what a
    // walking biped does and what makes a generated walk read as a walk rather
    // than as a march.
    for arm in arms {
        let Some(leg) = legs.iter().find(|l| l.side == arm.side) else {
            continue;
        };
        let mut track = JointTrack::new(arm.upper);
        track.rotation = Some(QuatTrack::new(
            times.clone(),
            (0..=n)
                .map(|i| {
                    let u = i as f64 / n as f64 + leg.phase;
                    quat_x(arm_swing * psin64(TAU * u))
                })
                .collect(),
            Interpolation::Linear,
        ));
        tracks.push(track);
    }

    AnimClip::new(name, tracks)
}

/// Reject degenerate gait parameters **as values** — [`crate::template`]'s rule,
/// for the same reason: a clamped cadence produces a clip that is *almost* what
/// was asked for and says nothing about the difference.
fn validate_gait(g: &GaitParams) -> Result<(), LocomotionError> {
    let positive = |param: &'static str, v: f64| -> Result<(), LocomotionError> {
        if !v.is_finite() || v <= 0.0 {
            return Err(LocomotionError::BadParam {
                param,
                value: format!("{v}"),
                why: "must be finite and greater than zero",
            });
        }
        Ok(())
    };
    let non_negative = |param: &'static str, v: f64| -> Result<(), LocomotionError> {
        if !v.is_finite() || v < 0.0 {
            return Err(LocomotionError::BadParam {
                param,
                value: format!("{v}"),
                why: "must be finite and not negative",
            });
        }
        Ok(())
    };
    positive("walk_cadence_hz", g.walk_cadence_hz)?;
    positive("run_cadence_hz", g.run_cadence_hz)?;
    positive("hip_swing_deg", g.hip_swing_deg)?;
    positive("idle_period_s", g.idle_period_s)?;
    positive("run_stride_scale", g.run_stride_scale)?;
    non_negative("knee_flex_deg", g.knee_flex_deg)?;
    non_negative("arm_swing_deg", g.arm_swing_deg)?;
    non_negative("bob_ratio", g.bob_ratio)?;
    non_negative("idle_bob_ratio", g.idle_bob_ratio)?;
    non_negative("idle_pitch_deg", g.idle_pitch_deg)?;
    // A swing past a right angle is a leg pointing behind its own hip; the clip
    // would still generate, but `2 L sin θ` stops growing with θ, so the derived
    // speed would go DOWN as the stride got wilder.
    if g.hip_swing_deg >= 90.0 {
        return Err(LocomotionError::BadParam {
            param: "hip_swing_deg",
            value: format!("{}", g.hip_swing_deg),
            why: "must be under 90°, past which a longer swing is a shorter stride",
        });
    }
    if !(2..=MAX_KEYS_PER_CYCLE).contains(&g.keys_per_cycle) {
        return Err(LocomotionError::BadParam {
            param: "keys_per_cycle",
            value: format!("{}", g.keys_per_cycle),
            why: "must be between 2 and MAX_KEYS_PER_CYCLE",
        });
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::template::{build_template, BodyParams};

    fn biped() -> SkeletonAsset {
        build_template(BodyPlan::Biped, &BodyParams::default()).unwrap()
    }
    fn quadruped() -> SkeletonAsset {
        build_template(BodyPlan::Quadruped, &BodyParams::default()).unwrap()
    }

    #[test]
    fn a_biped_gets_two_antiphase_legs_and_counter_swinging_arms() {
        let rig = biped();
        let set = build_locomotion(BodyPlan::Biped, &rig, &GaitParams::default()).unwrap();
        assert_eq!(set.legs.len(), 2);
        assert_eq!(set.legs[0].phase, 0.0);
        assert_eq!(set.legs[1].phase, 0.5);

        // hips + (upper, lower) × 2 legs + 2 arms.
        assert_eq!(set.walk.tracks.len(), 1 + 4 + 2);
        let arm = rig.skeleton.index_of("upper_arm_l").unwrap();
        let leg = rig.skeleton.index_of("upper_leg_l").unwrap();
        let arm_track = set.walk.tracks.iter().find(|t| t.joint == arm).unwrap();
        let leg_track = set.walk.tracks.iter().find(|t| t.joint == leg).unwrap();
        // A quarter of the way through the cycle both are at their extreme, and
        // the extremes are opposite: `x` carries the whole rotation here.
        let q = |t: &JointTrack, i: usize| t.rotation.as_ref().unwrap().values[i][0];
        let k = (GaitParams::default().keys_per_cycle / 4) as usize;
        assert!(
            q(arm_track, k) * q(leg_track, k) < 0.0,
            "the arm and the leg on the same side swing the same way: arm {}, leg {}",
            q(arm_track, k),
            q(leg_track, k)
        );
    }

    #[test]
    fn a_quadruped_walks_a_lateral_sequence() {
        let rig = quadruped();
        let set = build_locomotion(BodyPlan::Quadruped, &rig, &GaitParams::default()).unwrap();
        assert_eq!(
            set.legs.iter().map(|l| l.phase).collect::<Vec<_>>(),
            vec![0.0, 0.5, 0.25, 0.75],
            "girdle-then-side order, quarter-cycle apart"
        );
        // No arms on a quadruped, and no arm tracks either.
        assert_eq!(set.walk.tracks.len(), 1 + 8);
    }

    /// **The knee never leaves the half of its hinge the rig authorizes.**
    ///
    /// The clip is not run through the IK clamp — nothing solves a clip — so this
    /// is the only thing between an ambitious `knee_flex_deg` and committed
    /// content in which a knee bends backwards.
    #[test]
    fn the_knee_flexes_only_the_way_its_limit_allows() {
        let rig = biped();
        let gait = GaitParams {
            // Far past the −150° the template's hinge permits, and past 180°
            // where the half-angle sine changes sign.
            knee_flex_deg: 400.0,
            ..GaitParams::default()
        };
        let set = build_locomotion(BodyPlan::Biped, &rig, &gait).unwrap();
        let knee = rig.skeleton.index_of("lower_leg_l").unwrap();
        let track = set.walk.tracks.iter().find(|t| t.joint == knee).unwrap();
        let ceiling = knee_flex_ceiling(
            &rig,
            &legs_of(BodyPlan::Biped, &rig, &bind_globals(&rig.skeleton)).unwrap(),
        );
        assert_eq!(ceiling, Some(150.0), "the template's own hinge");
        for v in &track.rotation.as_ref().unwrap().values {
            // A negative rotation about X has a non-positive `x` component for
            // any angle in (−180°, 0].
            assert!(
                v[0] <= 1.0e-6,
                "a knee key rotates the wrong way about X: {v:?}"
            );
            // …and it never exceeds the authorized magnitude.
            let half = 150f64.to_radians() * 0.5;
            assert!(
                (v[0] as f64) >= -psin64(half) - 1.0e-6,
                "a knee key flexes past the rig's own limit: {v:?}"
            );
        }
    }

    /// **The bound `knee_flex_ceiling` documents, measured.**
    ///
    /// A knee whose authored range is entirely positive — an inverted hinge, which
    /// only the Skeleton Editor can produce — walks with a straight knee, because
    /// the flex direction is fixed negative. Asserted as it is, so the day the
    /// generator learns to sign the flex from the limit this test fails and the
    /// paragraph on `knee_flex_ceiling` gets rewritten rather than forgotten.
    #[test]
    fn an_inverted_knee_hinge_walks_stiff_legged_and_that_is_ledgered() {
        let mut rig = biped();
        let knees: Vec<u16> = rig
            .skeleton
            .joints()
            .iter()
            .enumerate()
            .filter(|(_, j)| j.name.starts_with("lower_leg_"))
            .map(|(i, _)| i as u16)
            .collect();
        assert_eq!(knees.len(), 2, "the fixture must have knees to invert");
        for limit in &mut rig.limits {
            if knees.contains(&limit.joint) {
                // The same range, the other way round.
                *limit = crate::template::JointLimit::hinge_x(limit.joint, 0.0, 150.0);
            }
        }
        let set = build_locomotion(BodyPlan::Biped, &rig, &GaitParams::default()).unwrap();
        for knee in knees {
            let track = set.walk.tracks.iter().find(|t| t.joint == knee).unwrap();
            let rot = track.rotation.as_ref().unwrap();
            // Every key is the same rotation, and that rotation is (numerically)
            // the identity. Not `== [0,0,0,1]`: `pcos64(0)` is 0.999_999_94, which
            // is the polynomial's documented ~1e-7 and what every key in every
            // generated clip carries — `QuatTrack::sample` normalizes.
            assert!(
                rot.values.iter().all(|v| v[0].abs() < 1.0e-6
                    && v[1] == 0.0
                    && v[2] == 0.0
                    && (v[3] - 1.0).abs() < 1.0e-6),
                "the knee moved; the generator now signs the flex from the limit — \
                 delete this test and rewrite `knee_flex_ceiling`'s bound paragraph"
            );
        }
        // …and the hips still swing, so the straight knee is the *limit's* doing
        // and not a clip that came out empty.
        let hip = rig.skeleton.index_of("upper_leg_l").unwrap();
        let hip_track = set.walk.tracks.iter().find(|t| t.joint == hip).unwrap();
        assert!(
            hip_track
                .rotation
                .as_ref()
                .unwrap()
                .values
                .iter()
                .any(|v| v[0] != 0.0),
            "the whole walk is inert — this arm is measuring an empty clip"
        );
    }

    /// **Byte-reproducible**, which is what the module docs claim and a stronger
    /// property than `PartialEq` can see.
    ///
    /// `assert_eq!` on an `AnimClip` compares `f32`s, and `-0.0 == 0.0` is *true*
    /// while their bytes differ — so a generator that flipped a zero's sign on
    /// alternate runs would satisfy a structural comparison and write two
    /// different `.inf_anim` files. These keyframes go on disk, into a cook and
    /// into a pack, so the claim has to be measured on
    /// [`inf_asset::encode`] — the same door
    /// `AssetProject::write_asset` puts them through, and the same shape
    /// [`crate::template`]'s `the_same_params_generate_the_same_bytes` uses.
    #[test]
    fn the_same_rig_generates_the_same_clips() {
        let rig = biped();
        let a = build_locomotion(BodyPlan::Biped, &rig, &GaitParams::default()).unwrap();
        let b = build_locomotion(BodyPlan::Biped, &rig, &GaitParams::default()).unwrap();
        assert_eq!(a, b);

        let bytes = |set: &LocomotionSet| -> Vec<Vec<u8>> {
            [&set.idle, &set.walk, &set.run]
                .iter()
                .map(|c| {
                    inf_asset::encode(&crate::asset::AnimClipAsset::new((*c).clone(), None))
                        .unwrap()
                })
                .collect()
        };
        assert_eq!(bytes(&a), bytes(&b), "a generated clip is not byte-stable");

        // …and the comparison is a filter rather than a formality: a different
        // rig writes different bytes. Without this the assertion above would pass
        // for a generator that emitted the same three clips for everything.
        let tall = build_template(
            BodyPlan::Biped,
            &BodyParams {
                height_m: 2.4,
                ..BodyParams::default()
            },
        )
        .unwrap();
        let c = build_locomotion(BodyPlan::Biped, &tall, &GaitParams::default()).unwrap();
        assert_ne!(bytes(&a), bytes(&c));

        // **And the two comparisons really are different checks.** Written out
        // rather than asserted about the generator, because the whole point is
        // that no generated value has to have this shape for the structural
        // comparison to be the weaker one.
        let key = |x: f32| {
            AnimClip::new(
                "k",
                vec![JointTrack {
                    rotation: Some(QuatTrack::new(
                        vec![0.0],
                        vec![[x, 0.0, 0.0, 1.0]],
                        Interpolation::Linear,
                    )),
                    ..JointTrack::new(0)
                }],
            )
        };
        let (plus, minus) = (key(0.0), key(-0.0));
        assert_eq!(plus, minus, "`-0.0 == 0.0`, which is the whole problem");
        assert_ne!(
            inf_asset::encode(&crate::asset::AnimClipAsset::new(plus, None)).unwrap(),
            inf_asset::encode(&crate::asset::AnimClipAsset::new(minus, None)).unwrap(),
            "the byte comparison above adds nothing over `PartialEq`"
        );
    }

    /// **Proportions reach the animation, not only the skeleton.** The whole
    /// reason the set is generated rather than shipped.
    #[test]
    fn a_taller_creature_walks_faster_and_animates_differently() {
        let short = build_template(
            BodyPlan::Biped,
            &BodyParams {
                height_m: 1.2,
                ..BodyParams::default()
            },
        )
        .unwrap();
        let tall = build_template(
            BodyPlan::Biped,
            &BodyParams {
                height_m: 2.4,
                ..BodyParams::default()
            },
        )
        .unwrap();
        let a = build_locomotion(BodyPlan::Biped, &short, &GaitParams::default()).unwrap();
        let b = build_locomotion(BodyPlan::Biped, &tall, &GaitParams::default()).unwrap();
        assert!(
            b.walk_speed_m_s > a.walk_speed_m_s * 1.5,
            "twice the height must not walk at the same speed: {} vs {}",
            a.walk_speed_m_s,
            b.walk_speed_m_s
        );
        assert_ne!(a.walk, b.walk, "the bob is a fraction of a real height");
        assert_ne!(a.idle, b.idle);
    }

    #[test]
    fn every_cycle_closes_on_its_own_first_key() {
        let rig = biped();
        let set = build_locomotion(BodyPlan::Biped, &rig, &GaitParams::default()).unwrap();
        for clip in [&set.idle, &set.walk, &set.run] {
            for track in &clip.tracks {
                if let Some(r) = &track.rotation {
                    assert_eq!(
                        r.values.first(),
                        r.values.last(),
                        "{}'s rotation on joint {} does not loop",
                        clip.name,
                        track.joint
                    );
                }
                if let Some(t) = &track.translation {
                    assert_eq!(t.values.first(), t.values.last());
                }
            }
        }
    }

    #[test]
    fn the_machine_is_wired_to_one_speed_variable() {
        let rig = biped();
        let set = build_locomotion(BodyPlan::Biped, &rig, &GaitParams::default()).unwrap();
        let sm = locomotion_machine(&set, [1; 16], [2; 16], [3; 16]);
        assert_eq!(sm.entry, 0);
        assert_eq!(sm.states.len(), 3);
        assert_eq!(sm.transitions.len(), 4);
        for t in &sm.transitions {
            let flat = t
                .condition
                .as_flat_and()
                .expect("the generated edges stay the flat float compares v1 authored");
            assert_eq!(flat.len(), 1);
            assert_eq!(flat[0].param, SPEED_VAR);
        }
        // v2: the generator DECLARES the one parameter it drives, so a reader (and
        // the rule builder) can see what this machine expects from gameplay.
        assert_eq!(sm.params.len(), 1);
        assert_eq!(sm.params[0].name, SPEED_VAR);
        assert_eq!(sm.params[0].kind, crate::state_machine::SmParamKind::Float);
        // …and the whole machine passes the door a decoded one has to pass.
        sm.validate().expect("the generated machine must validate");
        assert!(set.walk_threshold_m_s() < set.run_threshold_m_s());
    }

    /// The machine actually walks its states when `speed` moves — the property
    /// the wizard's whole "wired to a state machine" claim rests on, checked
    /// against the real evaluator rather than by reading the table.
    #[test]
    fn the_generated_machine_climbs_and_falls_with_speed() {
        let rig = biped();
        let set = build_locomotion(BodyPlan::Biped, &rig, &GaitParams::default()).unwrap();
        let sm = locomotion_machine(&set, [1; 16], [2; 16], [3; 16]);
        let mut rt = crate::state_machine::SmRuntime::default();
        let dt = 1.0 / 60.0;

        let drive = |speed: f64, steps: usize, rt: &mut crate::state_machine::SmRuntime| {
            let lookup = |name: &str| (name == SPEED_VAR).then_some(speed);
            let ctx = crate::state_machine::SmContext::new(&lookup);
            for _ in 0..steps {
                rt.advance(&sm, &ctx, dt);
            }
        };

        drive(0.0, 4, &mut rt);
        assert_eq!(rt.current, 0, "a stationary character idles");
        drive(set.walk_speed_m_s, 4, &mut rt);
        assert_eq!(rt.current, 1, "at the walk cycle's own speed it walks");
        drive(set.run_speed_m_s, 4, &mut rt);
        assert_eq!(rt.current, 2, "at the run cycle's own speed it runs");
        drive(0.0, 8, &mut rt);
        assert_eq!(rt.current, 0, "and it comes all the way back down");
    }

    #[test]
    fn a_rig_without_legs_is_a_named_refusal() {
        use crate::skeleton::{Joint, JointTransform};
        let lonely = SkeletonAsset::new(
            Skeleton::new(vec![Joint {
                name: "hips".into(),
                parent: None,
                inverse_bind: glam::Mat4::IDENTITY.to_cols_array(),
                local_bind: JointTransform::IDENTITY,
            }])
            .unwrap(),
        );
        match build_locomotion(BodyPlan::Biped, &lonely, &GaitParams::default()) {
            Err(LocomotionError::MissingJoint { name, plan }) => {
                assert_eq!(name, "upper_leg_l");
                assert_eq!(plan, "biped");
            }
            other => panic!("expected a named refusal, got {other:?}"),
        }
    }

    #[test]
    fn degenerate_gait_parameters_are_refused_by_name() {
        let rig = biped();
        for (param, gait) in [
            (
                "walk_cadence_hz",
                GaitParams {
                    walk_cadence_hz: 0.0,
                    ..GaitParams::default()
                },
            ),
            (
                "hip_swing_deg",
                GaitParams {
                    hip_swing_deg: 120.0,
                    ..GaitParams::default()
                },
            ),
            (
                "keys_per_cycle",
                GaitParams {
                    keys_per_cycle: 1,
                    ..GaitParams::default()
                },
            ),
            (
                "idle_period_s",
                GaitParams {
                    idle_period_s: f64::NAN,
                    ..GaitParams::default()
                },
            ),
        ] {
            match build_locomotion(BodyPlan::Biped, &rig, &gait) {
                Err(LocomotionError::BadParam { param: got, .. }) => assert_eq!(got, param),
                other => panic!("{param} was not refused: {other:?}"),
            }
        }
    }
}
